import { attemptContextBindingDigest, canonicalJson, domainDigest, DomainError, verifyForkPin, type AttemptContextBindingV1, type JsonValue, type SealedForkPinV1 } from "@horseness/domain";
import { assertAuthenticReconstructedContext, type ReconstructedContextV1 } from "../context/reconstruction.js";
import { isTrustedSchedulerDecision, type SchedulerDecisionV1 } from "../scheduler/scheduler.js";

export type AttemptTransitionCodeV1="ATTEMPT_CREATED"|"DUPLICATE_AUTHORIZATION"|"CANCELLATION_REQUESTED"|"CANCELLATION_IDEMPOTENT"|"RETRY_CREATED"|"RETRY_NOT_PERMITTED"|"BINDING_IMMUTABLE"|"OUTCOME_UNKNOWN"|"OUTCOME_RECORDED";
export interface AttemptBindingV1 extends AttemptContextBindingV1 { readonly bindingDigest:string }
export type AttemptCancellationStateV1="none"|"requested"|"acknowledged";
export type AttemptOutcomeV1="live"|"succeeded"|"failed"|"cancelled"|"unknown";
export interface BoundAttemptV1 { readonly schemaVersion:"1";readonly workspaceId:string;readonly runId:string;readonly taskId:string;readonly attemptId:string;readonly generation:number;readonly schedulerDecisionDigest:string;readonly authorizationKey:string;readonly binding:AttemptBindingV1;readonly bindingDigest:string;readonly forkPinDigest:string;readonly contextManifestCoreDigest:string;readonly cancellation:AttemptCancellationStateV1;readonly outcome:AttemptOutcomeV1;readonly priorGeneration:number|null;readonly attemptDigest:string }
export interface AttemptTransitionResultV1 { readonly code:AttemptTransitionCodeV1;readonly attempt:BoundAttemptV1 }
const boundAttempts=new WeakSet<object>();
function seal(core:Omit<BoundAttemptV1,"attemptDigest">):BoundAttemptV1{const attempt=Object.freeze({...core,attemptDigest:domainDigest("horseness.bound-attempt.v1",core as unknown as JsonValue)});boundAttempts.add(attempt);return attempt;}
export function isBoundAttempt(value:BoundAttemptV1):boolean{const{attemptDigest,...core}=value;return boundAttempts.has(value)&&attemptDigest===domainDigest("horseness.bound-attempt.v1",core as unknown as JsonValue);}
export function createBoundAttempt(input:{decision:SchedulerDecisionV1;taskId:string;attemptId:string;generation:number;pin:SealedForkPinV1;context:ReconstructedContextV1;existing?:BoundAttemptV1}):AttemptTransitionResultV1{
 if(!isTrustedSchedulerDecision(input.decision)||input.decision.decisionCode!=="READY"||!input.decision.authorizationKey)throw new DomainError("ATTEMPT_AUTHORIZATION_INVALID");
 if(input.decision.taskId!==input.taskId||input.generation<1)throw new DomainError("ATTEMPT_IDENTITY_INVALID");verifyForkPin(input.pin);
 if(input.existing){if(input.existing.authorizationKey===input.decision.authorizationKey)return{code:"DUPLICATE_AUTHORIZATION",attempt:input.existing};throw new DomainError("ATTEMPT_ALREADY_EXISTS");}
 assertAuthenticReconstructedContext(input.context);
 const binding=input.context.binding,bindingDigest=attemptContextBindingDigest(binding);
 if(binding.attemptId!==input.attemptId||binding.generation!==input.generation||binding.forkPinDigest!==input.pin.forkPinDigest||bindingDigest!==input.context.manifest.attemptContextBindingDigest)throw new DomainError("ATTEMPT_BINDING_INVALID");
 const immutableBinding=Object.freeze({...structuredClone(binding),bindingDigest});
 return{code:"ATTEMPT_CREATED",attempt:seal({schemaVersion:"1",workspaceId:input.pin.core.workspaceId,runId:input.pin.core.runId,taskId:input.taskId,attemptId:input.attemptId,generation:input.generation,schedulerDecisionDigest:input.decision.decisionDigest,authorizationKey:input.decision.authorizationKey,binding:immutableBinding,bindingDigest,forkPinDigest:input.pin.forkPinDigest,contextManifestCoreDigest:binding.contextManifestCoreDigest,cancellation:"none",outcome:"live",priorGeneration:null})};
}
export function requestAttemptCancellation(attempt:BoundAttemptV1):AttemptTransitionResultV1{if(!isBoundAttempt(attempt))throw new DomainError("ATTEMPT_UNTRUSTED");if(attempt.outcome!=="live"&&attempt.outcome!=="unknown")return{code:"CANCELLATION_IDEMPOTENT",attempt};if(attempt.cancellation!=="none")return{code:"CANCELLATION_IDEMPOTENT",attempt};const{attemptDigest:_,...core}=attempt;return{code:"CANCELLATION_REQUESTED",attempt:seal({...core,cancellation:"requested"})};}
export function recordAttemptOutcome(attempt:BoundAttemptV1,outcome:AttemptOutcomeV1):AttemptTransitionResultV1{if(!isBoundAttempt(attempt))throw new DomainError("ATTEMPT_UNTRUSTED");if(attempt.outcome!=="live"&&attempt.outcome!=="unknown")return{code:"OUTCOME_RECORDED",attempt};if(outcome==="live")throw new DomainError("OUTCOME_INVALID");const{attemptDigest:_,...core}=attempt;return{code:outcome==="unknown"?"OUTCOME_UNKNOWN":"OUTCOME_RECORDED",attempt:seal({...core,outcome,cancellation:outcome==="cancelled"?"acknowledged":attempt.cancellation})};}
export function createRetry(input:{prior:BoundAttemptV1;decision:SchedulerDecisionV1;pin:SealedForkPinV1;context:ReconstructedContextV1;attemptId:string}):AttemptTransitionResultV1{if(!isBoundAttempt(input.prior)||input.prior.outcome==="live"||input.prior.outcome==="unknown"||input.prior.cancellation!=="none")throw new DomainError("RETRY_NOT_PERMITTED");const created=createBoundAttempt({decision:input.decision,taskId:input.prior.taskId,attemptId:input.attemptId,generation:input.prior.generation+1,pin:input.pin,context:input.context});const{attemptDigest:_,...core}=created.attempt;return{code:"RETRY_CREATED",attempt:seal({...core,priorGeneration:input.prior.generation})};}
export function assertImmutableBinding(original:BoundAttemptV1,candidate:BoundAttemptV1):void{if(!isBoundAttempt(original)||!isBoundAttempt(candidate)||original.attemptId!==candidate.attemptId||original.generation!==candidate.generation||original.bindingDigest!==candidate.bindingDigest||canonicalJson(original.binding as unknown as JsonValue)!==canonicalJson(candidate.binding as unknown as JsonValue))throw new DomainError("BINDING_IMMUTABLE");}
