import { existsSync, rmSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";

export interface RetentionIntent {intentId:string;workspaceId:string;digest:string;state:"pending"|"deleted"}
function artifactPath(root:string,digest:string):string{if(!/^[a-f0-9]{64}$/.test(digest))throw new Error("invalid retention digest");return join(root,"objects",digest.slice(0,2),digest.slice(2));}
export function planRetention(db:DatabaseSync,workspaceId:string,digest:string,intentId:string=randomUUID()):RetentionIntent{
  db.exec("BEGIN IMMEDIATE");try{const artifact=db.prepare("SELECT 1 FROM artifacts WHERE digest=?").get(digest);if(!artifact)throw new Error("retention rejects unknown/dangling artifact");const refs=(db.prepare("SELECT count(*) AS count FROM artifact_refs WHERE digest=?").get(digest) as {count:number}).count;const pins=(db.prepare("SELECT count(*) AS count FROM artifact_pins WHERE digest=?").get(digest) as {count:number}).count;if(refs||pins)throw new Error("retention artifact is still referenced");db.prepare("INSERT INTO retention_intents(intent_id,workspace_id,digest,state,created_at) VALUES(?,?,?,'pending',?) ON CONFLICT(workspace_id,digest) DO NOTHING").run(intentId,workspaceId,digest,new Date().toISOString());const row=db.prepare("SELECT intent_id,workspace_id,digest,state FROM retention_intents WHERE workspace_id=? AND digest=?").get(workspaceId,digest) as {intent_id:string;workspace_id:string;digest:string;state:"pending"|"deleted"};db.exec("COMMIT");return{intentId:row.intent_id,workspaceId:row.workspace_id,digest:row.digest,state:row.state};}catch(error){if(db.isTransaction)db.exec("ROLLBACK");throw error;}}
export function resumeRetention(db:DatabaseSync,artifactRoot:string):number{
  const pending=db.prepare("SELECT intent_id,workspace_id,digest FROM retention_intents WHERE state='pending' ORDER BY created_at,intent_id").all() as {intent_id:string;workspace_id:string;digest:string}[];let completed=0;
  for(const intent of pending){const refs=(db.prepare("SELECT (SELECT count(*) FROM artifact_refs WHERE digest=?)+(SELECT count(*) FROM artifact_pins WHERE digest=?) AS count").get(intent.digest,intent.digest) as {count:number}).count;if(refs)throw new Error(`retention reference reappeared: ${intent.digest}`);const path=artifactPath(artifactRoot,intent.digest);if(existsSync(path))rmSync(path);db.exec("BEGIN IMMEDIATE");try{db.prepare("DELETE FROM artifacts WHERE digest=?").run(intent.digest);db.prepare("INSERT INTO artifact_tombstones(digest,workspace_id,deleted_at,intent_id) VALUES(?,?,?,?)").run(intent.digest,intent.workspace_id,new Date().toISOString(),intent.intent_id);db.prepare("UPDATE retention_intents SET state='deleted',completed_at=? WHERE intent_id=?").run(new Date().toISOString(),intent.intent_id);db.exec("COMMIT");completed++;}catch(error){if(db.isTransaction)db.exec("ROLLBACK");throw error;}}
  return completed;
}
