import { access, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { ROOT, canonical, inventory, readJson, sha256 } from "./lib.mjs";
const required = [".github/workflows/release.yml", ".github/workflows/release-stage.yml", ".github/workflows/live-gates.yml", "docs/release-process.md", "docs/trust/root-ceremony-v1.schema.json", ".acceptance/build-1/release-manifest.json", ".acceptance/build-2/release-manifest.json", ".acceptance/C22-claude-live-receipt.json", ".acceptance/C22-codex-live-receipt.json"];
for (const path of required) await access(resolve(ROOT, path));
const first = (await inventory(resolve(ROOT, ".acceptance/build-1"))).filter((item) => !item.path.endsWith(".sig")); const second = (await inventory(resolve(ROOT, ".acceptance/build-2"))).filter((item) => !item.path.endsWith(".sig"));
if (canonical(first) !== canonical(second)) throw new Error("DRY_RUN_BUILD_MISMATCH");
const claude = await readJson(resolve(ROOT, ".acceptance/C22-claude-live-receipt.json")); const codex = await readJson(resolve(ROOT, ".acceptance/C22-codex-live-receipt.json"));
if (claude.candidate.head !== codex.candidate.head || claude.candidate.tree !== codex.candidate.tree) throw new Error("LIVE_RECEIPT_CANDIDATE_MISMATCH");
const workflow = await readFile(resolve(ROOT, ".github/workflows/release.yml"), "utf8"); if (!workflow.includes("environment: release") || !workflow.includes("id-token: write") || !workflow.includes("refs/heads/main")) throw new Error("RELEASE_WORKFLOW_TRUST_CONTROLS_MISSING");
process.stdout.write(`${canonical({ schema: "horseness.release-dry-run.v1", candidate: claude.candidate, inventoryDigest: sha256(canonical(first)), externalEffects: 0 })}\n`);
