import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createWorkspaceGenesis, domainDigest, NO_POLICY_DIGEST, type JsonValue } from "@horseness/domain";
import { createOrLoadAuthorityCredential, rebindAuthorityCredential, SQLiteAuthority, StoreConflictError } from "../src/index.js";

function setup(){const root=mkdtempSync(join(tmpdir(),"authority-state-")),database=join(root,"authority.sqlite"),artifacts=join(root,"artifacts"),workspaceId="workspace-1";return{root,database,artifacts,workspaceId};}
function bootstrap(authority:SQLiteAuthority,workspaceId:string){const genesis=createWorkspaceGenesis({workspaceId,authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"consumed",activePolicyDigest:NO_POLICY_DIGEST,commandId:"bootstrap"});const state={schemaVersion:"1",value:"initial"} as const;return authority.bootstrapWorkspaceAuthorityAtomic({commandId:"bootstrap",workspace:{streamKind:"workspace",workspaceId,streamId:workspaceId,expectedSequence:0,expectedEnvelopeHash:null,events:[genesis.event]},authorityState:{schemaVersion:"1",workspaceId,stateKind:"test",revision:1,stateDigest:domainDigest("horseness.workspace-authority-state.v1",state),state}});}

test("workspace genesis and authority state commit atomically and reopen authenticated",()=>{const paths=setup();const credential=createOrLoadAuthorityCredential(paths.database,paths.artifacts,paths.workspaceId);const authority=SQLiteAuthority.open(paths.database,paths.artifacts);bootstrap(authority,paths.workspaceId);authority.close();const opened=SQLiteAuthority.openAuthenticatedWorkspace(paths.database,paths.artifacts,{workspaceId:paths.workspaceId,sessionId:"session",credential});assert.equal(opened.authority.authenticatedAuthorityState(paths.workspaceId,"test").revision,1);opened.authority.close();});

test("authority state compare-and-swap rejects stale writers",()=>{const paths=setup();const credential=createOrLoadAuthorityCredential(paths.database,paths.artifacts,paths.workspaceId);const authority=SQLiteAuthority.open(paths.database,paths.artifacts);bootstrap(authority,paths.workspaceId);authority.close();const opened=SQLiteAuthority.openAuthenticatedWorkspace(paths.database,paths.artifacts,{workspaceId:paths.workspaceId,sessionId:"session",credential}).authority;const current=opened.authenticatedAuthorityState(paths.workspaceId,"test");opened.compareAndSwapAuthorityState({commandId:"update",workspaceId:paths.workspaceId,stateKind:"test",expectedRevision:current.revision,expectedStateDigest:current.stateDigest,nextState:{schemaVersion:"1",value:"next"} as JsonValue});assert.throws(()=>opened.compareAndSwapAuthorityState({commandId:"stale",workspaceId:paths.workspaceId,stateKind:"test",expectedRevision:current.revision,expectedStateDigest:current.stateDigest,nextState:{schemaVersion:"1",value:"wrong"}}),StoreConflictError);opened.close();});

test("credential rebind recovers immutable workspace identity",()=>{const paths=setup();createOrLoadAuthorityCredential(paths.database,paths.artifacts,paths.workspaceId);const authority=SQLiteAuthority.open(paths.database,paths.artifacts);bootstrap(authority,paths.workspaceId);authority.close();const rebound=rebindAuthorityCredential(paths.database,paths.artifacts);assert.equal(rebound.workspaceId,paths.workspaceId);assert.notEqual(rebound.workspaceId,paths.root);});
