import assert from "node:assert/strict";
import { existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createWorkspaceGenesis, NO_POLICY_DIGEST } from "@horseness/domain";
import { CrashInjectedError, SQLiteAuthority, type CrashPoint } from "../src/index.js";

const artifactPoints:CrashPoint[]=["artifact.mkdir.before","artifact.mkdir.after","artifact.open.before","artifact.open.after","artifact.write.before","artifact.write.after","artifact.file-fsync.before","artifact.file-fsync.after","artifact.close.before","artifact.close.after","artifact.rename.before","artifact.rename.after","artifact.dir-fsync.before","artifact.dir-fsync.after","artifact.sql-reference.before","artifact.sql-reference.after"];
const transactionPoints:CrashPoint[]=["transaction.begin.before","transaction.begin.after","transaction.write.before","transaction.write.after","transaction.commit.before","transaction.commit.after"];

for(const point of artifactPoints)test(`artifact recovery at ${point}`,()=>{const root=mkdtempSync(join(tmpdir(),"horseness-crash-"));let armed=false;try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"),(seen)=>{if(armed&&seen===point)throw new CrashInjectedError(point);});armed=true;assert.throws(()=>store.artifacts.publishAndRegister("durable bytes"),CrashInjectedError);store.close();const recovered=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const rows=recovered.db.prepare("SELECT digest FROM artifacts").all() as {digest:string}[];for(const row of rows)assert.equal(recovered.artifacts.readReferenced(row.digest).toString(),"durable bytes");const staged=join(root,"artifacts","stage");assert.equal(existsSync(staged),true);recovered.close();}finally{rmSync(root,{recursive:true,force:true});}});

for(const point of transactionPoints)test(`transaction recovery at ${point}`,()=>{const root=mkdtempSync(join(tmpdir(),"horseness-tx-"));let armed=false;try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"),(seen)=>{if(armed&&seen===point)throw new CrashInjectedError(point);});const genesis=createWorkspaceGenesis({workspaceId:"ws",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:NO_POLICY_DIGEST,commandId:"genesis"});const request={commandId:"command",workspace:{streamKind:"workspace" as const,workspaceId:"ws",streamId:"ws",expectedSequence:0,expectedEnvelopeHash:null,events:[genesis.event]}};armed=true;assert.throws(()=>store.appendAtomic(request),CrashInjectedError);store.close();const recovered=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const count=(recovered.db.prepare("SELECT count(*) AS count FROM events").get() as {count:number}).count;assert(count===0||count===1);if(count===1)assert.equal(recovered.appendAtomic(request).deduplicated,true);else assert.equal(recovered.appendAtomic(request).workspaceHead?.sequence,1);recovered.close();}finally{rmSync(root,{recursive:true,force:true});}});

for(const rollbackPoint of ["transaction.rollback.before","transaction.rollback.after"] as const)test(`transaction recovery at ${rollbackPoint}`,()=>{const root=mkdtempSync(join(tmpdir(),"horseness-rollback-"));let armed=false;try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"),(point)=>{if(!armed)return;if(point==="transaction.write.after")throw new Error("force rollback");if(point===rollbackPoint)throw new CrashInjectedError(point);});const event=createWorkspaceGenesis({workspaceId:"ws",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:NO_POLICY_DIGEST,commandId:"genesis"}).event;armed=true;assert.throws(()=>store.appendAtomic({commandId:"rollback",workspace:{streamKind:"workspace",workspaceId:"ws",streamId:"ws",expectedSequence:0,expectedEnvelopeHash:null,events:[event]}}));store.close();const recovered=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));assert.equal((recovered.db.prepare("SELECT count(*) AS count FROM events").get() as {count:number}).count,0);recovered.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("dual-stream failure rolls back both streams",()=>{const root=mkdtempSync(join(tmpdir(),"horseness-dual-"));let writes=0;try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"),(point)=>{if(point==="transaction.write.after"&&++writes===1)throw new CrashInjectedError(point);});const event=createWorkspaceGenesis({workspaceId:"ws",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:NO_POLICY_DIGEST,commandId:"genesis"}).event;assert.throws(()=>store.appendAtomic({commandId:"bad",workspace:{streamKind:"workspace",workspaceId:"ws",streamId:"ws",expectedSequence:0,expectedEnvelopeHash:null,events:[event]}}));assert.equal((store.db.prepare("SELECT count(*) AS count FROM events").get() as {count:number}).count,0);store.close();}finally{rmSync(root,{recursive:true,force:true});}});
