import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createRunGenesis, createWorkspaceGenesis, NO_POLICY_DIGEST } from "@horseness/domain";
import { ArtifactIntegrityError, SQLiteAuthority, StoreConflictError } from "../src/index.js";

const temporary=()=>mkdtempSync(join(tmpdir(),"horseness-store-"));

test("migration 0001 is idempotent and creates its complete authority ledger",()=>{const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));assert.deepEqual(store.migrationVersions(),[1]);store.close();const reopened=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));assert.deepEqual(reopened.migrationVersions(),[1]);const tables=(reopened.db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all() as {name:string}[]).map(r=>r.name);for(const table of ["artifact_pins","artifact_refs","artifacts","command_dedup","events","projection_metadata","schema_migrations","snapshots","streams"])assert(tables.includes(table));reopened.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("workspace and run appends are atomic, CAS protected, deduplicated, and replay raw genesis",()=>{const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const ws=createWorkspaceGenesis({workspaceId:"ws",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:NO_POLICY_DIGEST,commandId:"workspace-command"});const run=createRunGenesis({observationCursor:{...ws.resultCursor,kind:"absent-run-genesis",runId:"run",expectedRunHead:"absent"},initialDocument:{items:[]},principalId:"authority",commandId:"run-command"});const request={commandId:"atomic-command",workspace:{streamKind:"workspace" as const,workspaceId:"ws",streamId:"ws",expectedSequence:0,expectedEnvelopeHash:null,events:[ws.event]},run:{streamKind:"run" as const,workspaceId:"ws",streamId:"run",expectedSequence:0,expectedEnvelopeHash:null,events:[run.event]}};const result=store.appendAtomic(request);assert.equal(result.workspaceHead?.sequence,1);assert.equal(store.appendAtomic(request).deduplicated,true);assert.equal(store.replay("workspace","ws")[0]?.envelopeHash,ws.event.envelopeHash);assert.equal(JSON.parse(store.replayRaw("run","run")[0]??"null").envelopeHash,run.event.envelopeHash);assert.throws(()=>store.appendAtomic({...request,commandId:"other"}),StoreConflictError);store.putSnapshot({streamKind:"run",streamId:"run",sequence:1,envelopeHash:run.event.envelopeHash,projectionName:"canonical",projectionVersion:"1",state:{items:[]}});assert.deepEqual(store.latestSnapshot("run","run","canonical","1")?.state,{items:[]});store.setProjectionMetadata("canonical","1","run","run",1,run.event.envelopeHash);store.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("artifacts publish before references, verify reads, pin/reference and collect orphans",()=>{const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const kept=store.artifacts.publishAndRegister("kept","text/plain");const orphan=store.artifacts.publishAndRegister("orphan");store.artifacts.addReference("event","one",kept.digest);store.artifacts.pin("release",kept.digest);assert.equal(store.artifacts.readReferenced(kept.digest).toString(),"kept");assert.deepEqual(store.artifacts.collectOrphans().removedDigests,[orphan.digest]);store.artifacts.removeReference("event","one",kept.digest);store.artifacts.unpin("release",kept.digest);assert.deepEqual(store.artifacts.collectOrphans().removedDigests,[kept.digest]);const corrupt=store.artifacts.publishAndRegister("corrupt");const path=join(root,"artifacts",corrupt.relativePath);writeFileSync(path,"tampered");assert.throws(()=>store.artifacts.readReferenced(corrupt.digest),ArtifactIntegrityError);rmSync(path);assert.throws(()=>store.artifacts.readReferenced(corrupt.digest),ArtifactIntegrityError);assert.equal(readFileSync(join(root,"db.sqlite")).length>0,true);store.close();}finally{rmSync(root,{recursive:true,force:true});}});
