import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import { createRunGenesis, createWorkspaceGenesis, NO_POLICY_DIGEST, sealEventEnvelope, type HashedEventEnvelopeV1, type PolicyReferenceChangedV1, type ProposalSubmittedV1 } from "@horseness/domain";
import { SQLiteAuthority, StoreConflictError, StoreIntegrityError } from "../src/index.js";

const temporary=()=>mkdtempSync(join(tmpdir(),"horseness-store-"));
type SQLiteRow = Record<string, unknown>;

function isSQLiteRow(value: unknown): value is SQLiteRow {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function rowValue(row: unknown, key: "journal_mode"): string;
function rowValue(row: unknown, key: "count"): number;
function rowValue(row: unknown, key: "journal_mode" | "count"): string | number {
  assert(isSQLiteRow(row), "node:sqlite must return a row record");
  const value = row[key];
  if (key === "journal_mode") {
    assert(typeof value === "string", "journal_mode must be a string");
    return value;
  }
  assert(typeof value === "number", "count must be a number");
  return value;
}

function genesis(workspaceId:string,runId="run",commandId="atomic-command") {
  const ws=createWorkspaceGenesis({workspaceId,authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:NO_POLICY_DIGEST,commandId:`${commandId}-workspace`});
  const observationCursor={...ws.resultCursor,kind:"absent-run-genesis" as const,runId,expectedRunHead:"absent" as const};
  const run=createRunGenesis({observationCursor,initialDocument:{items:[]},principalId:"authority",commandId:`${commandId}-run`});
  return {
    workspace:{commandId:`${commandId}-workspace`,workspace:{streamKind:"workspace" as const,workspaceId,streamId:workspaceId,expectedSequence:0,expectedEnvelopeHash:null,events:[ws.event]}},
    run:{commandId,runGenesis:{observationCursor,event:run.event}},
  };
}

function appendGenesis(store:SQLiteAuthority,workspaceId:string,runId="run",commandId="atomic-command") {
  const requests=genesis(workspaceId,runId,commandId);
  const workspaceResult=store.appendAtomic(requests.workspace);
  const runResult=store.appendAtomic(requests.run);
  return {workspaceHead:workspaceResult.workspaceHead,runHead:runResult.runHead};
}

function workspaceEvent(workspaceId:string,sequence:number,priorEnvelopeHash:string,commandId:string):HashedEventEnvelopeV1<PolicyReferenceChangedV1>{
  const payload:PolicyReferenceChangedV1={eventType:"PolicyReferenceChangedV1",workspaceId,activePolicyDigest:`policy-${sequence}`};
  return sealEventEnvelope({schemaVersion:"1",streamKind:"workspace",workspaceId,streamId:workspaceId,sequence,eventId:`${commandId}:${sequence}`,eventType:payload.eventType,principalId:"authority",causationId:commandId,correlationId:commandId,idempotencyKey:`${commandId}:${sequence}`,priorEnvelopeHash,payload});
}

function runEvent(workspaceId:string,runId:string,sequence:number,priorEnvelopeHash:string,commandId:string):HashedEventEnvelopeV1<ProposalSubmittedV1>{
  const payload:ProposalSubmittedV1={eventType:"ProposalSubmittedV1",workspaceId,runId,proposalId:`proposal-${sequence}`,proposalDigest:`digest-${sequence}`};
  return sealEventEnvelope({schemaVersion:"1",streamKind:"run",workspaceId,streamId:runId,sequence,eventId:`${commandId}:${sequence}`,eventType:payload.eventType,principalId:"authority",causationId:commandId,correlationId:commandId,idempotencyKey:`${commandId}:${sequence}`,priorEnvelopeHash,payload});
}

function corrupt<T>(event:HashedEventEnvelopeV1<T>,change:(copy:HashedEventEnvelopeV1<T>)=>void):HashedEventEnvelopeV1<T>{const copy=structuredClone(event);change(copy);return copy;}
function reseal<T>(event:HashedEventEnvelopeV1<T>):HashedEventEnvelopeV1<T>{const {payloadHash: _payloadHash,...envelope}=event.envelope;return sealEventEnvelope(envelope);}

test("migration 0001 is transactional, idempotent, and creates its complete authority ledger",()=>{const root=temporary();try{const path=join(root,"db.sqlite");const store=new SQLiteAuthority(path,join(root,"artifacts"));assert.deepEqual(store.migrationVersions(),[1]);store.close();const reopened=new SQLiteAuthority(path,join(root,"artifacts"));assert.deepEqual(reopened.migrationVersions(),[1]);const tables=(reopened.db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all() as {name:string}[]).map(r=>r.name);for(const table of ["artifact_pins","artifact_refs","artifacts","authority_consumption","command_dedup","events","projection_metadata","schema_migrations","snapshots","streams"])assert(tables.includes(table));const streamPk=reopened.db.prepare("PRAGMA table_info(streams)").all() as {name:string;pk:number}[];assert.deepEqual(streamPk.filter(column=>column.pk>0).sort((a,b)=>a.pk-b.pk).map(column=>column.name),["workspace_id","stream_kind","stream_id"]);const dedupPk=reopened.db.prepare("PRAGMA table_info(command_dedup)").all() as {name:string;pk:number}[];assert.deepEqual(dedupPk.filter(column=>column.pk>0).sort((a,b)=>a.pk-b.pk).map(column=>column.name),["workspace_id","scope_kind","scope_id","command_id"]);reopened.close();const failedPath=join(root,"failed.sqlite");const failed=new DatabaseSync(failedPath);failed.exec("CREATE TABLE streams(unrelated TEXT)");assert.throws(()=>new SQLiteAuthority(failedPath,join(root,"failed-artifacts")));assert.equal(failed.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='schema_migrations'").get(),undefined);assert.equal(failed.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='artifacts'").get(),undefined);failed.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("unsupported newer schema is rejected before mutable PRAGMAs",()=>{const root=temporary();try{const path=join(root,"future.sqlite");const db=new DatabaseSync(path);db.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL); INSERT INTO schema_migrations VALUES(2,'future','now')");assert.equal(rowValue(db.prepare("PRAGMA journal_mode").get(),"journal_mode"),"delete");db.close();assert.throws(()=>new SQLiteAuthority(path,join(root,"artifacts")),/unsupported newer schema version 2/);const inspect=new DatabaseSync(path);assert.equal(rowValue(inspect.prepare("PRAGMA journal_mode").get(),"journal_mode"),"delete");assert.equal(rowValue(inspect.prepare("SELECT count(*) AS count FROM sqlite_master WHERE type='table'").get(),"count"),1);inspect.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("deduplication is workspace-and-run scoped and conflicting retries reject",()=>{const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const first=genesis("ws-a","same-run","same-command");store.appendAtomic(first.workspace);const original=store.appendAtomic(first.run);assert.equal(original.deduplicated,false);assert.deepEqual(store.appendAtomic(first.run),{...original,deduplicated:true});assert.throws(()=>store.appendAtomic({...first.run,runGenesis:{...first.run.runGenesis,observationCursor:{...first.run.runGenesis.observationCursor,workspaceSequence:2}}}),StoreConflictError);const next=genesis("ws-a","other-run","other-event").run;const otherRun={...next,commandId:"same-command",runGenesis:{...next.runGenesis,observationCursor:{...first.run.runGenesis.observationCursor,runId:"other-run"}}};assert.equal(store.appendAtomic(otherRun).deduplicated,false);const second=genesis("ws-b","same-run","same-command");store.appendAtomic(second.workspace);assert.equal(store.appendAtomic(second.run).deduplicated,false);assert.equal(store.replay("ws-a","run","same-run").length,1);assert.equal(store.replay("ws-a","run","other-run").length,1);assert.equal(store.replay("ws-b","run","same-run").length,1);assert.notEqual(store.replay("ws-a","run","same-run")[0]?.envelope.workspaceId,store.replay("ws-b","run","same-run")[0]?.envelope.workspaceId);store.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("workspace post-genesis append slices authenticate their anchor, continuity, hashes, and identity",()=>{const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const genesisResult=appendGenesis(store,"ws");const head=genesisResult.workspaceHead;assert(head);const one=workspaceEvent("ws",2,head.envelopeHash,"workspace-one");assert.deepEqual(store.appendAtomic({commandId:"workspace-one",workspace:{streamKind:"workspace",workspaceId:"ws",streamId:"ws",expectedSequence:1,expectedEnvelopeHash:head.envelopeHash,events:[one]}}).workspaceHead,{sequence:2,envelopeHash:one.envelopeHash});const three=workspaceEvent("ws",3,one.envelopeHash,"workspace-many");const four=workspaceEvent("ws",4,three.envelopeHash,"workspace-many");assert.deepEqual(store.appendAtomic({commandId:"workspace-many",workspace:{streamKind:"workspace",workspaceId:"ws",streamId:"ws",expectedSequence:2,expectedEnvelopeHash:one.envelopeHash,events:[three,four]}}).workspaceHead,{sequence:4,envelopeHash:four.envelopeHash});assert.equal(store.replay("ws","workspace","ws").length,4);const valid=workspaceEvent("ws",5,four.envelopeHash,"workspace-invalid");const wrongIdentity=corrupt(valid,event=>{event.envelope.payload.workspaceId="other";});const attempts=[corrupt(valid,event=>{event.envelope.priorEnvelopeHash="wrong";}),corrupt(valid,event=>{event.envelope.sequence=6;}),corrupt(valid,event=>{event.envelopeHash="wrong";}),reseal(wrongIdentity)];for(const [index,event] of attempts.entries())assert.throws(()=>store.appendAtomic({commandId:`workspace-invalid-${index}`,workspace:{streamKind:"workspace",workspaceId:"ws",streamId:"ws",expectedSequence:4,expectedEnvelopeHash:four.envelopeHash,events:[event]}}),StoreIntegrityError);assert.equal(store.replay("ws","workspace","ws").length,4);store.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("run post-genesis append slices authenticate their anchor, continuity, hashes, and identity",()=>{const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const genesisResult=appendGenesis(store,"ws");const head=genesisResult.runHead;assert(head);const one=runEvent("ws","run",2,head.envelopeHash,"run-one");assert.deepEqual(store.appendAtomic({commandId:"run-one",run:{streamKind:"run",workspaceId:"ws",streamId:"run",expectedSequence:1,expectedEnvelopeHash:head.envelopeHash,events:[one]}}).runHead,{sequence:2,envelopeHash:one.envelopeHash});const three=runEvent("ws","run",3,one.envelopeHash,"run-many");const four=runEvent("ws","run",4,three.envelopeHash,"run-many");assert.deepEqual(store.appendAtomic({commandId:"run-many",run:{streamKind:"run",workspaceId:"ws",streamId:"run",expectedSequence:2,expectedEnvelopeHash:one.envelopeHash,events:[three,four]}}).runHead,{sequence:4,envelopeHash:four.envelopeHash});assert.equal(store.replay("ws","run","run").length,4);const valid=runEvent("ws","run",5,four.envelopeHash,"run-invalid");const wrongIdentity=corrupt(valid,event=>{event.envelope.payload.runId="other";});const attempts=[corrupt(valid,event=>{event.envelope.priorEnvelopeHash="wrong";}),corrupt(valid,event=>{event.envelope.sequence=6;}),corrupt(valid,event=>{event.envelope.payloadHash="wrong";}),reseal(wrongIdentity)];for(const [index,event] of attempts.entries())assert.throws(()=>store.appendAtomic({commandId:`run-invalid-${index}`,run:{streamKind:"run",workspaceId:"ws",streamId:"run",expectedSequence:4,expectedEnvelopeHash:four.envelopeHash,events:[event]}}),StoreIntegrityError);assert.equal(store.replay("ws","run","run").length,4);store.close();}finally{rmSync(root,{recursive:true,force:true});}});
test("run genesis atomically authenticates an existing workspace observation and absent run authority state",()=>{const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const request=genesis("ws","run","create-run");assert.throws(()=>store.appendAtomic(request.run),/existing workspace/);store.appendAtomic(request.workspace);const ordinary={commandId:"ordinary-genesis",run:{streamKind:"run" as const,workspaceId:"ws",streamId:"run",expectedSequence:0,expectedEnvelopeHash:null,events:[request.run.runGenesis.event]}};assert.throws(()=>store.appendAtomic(ordinary),/explicit runGenesis/);for(const observationCursor of [{...request.run.runGenesis.observationCursor,workspaceSequence:2},{...request.run.runGenesis.observationCursor,workspaceEnvelopeHash:"substituted"},{...request.run.runGenesis.observationCursor,workspaceContextEpoch:1}])assert.throws(()=>store.appendAtomic({commandId:`stale-${String(observationCursor.workspaceSequence)}-${observationCursor.workspaceEnvelopeHash}-${String(observationCursor.workspaceContextEpoch)}`,runGenesis:{...request.run.runGenesis,observationCursor}}),StoreConflictError);assert.equal(store.replay("ws","run","run").length,0);store.db.exec("PRAGMA foreign_keys=OFF");store.db.prepare("INSERT INTO projection_metadata(projection_name,projection_version,workspace_id,stream_kind,stream_id,last_sequence,last_envelope_hash,updated_at) VALUES('poison','1','ws','run','run',0,NULL,'now')").run();store.db.exec("PRAGMA foreign_keys=ON");assert.throws(()=>store.appendAtomic({...request.run,commandId:"projection-state"}),/not absent/);store.db.prepare("DELETE FROM projection_metadata WHERE workspace_id='ws' AND stream_kind='run' AND stream_id='run'").run();store.db.exec("PRAGMA foreign_keys=OFF");store.db.prepare("INSERT INTO snapshots(workspace_id,stream_kind,stream_id,sequence,envelope_hash,projection_name,projection_version,state_json,created_at) VALUES('ws','run','run',0,'absent','poison','1','{}','now')").run();store.db.exec("PRAGMA foreign_keys=ON");assert.throws(()=>store.appendAtomic({...request.run,commandId:"snapshot-state"}),/not absent/);store.db.prepare("DELETE FROM snapshots WHERE workspace_id='ws' AND stream_kind='run' AND stream_id='run'").run();const created=store.appendAtomic(request.run);assert.deepEqual(created.runHead,{sequence:1,envelopeHash:request.run.runGenesis.event.envelopeHash});assert.equal(store.replay("ws","run","run")[0]?.envelope.eventType,"RunCreatedV1");const duplicate=genesis("ws","run","different-command").run;duplicate.runGenesis.observationCursor=request.run.runGenesis.observationCursor;assert.throws(()=>store.appendAtomic(duplicate),/not absent/);store.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("run genesis rejects orphan run-scoped dedup and authority consumption while workspace scope remains valid",()=>{for(const poison of ["dedup","authority"] as const){const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const request=genesis("ws","run",`create-${poison}`);store.appendAtomic(request.workspace);if(poison==="dedup")store.db.prepare("INSERT INTO command_dedup(workspace_id,scope_kind,scope_id,command_id,request_digest,result_json,created_at) VALUES(?,?,?,?,?,?,?)").run("ws","run","run","orphan","digest","{}","now");else assert.equal(store.recordAuthorityConsumption({workspaceId:"ws",runId:"run",principalId:"authority",authorityKey:"grant",commandId:"consume"}),true);assert.throws(()=>store.appendAtomic(request.run),/not absent/);assert.equal(store.replay("ws","run","run").length,0);store.close();}finally{rmSync(root,{recursive:true,force:true});}}const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));const request=genesis("ws","run","create-normal");const workspace=store.appendAtomic(request.workspace);assert.equal(store.appendAtomic(request.workspace).deduplicated,true);assert.equal(store.recordAuthorityConsumption({workspaceId:"ws",principalId:"authority",authorityKey:"bootstrap",commandId:"workspace-consume"}),true);assert.equal(store.recordAuthorityConsumption({workspaceId:"ws",principalId:"authority",authorityKey:"bootstrap",commandId:"workspace-consume"}),false);assert.throws(()=>store.recordAuthorityConsumption({workspaceId:"ws",principalId:"authority",authorityKey:"bootstrap",commandId:"different"}),StoreConflictError);const created=store.appendAtomic(request.run);assert.equal(created.deduplicated,false);assert.equal(store.appendAtomic(request.run).deduplicated,true);assert(workspace.workspaceHead);assert.equal(store.replay("ws","run","run").length,1);store.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("replay and raw partial replay authenticate JSON, sequence, prior hash, envelope hash, and stored head",()=>{const corruptions=[
  ["invalid JSON","UPDATE events SET envelope_json='{' WHERE workspace_id='ws' AND stream_kind='run'"],
  ["sequence","UPDATE events SET sequence=2 WHERE workspace_id='ws' AND stream_kind='run'"],
  ["prior hash","UPDATE events SET prior_envelope_hash='bad' WHERE workspace_id='ws' AND stream_kind='run'"],
  ["envelope hash","UPDATE events SET envelope_hash='bad' WHERE workspace_id='ws' AND stream_kind='run'"],
  ["stored head","UPDATE streams SET head_hash='bad' WHERE workspace_id='ws' AND stream_kind='run'"],
] as const;for(const [name,sql] of corruptions){const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));appendGenesis(store, "ws");store.db.exec("PRAGMA foreign_keys=OFF");store.db.exec(sql);assert.throws(()=>store.replay("ws","run","run"),StoreIntegrityError,name);assert.throws(()=>store.replayRaw("ws","run","run",2),StoreIntegrityError,`${name} raw partial`);store.close();}finally{rmSync(root,{recursive:true,force:true});}}});

test("snapshots cannot cross workspace identity",()=>{const root=temporary();try{const store=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));appendGenesis(store, "ws-a","same-run","a");appendGenesis(store, "ws-b","same-run","b");const event=store.replay("ws-a","run","same-run")[0];assert(event);store.putSnapshot({workspaceId:"ws-a",streamKind:"run",streamId:"same-run",sequence:1,envelopeHash:event.envelopeHash,projectionName:"run",projectionVersion:"1",state:{workspace:"a"}});assert.equal(store.latestSnapshot("ws-b","run","same-run","run","1"),null);assert.deepEqual(store.latestSnapshot("ws-a","run","same-run","run","1")?.state,{workspace:"a"});assert.throws(()=>store.putSnapshot({workspaceId:"ws-b",streamKind:"run",streamId:"same-run",sequence:1,envelopeHash:event.envelopeHash,projectionName:"run",projectionVersion:"1",state:null}),StoreIntegrityError);store.close();}finally{rmSync(root,{recursive:true,force:true});}});
