import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createRunGenesis, createWorkspaceGenesis, domainDigest, sealForkPin, type CompositeCursorV1, type ContextVersionV1 } from "@horseness/domain";
import { SQLiteAuthority, createOrLoadAuthorityCredential } from "@horseness/store-sqlite";
import { authenticateContextSnapshot, contextSourceDigest, reconstructPinnedContext, type ContextSourceInputV1 } from "../../src/context/index.js";

function fixture() {
  const root=mkdtempSync(join(tmpdir(),"horseness-context-")),database=join(root,"db.sqlite"),artifactRoot=join(root,"artifacts"),bootstrap=SQLiteAuthority.open(database,artifactRoot);
  const workspace=createWorkspaceGenesis({workspaceId:"w",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:"policy",commandId:"workspace"});
  bootstrap.appendAtomic({commandId:"workspace",workspace:{streamKind:"workspace",workspaceId:"w",streamId:"w",expectedSequence:0,expectedEnvelopeHash:null,events:[workspace.event]}});
  const absent={schemaVersion:"1" as const,kind:"absent-run-genesis" as const,workspaceId:"w",workspaceSequence:1,workspaceEnvelopeHash:workspace.event.envelopeHash,workspaceContextEpoch:0,runId:"r",expectedRunHead:"absent" as const};
  const run=createRunGenesis({observationCursor:absent,initialDocument:{objective:"ship"},principalId:"authority",commandId:"run"}); bootstrap.appendAtomic({commandId:"run",runGenesis:{observationCursor:absent,event:run.event}}); bootstrap.close();
  const opened=SQLiteAuthority.openAuthenticatedWorkspace(database,artifactRoot,{workspaceId:"w",sessionId:`context-${root}`,credential:createOrLoadAuthorityCredential(database,artifactRoot,"w")});
  const cursor=run.resultCursor,version:ContextVersionV1={schemaVersion:"1",kind:"composite",workspaceContextEpoch:0,runContextEpoch:0,observationCursor:cursor};
  const pin=sealForkPin({schemaVersion:"1",forkId:"fork",pinVersion:1,workspaceId:"w",runId:"r",parentForkPinDigest:null,refreshesForkPinDigest:null,canonicalRevision:0,canonicalStateHash:domainDigest("horseness.canonical-document.v1",{objective:"ship"}),canonicalizerVersion:"jcs-v1",hashVersion:"sha256-v1",sourceObservationCursor:cursor,sourceContextVersion:version,dependencyJoinSnapshotDigest:"join",deltaAuthorityScopeDigest:"scope",pinnedPolicyDigest:"policy",ancestry:[],createdByPrincipalId:"authority",createdByGrantDigest:"grant"});
  const artifactAuthority={readDurableReferenced:(digest:string,workspaceId:string)=>{const row=opened.authority.db.prepare("SELECT 1 FROM artifact_refs WHERE workspace_id=? AND digest=?").get(workspaceId,digest);if(!row)throw new Error("artifact is not durably referenced");return opened.authority.artifacts.readReferenced(digest);}};
  const snapshot=(sources:readonly ContextSourceInputV1[])=>authenticateContextSnapshot(opened.reader,{pin,canonicalState:{objective:"ship"},sources,artifacts:artifactAuthority});
  const request=(sources:readonly ContextSourceInputV1[],byteBudget=1000)=>({snapshot:snapshot(sources),attemptId:"attempt",generation:1,byteBudget,rendererVersion:"renderer-v1",authorizationObservationCursor:cursor,authorizationContextVersion:version,authorizationOverlay:{policyDigest:"policy",grantDigest:"grant",quotaDigest:"quota",result:"allowed" as const},providerIdempotencyKey:"provider-key",allowedProducerPrincipalId:"worker",allowedProducerGrantDigest:"worker-grant"});
  return {root,authority:opened.authority,cursor,version,pin,snapshot,request,close(){opened.authority.close();rmSync(root,{recursive:true,force:true});}};
}
const source=(sourceId:string,kind:ContextSourceInputV1["kind"],priority:number,text:string,overrides:Partial<ContextSourceInputV1>={}):ContextSourceInputV1=>({sourceId,kind,priority,bytes:text,digest:contextSourceDigest(text),activationEpoch:0,deactivationEpoch:null,visibleAtRunSequence:1,artifactDigest:null,...overrides});

test("golden reconstruction is byte deterministic with stable ordering, normalization, omissions and binding equivalence",()=>{const f=fixture();try{const inputs=[source("z","task",20,"task\n"),source("a","system",10,"e\u0301\n"),source("b","system",10,"B\n")];const first=reconstructPinnedContext(f.request(inputs,7));const second=reconstructPinnedContext(f.request([...inputs].reverse(),7));assert.equal(Buffer.from(first.bytes).toString(),"é\nB\n");assert.deepEqual(first,second);assert.deepEqual(first.manifest.core.sources.map(item=>item.kind),["system","system"]);assert.deepEqual(first.manifest.core.omissions,["budget:z"]);assert.equal(first.binding.contextManifestCoreDigest,first.manifest.contextManifestCoreDigest);assert.equal(first.manifest.attemptContextBindingDigest,domainDigest("horseness.attempt-context-binding.v1",first.binding as never));}finally{f.close();}});

test("activation replacement and deactivation epochs invalidate visibility exactly at the pin",()=>{const f=fixture();try{const old=source("config-v1","task",1,"old",{activationEpoch:0,deactivationEpoch:1}),replacement=source("config-v2","task",1,"new",{activationEpoch:1});assert.equal(Buffer.from(reconstructPinnedContext(f.request([old,replacement])).bytes).toString(),"old");const cursor={...f.cursor,runContextEpoch:1},version={...f.version,runContextEpoch:1,observationCursor:cursor} as ContextVersionV1,pin=sealForkPin({...f.pin.core,sourceObservationCursor:cursor,sourceContextVersion:version});assert.throws(()=>authenticateContextSnapshot({authenticatedView:()=>({cursor:f.cursor,workspaceEvents:[],runEvents:[]})} as never,{pin,canonicalState:{objective:"ship"},sources:[old,replacement],artifacts:{readDurableReferenced(){throw new Error("unused");}}}),/CONTEXT_AUTHORITY_CURSOR_SUBSTITUTED|CONTEXT_AUTHORITY_CURSOR_STALE/);}finally{f.close();}});

test("rejects unauthenticated, substituted pin cursor, canonical state and source bytes",()=>{const f=fixture();try{assert.throws(()=>reconstructPinnedContext({...f.request([]),snapshot:{...f.snapshot([])}}),/CONTEXT_AUTHORITY_UNAUTHENTICATED/);assert.throws(()=>authenticateContextSnapshot({authenticatedView:()=>({cursor:f.cursor,workspaceEvents:[],runEvents:[]})} as never,{pin:f.pin,canonicalState:{objective:"ship"},sources:[],artifacts:{readDurableReferenced(){throw new Error("unused");}}}),/CONTEXT_AUTHORITY_CURSOR_SUBSTITUTED/);assert.throws(()=>authenticateContextSnapshot({authenticatedView:()=>({cursor:f.cursor,workspaceEvents:[],runEvents:[]})} as never,{pin:f.pin,canonicalState:{objective:"changed"},sources:[],artifacts:{readDurableReferenced(){throw new Error("unused");}}}),/CONTEXT_AUTHORITY_CURSOR_SUBSTITUTED|CONTEXT_CANONICAL_STATE_SUBSTITUTED/);assert.throws(()=>reconstructPinnedContext(f.request([source("x","task",1,"changed",{digest:contextSourceDigest("original")})])),/CONTEXT_SOURCE_DIGEST_MISMATCH/);}finally{f.close();}});

test("only published, registered and durably referenced artifacts are visible; retry after crash is deterministic",()=>{const f=fixture();try{const record=f.authority.artifacts.publish("durable","text/plain"),input=source("artifact","evidence",1,"durable",{artifactDigest:record.digest});assert.throws(()=>reconstructPinnedContext(f.request([input])),/not durably referenced/);f.authority.artifacts.register(record);assert.throws(()=>reconstructPinnedContext(f.request([input])),/not durably referenced/);const owner=f.authority.replay("w","run","r")[0]!.envelope.eventId;f.authority.artifacts.addReference("w","event",owner,record.digest);const first=reconstructPinnedContext(f.request([input])),second=reconstructPinnedContext(f.request([input]));assert.deepEqual(first,second);assert.equal(Buffer.from(first.bytes).toString(),"durable");}finally{f.close();}});
