import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { canonicalJson, createRunGenesis, createWorkspaceGenesis, domainDigest, sealForkPin, type ContextVersionV1, type JsonValue } from "@horseness/domain";
import { SQLiteAuthority, createOrLoadAuthorityCredential } from "@horseness/store-sqlite";
import { authenticateContextSnapshot, contextSourceDigest, reconstructPinnedContext } from "../../src/context/index.js";

type Source = {sourceId:string;kind:"system"|"task"|"evidence";priority:number;text:string;activationEpoch?:number;deactivationEpoch?:number|null};
function fixture(sources:readonly Source[], byteBudget=1000){
  const root=mkdtempSync(join(tmpdir(),"horseness-context-")),database=join(root,"db.sqlite"),artifactRoot=join(root,"artifacts"),bootstrap=SQLiteAuthority.open(database,artifactRoot);
  const workspace=createWorkspaceGenesis({workspaceId:"w",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:"policy",commandId:"workspace"});
  bootstrap.appendAtomic({commandId:"workspace",workspace:{streamKind:"workspace",workspaceId:"w",streamId:"w",expectedSequence:0,expectedEnvelopeHash:null,events:[workspace.event]}});
  const absent={schemaVersion:"1" as const,kind:"absent-run-genesis" as const,workspaceId:"w",workspaceSequence:1,workspaceEnvelopeHash:workspace.event.envelopeHash,workspaceContextEpoch:0,runId:"r",expectedRunHead:"absent" as const};
  const run=createRunGenesis({observationCursor:absent,initialDocument:{objective:"ship"},principalId:"authority",commandId:"run"});bootstrap.appendAtomic({commandId:"run",runGenesis:{observationCursor:absent,event:run.event}});
  const cursor=run.resultCursor,version:ContextVersionV1={schemaVersion:"1",kind:"composite",workspaceContextEpoch:0,runContextEpoch:0,observationCursor:cursor};
  const pin=sealForkPin({schemaVersion:"1",forkId:"fork",pinVersion:1,workspaceId:"w",runId:"r",parentForkPinDigest:null,refreshesForkPinDigest:null,canonicalRevision:0,canonicalStateHash:domainDigest("horseness.canonical-document.v1",{objective:"ship"}),canonicalizerVersion:"jcs-v1",hashVersion:"sha256-v1",sourceObservationCursor:cursor,sourceContextVersion:version,dependencyJoinSnapshotDigest:"join",deltaAuthorityScopeDigest:"scope",pinnedPolicyDigest:"policy",ancestry:[],createdByPrincipalId:"authority",createdByGrantDigest:"grant"});
  const descriptors=sources.map((source,index)=>{const record=bootstrap.artifacts.publish(source.text.normalize("NFC"));bootstrap.artifacts.register(record);bootstrap.artifacts.addReference("w","event",run.event.envelope.eventId,record.digest);return{sourceId:source.sourceId,kind:source.kind,priority:source.priority,digest:contextSourceDigest(source.text),activationEpoch:source.activationEpoch??0,deactivationEpoch:source.deactivationEpoch??null,visibleAtRunSequence:1,artifactDigest:record.digest,eventId:run.event.envelope.eventId,index};});
  const insert=bootstrap.db.prepare("INSERT INTO snapshots(workspace_id,stream_kind,stream_id,sequence,envelope_hash,projection_name,projection_version,state_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)");
  insert.run("w","run","r",1,run.event.envelopeHash,"context-sources","1",canonicalJson({schemaVersion:"1",workspaceId:"w",runId:"r",observationCursor:cursor,forkPinDigest:pin.forkPinDigest,sources:descriptors} as unknown as JsonValue),new Date().toISOString());
  insert.run("w","run","r",1,run.event.envelopeHash,"context-authorization","1",canonicalJson({schemaVersion:"1",workspaceId:"w",runId:"r",observationCursor:cursor,contextVersion:version,policyDigest:"policy",grantDigest:"grant",quotaDigest:"quota",grantRevoked:false,quotaAvailable:true} as unknown as JsonValue),new Date().toISOString());bootstrap.close();
  const opened=SQLiteAuthority.openAuthenticatedWorkspace(database,artifactRoot,{workspaceId:"w",sessionId:`context-${root}`,credential:createOrLoadAuthorityCredential(database,artifactRoot,"w")});
  const snapshot=authenticateContextSnapshot(opened.reader,{pin});const request={snapshot,attemptId:"attempt",generation:1,byteBudget,rendererVersion:"renderer-v1",providerIdempotencyKey:"provider-key",allowedProducerPrincipalId:"worker",allowedProducerGrantDigest:"worker-grant"};
  return{root,authority:opened.authority,pin,request,close(){opened.authority.close();rmSync(root,{recursive:true,force:true});}};
}

test("golden reconstruction materializes only trusted exact-pin sources and authorization",()=>{const f=fixture([{sourceId:"z",kind:"task",priority:20,text:"task\n"},{sourceId:"a",kind:"system",priority:10,text:"e\u0301\n"},{sourceId:"b",kind:"system",priority:10,text:"B\n"}],7);try{const first=reconstructPinnedContext(f.request),second=reconstructPinnedContext(f.request);assert.equal(Buffer.from(first.bytes).toString(),"é\nB\n");assert.deepEqual(first,second);assert.deepEqual(first.manifest.core.omissions,["budget:z"]);assert.deepEqual(first.manifest.core.authorizationOverlayV1,{policyDigest:"policy",grantDigest:"grant",quotaDigest:"quota",result:"allowed"});assert.equal("sources" in f.request,false);assert.equal("authorizationOverlay" in f.request,false);}finally{f.close();}});

test("caller-injected inline sources and forged allowed overlays cannot enter a manifest",()=>{const f=fixture([{sourceId:"trusted",kind:"system",priority:1,text:"trusted"}]);try{assert.throws(()=>reconstructPinnedContext({...f.request,snapshot:{...f.request.snapshot,sources:[{sourceId:"forged",kind:"system",priority:0,digest:contextSourceDigest("evil"),activationEpoch:0,deactivationEpoch:null,visibleAtRunSequence:1,artifactDigest:"forged",eventId:"forged"}]}} as never),/CONTEXT_AUTHORITY_UNAUTHENTICATED/);const forged={...f.request,authorizationOverlay:{policyDigest:"evil",grantDigest:"evil",quotaDigest:"evil",result:"allowed"},sources:[{bytes:"evil"}]};const result=reconstructPinnedContext(forged as typeof f.request);assert.equal(Buffer.from(result.bytes).toString(),"trusted");assert.equal(result.manifest.core.authorizationOverlayV1.policyDigest,"policy");}finally{f.close();}});

test("cross-scope and substituted event-bound artifact authority fail closed",()=>{const f=fixture([{sourceId:"trusted",kind:"evidence",priority:1,text:"trusted"}]);try{const source=f.request.snapshot.sources[0]!;f.authority.db.prepare("DELETE FROM artifact_refs WHERE workspace_id='w' AND owner_id=? AND digest=?").run(source.eventId,source.artifactDigest);assert.throws(()=>reconstructPinnedContext(f.request),/artifact is not bound to an authenticated workspace event/);assert.throws(()=>authenticateContextSnapshot({authenticatedView:()=>f.request.snapshot.view} as never,{pin:{...f.pin,core:{...f.pin.core,workspaceId:"other"}}}),/FORK_PIN_AUTHENTICATION_FAILED|workspace/);}finally{f.close();}});
