import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { completionPredicateIdentity, createRunGenesis, createWorkspaceGenesis, sealEventEnvelope, type CompletionPredicateV1, type CompositeCursorV1 } from "@horseness/domain";
import { SQLiteAuthority, createOrLoadAuthorityCredential } from "@horseness/store-sqlite";
import { issueStoredAuthorityEvent, issueStoredTaskResolvedCapability, issueTaskAuthorityProjection, projectDurablePredicate as projectDurablePredicateFromPackageRoot } from "@horseness/orchestrator";
import { activateTask, addDependency, addTask, emptyTaskProjection, evaluateTaskJoin, projectDurablePredicate, resolveProjectedTask, type DurableAuthorityEventV1, type DurablePredicatePayloadV1, type StoredTaskResolvedCapabilityV1, type TaskAuthorityComponentSnapshotV1, type TaskAuthorityProjectionV1, type VerifiedAuthorityEventV1 } from "../../src/tasks/task-projection.js";

let baseCursor:CompositeCursorV1;
const predicate=(taskId:string):CompletionPredicateV1=>({kind:"canonical-change",proposalDigest:`proposal-${taskId}`,acceptedEventDigest:`event-${taskId}`,resultingRevision:1,resultingStateHash:`state-${taskId}`});
type ComponentValue=TaskAuthorityComponentSnapshotV1["value"];
const root=mkdtempSync(join(tmpdir(),"horseness-projection-model-")),databasePath=join(root,"authority.sqlite"),artifactRoot=join(root,"artifacts"),bootstrapStore=new SQLiteAuthority(databasePath,artifactRoot);
const workspace=createWorkspaceGenesis({workspaceId:"w",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:"policy",commandId:"workspace"});bootstrapStore.appendAtomic({commandId:"workspace",workspace:{streamKind:"workspace",workspaceId:"w",streamId:"w",expectedSequence:0,expectedEnvelopeHash:null,events:[workspace.event]}});
const absent={...workspace.resultCursor,kind:"absent-run-genesis" as const,runId:"r",expectedRunHead:"absent" as const},run=createRunGenesis({observationCursor:absent,initialDocument:{},principalId:"authority",commandId:"run"});bootstrapStore.appendAtomic({commandId:"run",runGenesis:{observationCursor:absent,event:run.event}});baseCursor=run.resultCursor;const headEvent=sealEventEnvelope({schemaVersion:"1",streamKind:"run",workspaceId:"w",streamId:"r",sequence:2,eventId:"head:2",eventType:"ProposalSubmittedV1",principalId:"authority",causationId:"head",correlationId:"run",idempotencyKey:"head",priorEnvelopeHash:run.event.envelopeHash,payload:{eventType:"ProposalSubmittedV1",workspaceId:"w",runId:"r",proposalId:"head",proposalDigest:"head"}});bootstrapStore.appendAtomic({commandId:"head",run:{streamKind:"run",workspaceId:"w",streamId:"r",expectedSequence:1,expectedEnvelopeHash:run.event.envelopeHash,events:[headEvent]}});bootstrapStore.close();const opened=SQLiteAuthority.openAuthenticatedWorkspace(databasePath,artifactRoot,{workspaceId:"w",sessionId:"projection-model",credential:createOrLoadAuthorityCredential(databasePath,artifactRoot,"w")}),store=opened.authority,reader=opened.reader;
test.after(()=>{store.close();rmSync(root,{recursive:true,force:true})});
const snapshot=(authorityStore:SQLiteAuthority,projectionName:string,state:unknown,envelopeHash=headEvent.envelopeHash):void=>{authorityStore.db.prepare("INSERT OR REPLACE INTO snapshots(workspace_id,stream_kind,stream_id,sequence,envelope_hash,projection_name,projection_version,state_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run("w","run","r",2,envelopeHash,projectionName,"1",JSON.stringify(state),"2026-08-12T00:00:00.000Z")};
const authority=(_proofEvent:VerifiedAuthorityEventV1,overrides:Partial<Record<ComponentValue["kind"],ComponentValue>>={}):TaskAuthorityProjectionV1=>{const values:ComponentValue[]=[overrides.contract??{kind:"contract",valid:true},overrides.policy??{kind:"policy",state:"allowed"},overrides["grant-revocation"]??{kind:"grant-revocation",grantState:"allowed",revocationState:"clear"},overrides.quota??{kind:"quota",state:"available"},overrides["attempt-outcome"]??{kind:"attempt-outcome",state:"none"}];for(const value of values)snapshot(store,`task-authority/${value.kind}`,{taskId:"dependent",...value});return issueTaskAuthorityProjection(reader,{workspaceId:"w",runId:"r",taskId:"dependent"})};
function rawEvent(payload:DurablePredicatePayloadV1,sequence:number,prior:string|null):DurableAuthorityEventV1 {
  const sealed=sealEventEnvelope({schemaVersion:"1",streamKind:"run",workspaceId:"w",streamId:"r",sequence,eventId:`event-${sequence}`,eventType:payload.eventType,principalId:"authority",causationId:"command",correlationId:"run",idempotencyKey:`key-${sequence}`,priorEnvelopeHash:prior,payload});
  return {envelope:sealed.envelope,envelopeHash:sealed.envelopeHash,resultCursor:{...baseCursor,runSequence:sequence,runEnvelopeHash:sealed.envelopeHash,runContextEpoch:sequence-1}};
}
function event(payload:DurablePredicatePayloadV1,_sequence:number,_prior:string|null):VerifiedAuthorityEventV1 {const candidate=rawEvent(payload,2,run.event.envelopeHash);candidate.resultCursor={...reader.authenticatedView("w","r").cursor};snapshot(store,`durable-authority-event/${payload.eventType}/2`,candidate);return issueStoredAuthorityEvent(reader,{workspaceId:"w",runId:"r",sequence:2,eventType:payload.eventType})}
function resolutionCapability(resolution:"succeeded"|"failed"|"cancelled",winningGeneration:number|null):StoredTaskResolvedCapabilityV1 {const path=mkdtempSync(join(tmpdir(),"horseness-task-resolution-")),workspaceId=`w-${path.slice(-6)}`,runId="r",database=join(path,"authority.sqlite"),artifacts=join(path,"artifacts"),authorityStore=new SQLiteAuthority(database,artifacts);let opened:SQLiteAuthority|undefined;try{const ws=createWorkspaceGenesis({workspaceId,authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:"policy",commandId:"workspace"});authorityStore.appendAtomic({commandId:"workspace",workspace:{streamKind:"workspace",workspaceId,streamId:workspaceId,expectedSequence:0,expectedEnvelopeHash:null,events:[ws.event]}});const absentRun={...ws.resultCursor,kind:"absent-run-genesis" as const,runId,expectedRunHead:"absent" as const},created=createRunGenesis({observationCursor:absentRun,initialDocument:{},principalId:"authority",commandId:"run"});authorityStore.appendAtomic({commandId:"run",runGenesis:{observationCursor:absentRun,event:created.event}});const evaluationClock={schemaVersion:"1" as const,authorityTime:"2026-08-12T00:00:00Z",observationCursor:created.resultCursor},payload={eventType:"TaskResolvedV1" as const,workspaceId,runId,taskId:"source",resolution,evaluationClock};const resolved=sealEventEnvelope({schemaVersion:"1",streamKind:"run",workspaceId,streamId:runId,sequence:2,eventId:"resolve:2",eventType:"TaskResolvedV1",principalId:"authority",causationId:"resolve",correlationId:"run",idempotencyKey:"resolve",priorEnvelopeHash:created.event.envelopeHash,payload});authorityStore.appendAtomic({commandId:"resolve",run:{streamKind:"run",workspaceId,streamId:runId,expectedSequence:1,expectedEnvelopeHash:created.event.envelopeHash,events:[resolved]}});authorityStore.db.prepare("INSERT OR REPLACE INTO snapshots(workspace_id,stream_kind,stream_id,sequence,envelope_hash,projection_name,projection_version,state_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(workspaceId,"run",runId,2,resolved.envelopeHash,"task-resolution/source","1",JSON.stringify({workspaceId,runId,taskId:"source",resolution,winningGeneration,eventSequence:2,eventDigest:resolved.envelopeHash}),"2026-08-12T00:00:00.000Z");authorityStore.close();const session=SQLiteAuthority.openAuthenticatedWorkspace(database,artifacts,{workspaceId,sessionId:`resolution-${workspaceId}`,credential:createOrLoadAuthorityCredential(database,artifacts,workspaceId)});opened=session.authority;return issueStoredTaskResolvedCapability(session.reader,{workspaceId,runId,taskId:"source"})}finally{try{authorityStore.close()}catch{}opened?.close();rmSync(path,{recursive:true,force:true})}}

test("raw self-hashed authority events cannot project through direct or package-root APIs",()=>{const raw=rawEvent({eventType:"BindingValidSelectedReceiptV1",workspaceId:"w",runId:"r",taskId:"source",receiptDigest:"receipt",generation:1,attemptContextBindingDigest:"binding",bindingValid:true,selected:true,outcome:"succeeded"},1,null);const state=graph({kind:"receipt-only"});assert.throws(()=>projectDurablePredicate(state,raw as VerifiedAuthorityEventV1),/PREDICATE_EVENT_UNVERIFIED/);assert.throws(()=>projectDurablePredicateFromPackageRoot(state,raw as VerifiedAuthorityEventV1),/PREDICATE_EVENT_UNVERIFIED/);const verified=event(raw.envelope.payload,1,null);assert.ok(Object.isFrozen(verified));assert.ok(Object.isFrozen(verified.envelope));assert.throws(()=>projectDurablePredicate(state,{...verified} as VerifiedAuthorityEventV1),/PREDICATE_EVENT_UNVERIFIED/)});
function graph(sourcePolicy:CompletionPredicateV1,edgeType:"requires_success"|"requires_terminal"|"requires_outcome"="requires_success",allowedOutcomes?:Array<"succeeded"|"failed"|"cancelled">,propagateCancellation=false){let state=emptyTaskProjection();state=addTask(state,{taskId:"source",contractDigest:"source-contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:sourcePolicy}});state=addTask(state,{taskId:"dependent",contractDigest:"dependent-contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});state=addDependency(state,{edgeId:"edge",sourceTaskId:"source",dependentTaskId:"dependent",edgeType,releasePredicate:completionPredicateIdentity(sourcePolicy),...(allowedOutcomes===undefined?{}:{allowedOutcomes}),propagateCancellation});state=activateTask(state,"source");state=activateTask(state,"dependent");return state}

test("dependency edges bind an exact completion predicate identity and reject cycles",()=>{const p=predicate("source");let state=emptyTaskProjection();state=addTask(state,{taskId:"a",contractDigest:"a",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:p}});state=addTask(state,{taskId:"b",contractDigest:"b",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});assert.throws(()=>addDependency(state,{edgeId:"bad",sourceTaskId:"a",dependentTaskId:"b",edgeType:"requires_success",releasePredicate:"task-resolution",propagateCancellation:false}),/INVALID_RELEASE_PREDICATE/);state=addDependency(state,{edgeId:"ab",sourceTaskId:"a",dependentTaskId:"b",edgeType:"requires_success",releasePredicate:completionPredicateIdentity(p),propagateCancellation:false});assert.throws(()=>addDependency(state,{edgeId:"ba",sourceTaskId:"b",dependentTaskId:"a",edgeType:"requires_terminal",releasePredicate:completionPredicateIdentity({kind:"receipt-only"}),propagateCancellation:false}),/DEPENDENCY_CYCLE/)});

test("canonical-change release requires the exact authenticated DeltaAccepted event",()=>{const expected=predicate("source");let state=graph(expected);const invented=rawEvent({eventType:"DeltaAcceptedV1",workspaceId:"w",runId:"r",taskId:"source",proposalDigest:"proposal-source",resultingRevision:1,resultingStateHash:"state-source"},1,null);assert.throws(()=>projectDurablePredicate(state,invented as VerifiedAuthorityEventV1),/PREDICATE_EVENT_UNVERIFIED/);assert.throws(()=>resolveProjectedTask(state,{taskId:"source",resolution:"succeeded",winningGeneration:1,eventSequence:3,eventDigest:"resolution",workspaceId:"w",runId:"r",compositeCursor:baseCursor} as StoredTaskResolvedCapabilityV1),/TASK_RESOLUTION_UNAUTHENTICATED/);
  const accepted=event({eventType:"DeltaAcceptedV1",workspaceId:"w",runId:"r",taskId:"source",proposalDigest:"proposal-source",resultingRevision:1,resultingStateHash:"state-source"},2,"genesis");const exact={...expected,acceptedEventDigest:accepted.envelopeHash};state=emptyTaskProjection();state=addTask(state,{taskId:"source",contractDigest:"source-contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:exact}});state=addTask(state,{taskId:"dependent",contractDigest:"dependent-contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});state=addDependency(state,{edgeId:"edge",sourceTaskId:"source",dependentTaskId:"dependent",edgeType:"requires_success",releasePredicate:completionPredicateIdentity(exact),propagateCancellation:false});state=activateTask(activateTask(state,"source"),"dependent");state=projectDurablePredicate(state,accepted);state=resolveProjectedTask(state,resolutionCapability("succeeded",2));assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor:accepted.resultCursor,authority:authority(accepted)}).schedulability,"ready")});

test("closed event projectors cover selected receipt, artifacts, and approval while rejecting arbitrary facts",()=>{const cases:Array<[CompletionPredicateV1,DurablePredicatePayloadV1]>=[
  [{kind:"receipt-only"},{eventType:"BindingValidSelectedReceiptV1",workspaceId:"w",runId:"r",taskId:"source",receiptDigest:"receipt",generation:2,attemptContextBindingDigest:"binding",bindingValid:true,selected:true,outcome:"succeeded"}],
  [{kind:"artifact-published",objectDigests:["object"],publicationEventDigests:["publication-record"]},{eventType:"ArtifactPublishedV1",workspaceId:"w",runId:"r",taskId:"source",objectDigests:["object"],publicationEventDigests:["publication-record"]}],
  [{kind:"approval-recorded",approvalId:"approval",scopeDigest:"scope",evaluationCursor:baseCursor,expiresAt:"2027-01-01T00:00:00Z"},{eventType:"ApprovalRecordedV1",workspaceId:"w",runId:"r",taskId:"source",approvalId:"approval",scopeDigest:"scope",evaluationCursor:baseCursor,expiresAt:"2027-01-01T00:00:00Z"}],
 ];
  for(const [policy,payload] of cases){const projected=event(payload,2,"genesis");let state=graph(policy);state=projectDurablePredicate(state,projected);state=resolveProjectedTask(state,resolutionCapability("succeeded",payload.eventType==="BindingValidSelectedReceiptV1"?payload.generation:null));assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor:projected.resultCursor,authority:authority(projected)}).schedulability,"ready")}
});

test("all edge types, mixed outcomes, cancellation propagation, and unresolved retries are deterministic",()=>{for(const [edgeType,resolution,allowed,expected] of [["requires_success","failed",undefined,"blocked"],["requires_terminal","failed",undefined,"ready"],["requires_outcome","failed",["failed"],"ready"]] as const){const p:CompletionPredicateV1={kind:"receipt-only"};let state=graph(p,edgeType,allowed===undefined?undefined:[...allowed]);const selected=event({eventType:"BindingValidSelectedReceiptV1",workspaceId:"w",runId:"r",taskId:"source",receiptDigest:"receipt",generation:2,attemptContextBindingDigest:"binding",bindingValid:true,selected:true,outcome:"succeeded"},2,"genesis");state=projectDurablePredicate(state,selected);state=resolveProjectedTask(state,resolutionCapability(resolution,null));assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor:selected.resultCursor,authority:authority(selected)}).schedulability,expected)}
  let cancelled=graph({kind:"receipt-only"},"requires_terminal",undefined,true);const selected=event({eventType:"BindingValidSelectedReceiptV1",workspaceId:"w",runId:"r",taskId:"source",receiptDigest:"receipt",generation:3,attemptContextBindingDigest:"binding",bindingValid:true,selected:true,outcome:"succeeded"},4,"prior");cancelled=projectDurablePredicate(cancelled,selected);cancelled=resolveProjectedTask(cancelled,resolutionCapability("cancelled",null));const joined=evaluateTaskJoin(cancelled,{taskId:"dependent",cursor:selected.resultCursor,authority:authority(selected)});assert.equal(joined.schedulability,"ineligible");assert.deepEqual(joined.reasonCodes,["CANCELLATION_PROPAGATED"]);
  const unresolved=graph({kind:"receipt-only"}),observation=event({eventType:"ArtifactPublishedV1",workspaceId:"w",runId:"r",taskId:"dependent",objectDigests:["authority"],publicationEventDigests:["authority"]},1,null);assert.deepEqual(evaluateTaskJoin(unresolved,{taskId:"dependent",cursor:observation.resultCursor,authority:authority(observation)}).reasonCodes,["DEPENDENCY_UNKNOWN"])});

test("authenticated composite authority rejects invented readiness and substituted components",()=>{const state=activateTask(addTask(emptyTaskProjection(),{taskId:"dependent",contractDigest:"contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}}),"dependent"),observation=event({eventType:"ArtifactPublishedV1",workspaceId:"w",runId:"r",taskId:"dependent",objectDigests:["authority"],publicationEventDigests:["authority"]},1,null),cursor=observation.resultCursor;const blocked=authority(observation,{policy:{kind:"policy",state:"denied"},"grant-revocation":{kind:"grant-revocation",grantState:"unknown",revocationState:"revoked"},quota:{kind:"quota",state:"exhausted"}});const first=evaluateTaskJoin(state,{taskId:"dependent",cursor,authority:blocked});const replay=evaluateTaskJoin(state,{taskId:"dependent",cursor,authority:blocked});assert.equal(first.schedulability,"blocked");assert.deepEqual(first.reasonCodes,["GRANT_REVOKED","GRANT_UNKNOWN","POLICY_DENIED","QUOTA_EXHAUSTED"]);assert.equal(first.authoritySnapshotIdentities.length,5);assert.equal(first.snapshot.digest,replay.snapshot.digest);assert.throws(()=>evaluateTaskJoin(state,{taskId:"dependent",cursor:{...cursor,runId:"other"},authority:blocked}),/AUTHORITY_CURSOR_SUBSTITUTED/);
  const forged={...blocked,components:blocked.components.map(component=>component.value.kind==="policy"?{...component,value:{kind:"policy" as const,state:"allowed" as const}}:component)} as TaskAuthorityProjectionV1;assert.throws(()=>evaluateTaskJoin(state,{taskId:"dependent",cursor,authority:forged}),/AUTHORITY_PROOF_INVALID/);
  const substituted={...blocked,components:blocked.components.map((component,index)=>index===0?{...component,observationCursor:{...cursor,runSequence:2}}:component)} as TaskAuthorityProjectionV1;assert.throws(()=>evaluateTaskJoin(state,{taskId:"dependent",cursor,authority:substituted}),/AUTHORITY_PROOF_INVALID/);
  const empty={...blocked,components:blocked.components.map((component,index)=>index===0?{...component,projectionProof:{...component.projectionProof,snapshotDigest:""}}:component)} as TaskAuthorityProjectionV1;assert.throws(()=>evaluateTaskJoin(state,{taskId:"dependent",cursor,authority:empty}),/AUTHORITY_PROOF_INVALID/);assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor,authority:authority(observation)}).schedulability,"ready");assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor,authority:authority(observation,{"attempt-outcome":{kind:"attempt-outcome",state:"unknown_outcome"}})}).schedulability,"unknown_outcome");assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor,authority:authority(observation,{"attempt-outcome":{kind:"attempt-outcome",state:"live"}})}).schedulability,"running")});
