import assert from "node:assert/strict";
import test from "node:test";
import { completionPredicateIdentity, domainDigest, sealEventEnvelope, type CompletionPredicateV1, type CompositeCursorV1, type JsonValue } from "@horseness/domain";
import { activateTask, addDependency, addTask, authenticateTaskAuthorityProjection, authorityReplayDigest, emptyTaskProjection, evaluateTaskJoin, projectDurablePredicate, resolveProjectedTask, verifyAuthorityEvent, type DurableAuthorityEventV1, type DurablePredicatePayloadV1, type TaskAuthorityComponentSnapshotV1, type TaskAuthorityProjectionV1, type VerifiedAuthorityEventV1 } from "../../src/tasks/task-projection.js";

const baseCursor:CompositeCursorV1={schemaVersion:"1",kind:"composite",workspaceId:"w",workspaceSequence:3,workspaceEnvelopeHash:"workspace-3",workspaceContextEpoch:2,runId:"r",runSequence:1,runEnvelopeHash:"genesis",runContextEpoch:0};
const predicate=(taskId:string):CompletionPredicateV1=>({kind:"canonical-change",proposalDigest:`proposal-${taskId}`,acceptedEventDigest:`event-${taskId}`,resultingRevision:1,resultingStateHash:`state-${taskId}`});
type ComponentValue=TaskAuthorityComponentSnapshotV1["value"];
const authority=(cursor:CompositeCursorV1,overrides:Partial<Record<ComponentValue["kind"],ComponentValue>>={}):TaskAuthorityProjectionV1=>{const values:ComponentValue[]=[overrides.contract??{kind:"contract",valid:true},overrides.policy??{kind:"policy",state:"allowed"},overrides["grant-revocation"]??{kind:"grant-revocation",grantState:"allowed",revocationState:"clear"},overrides.quota??{kind:"quota",state:"available"},overrides["attempt-outcome"]??{kind:"attempt-outcome",state:"none"}];const components=values.map(value=>{const core={schemaVersion:"1" as const,workspaceId:"w",runId:"r",taskId:"dependent",observationCursor:cursor,value};const projectionName=`task-authority/${value.kind}`,snapshotDigest=domainDigest("horseness.task-authority-component.v1",core as unknown as JsonValue);return {...core,projectionProof:{schemaVersion:"1" as const,projectionName,projectionVersion:"1" as const,snapshotDigest,replayDigest:domainDigest("horseness.task-authority-replay-proof.v1",{projectionName,projectionVersion:"1",observationCursor:cursor,snapshotDigest} as unknown as JsonValue)}}});return authenticateTaskAuthorityProjection({schemaVersion:"1",observationCursor:cursor,taskId:"dependent",components,compositeDigest:domainDigest("horseness.task-authority-composite.v1",{schemaVersion:"1",observationCursor:cursor,taskId:"dependent",componentDigests:components.map(component=>component.projectionProof.snapshotDigest)} as unknown as JsonValue)})};
function rawEvent(payload:DurablePredicatePayloadV1,sequence:number,prior:string|null):DurableAuthorityEventV1 {
  const sealed=sealEventEnvelope({schemaVersion:"1",streamKind:"run",workspaceId:"w",streamId:"r",sequence,eventId:`event-${sequence}`,eventType:payload.eventType,principalId:"authority",causationId:"command",correlationId:"run",idempotencyKey:`key-${sequence}`,priorEnvelopeHash:prior,payload});
  return {envelope:sealed.envelope,envelopeHash:sealed.envelopeHash,resultCursor:{...baseCursor,runSequence:sequence,runEnvelopeHash:sealed.envelopeHash,runContextEpoch:sequence-1}};
}
function event(payload:DurablePredicatePayloadV1,sequence:number,_prior:string|null):VerifiedAuthorityEventV1 {const replay:DurableAuthorityEventV1[]=[];let prior:string|null=null;for(let current=1;current<sequence;current+=1){const filler=rawEvent({eventType:"ArtifactPublishedV1",workspaceId:"w",runId:"r",taskId:"unrelated",objectDigests:[`object-${current}`],publicationEventDigests:[`publication-${current}`]},current,prior);replay.push(filler);prior=filler.envelopeHash}const candidate=rawEvent(payload,sequence,prior);replay.push(candidate);return verifyAuthorityEvent(candidate,{workspaceId:"w",runId:"r",headSequence:sequence,headEnvelopeHash:candidate.envelopeHash,authorityReplayDigest:authorityReplayDigest(replay),replay,authorizedProducers:{[payload.eventType]:["authority"]}})}
function graph(sourcePolicy:CompletionPredicateV1,edgeType:"requires_success"|"requires_terminal"|"requires_outcome"="requires_success",allowedOutcomes?:Array<"succeeded"|"failed"|"cancelled">,propagateCancellation=false){let state=emptyTaskProjection();state=addTask(state,{taskId:"source",contractDigest:"source-contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:sourcePolicy}});state=addTask(state,{taskId:"dependent",contractDigest:"dependent-contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});state=addDependency(state,{edgeId:"edge",sourceTaskId:"source",dependentTaskId:"dependent",edgeType,releasePredicate:completionPredicateIdentity(sourcePolicy),...(allowedOutcomes===undefined?{}:{allowedOutcomes}),propagateCancellation});return activateTask(activateTask(state,"source"),"dependent")}

test("dependency edges bind an exact completion predicate identity and reject cycles",()=>{const p=predicate("source");let state=emptyTaskProjection();state=addTask(state,{taskId:"a",contractDigest:"a",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:p}});state=addTask(state,{taskId:"b",contractDigest:"b",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});assert.throws(()=>addDependency(state,{edgeId:"bad",sourceTaskId:"a",dependentTaskId:"b",edgeType:"requires_success",releasePredicate:"task-resolution",propagateCancellation:false}),/INVALID_RELEASE_PREDICATE/);state=addDependency(state,{edgeId:"ab",sourceTaskId:"a",dependentTaskId:"b",edgeType:"requires_success",releasePredicate:completionPredicateIdentity(p),propagateCancellation:false});assert.throws(()=>addDependency(state,{edgeId:"ba",sourceTaskId:"b",dependentTaskId:"a",edgeType:"requires_terminal",releasePredicate:completionPredicateIdentity({kind:"receipt-only"}),propagateCancellation:false}),/DEPENDENCY_CYCLE/)});

test("canonical-change release requires the exact authenticated DeltaAccepted event",()=>{const expected=predicate("source");let state=graph(expected);const invented=rawEvent({eventType:"DeltaAcceptedV1",workspaceId:"w",runId:"r",taskId:"source",proposalDigest:"proposal-source",resultingRevision:1,resultingStateHash:"state-source"},2,"genesis");const inventedReplay=[rawEvent({eventType:"ArtifactPublishedV1",workspaceId:"w",runId:"r",taskId:"unrelated",objectDigests:["object"],publicationEventDigests:["publication"]},1,null),invented];assert.throws(()=>verifyAuthorityEvent(invented,{workspaceId:"w",runId:"r",headSequence:2,headEnvelopeHash:invented.envelopeHash,authorityReplayDigest:"invented-self-assertion",replay:inventedReplay}),/PREDICATE_EVENT_UNAUTHENTICATED/);assert.throws(()=>resolveProjectedTask(state,{taskId:"source",resolution:"succeeded",winningGeneration:1,eventSequence:3,eventDigest:"resolution"}),/TASK_COMPLETION_UNSATISFIED/);
  const accepted=event({eventType:"DeltaAcceptedV1",workspaceId:"w",runId:"r",taskId:"source",proposalDigest:"proposal-source",resultingRevision:1,resultingStateHash:"state-source"},2,"genesis");const exact={...expected,acceptedEventDigest:accepted.envelopeHash};state=emptyTaskProjection();state=addTask(state,{taskId:"source",contractDigest:"source-contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:exact}});state=addTask(state,{taskId:"dependent",contractDigest:"dependent-contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});state=addDependency(state,{edgeId:"edge",sourceTaskId:"source",dependentTaskId:"dependent",edgeType:"requires_success",releasePredicate:completionPredicateIdentity(exact),propagateCancellation:false});state=activateTask(activateTask(state,"source"),"dependent");state=projectDurablePredicate(state,accepted);state=resolveProjectedTask(state,{taskId:"source",resolution:"succeeded",winningGeneration:2,eventSequence:3,eventDigest:"resolution"});assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor:accepted.resultCursor,authority:authority(accepted.resultCursor)}).schedulability,"ready")});

test("closed event projectors cover selected receipt, artifacts, and approval while rejecting arbitrary facts",()=>{const cases:Array<[CompletionPredicateV1,DurablePredicatePayloadV1]>=[
  [{kind:"receipt-only"},{eventType:"BindingValidSelectedReceiptV1",workspaceId:"w",runId:"r",taskId:"source",receiptDigest:"receipt",generation:2,attemptContextBindingDigest:"binding",bindingValid:true,selected:true,outcome:"succeeded"}],
  [{kind:"artifact-published",objectDigests:["object"],publicationEventDigests:["publication-record"]},{eventType:"ArtifactPublishedV1",workspaceId:"w",runId:"r",taskId:"source",objectDigests:["object"],publicationEventDigests:["publication-record"]}],
  [{kind:"approval-recorded",approvalId:"approval",scopeDigest:"scope",evaluationCursor:baseCursor,expiresAt:"2027-01-01T00:00:00Z"},{eventType:"ApprovalRecordedV1",workspaceId:"w",runId:"r",taskId:"source",approvalId:"approval",scopeDigest:"scope",evaluationCursor:baseCursor,expiresAt:"2027-01-01T00:00:00Z"}],
 ];
  for(const [policy,payload] of cases){const projected=event(payload,2,"genesis");let state=graph(policy);state=projectDurablePredicate(state,projected);state=resolveProjectedTask(state,{taskId:"source",resolution:"succeeded",winningGeneration:payload.eventType==="BindingValidSelectedReceiptV1"?payload.generation:null,eventSequence:3,eventDigest:"resolution"});assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor:projected.resultCursor,authority:authority(projected.resultCursor)}).schedulability,"ready")}
});

test("all edge types, mixed outcomes, cancellation propagation, and unresolved retries are deterministic",()=>{for(const [edgeType,resolution,allowed,expected] of [["requires_success","failed",undefined,"blocked"],["requires_terminal","failed",undefined,"ready"],["requires_outcome","failed",["failed"],"ready"]] as const){const p:CompletionPredicateV1={kind:"receipt-only"};let state=graph(p,edgeType,allowed===undefined?undefined:[...allowed]);const selected=event({eventType:"BindingValidSelectedReceiptV1",workspaceId:"w",runId:"r",taskId:"source",receiptDigest:"receipt",generation:2,attemptContextBindingDigest:"binding",bindingValid:true,selected:true,outcome:"succeeded"},2,"genesis");state=projectDurablePredicate(state,selected);state=resolveProjectedTask(state,{taskId:"source",resolution,winningGeneration:resolution==="succeeded"?2:null,eventSequence:3,eventDigest:"resolution"});assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor:selected.resultCursor,authority:authority(selected.resultCursor)}).schedulability,expected)}
  let cancelled=graph({kind:"receipt-only"},"requires_terminal",undefined,true);const selected=event({eventType:"BindingValidSelectedReceiptV1",workspaceId:"w",runId:"r",taskId:"source",receiptDigest:"receipt",generation:3,attemptContextBindingDigest:"binding",bindingValid:true,selected:true,outcome:"succeeded"},4,"prior");cancelled=projectDurablePredicate(cancelled,selected);cancelled=resolveProjectedTask(cancelled,{taskId:"source",resolution:"cancelled",winningGeneration:null,eventSequence:5,eventDigest:"cancelled"});const joined=evaluateTaskJoin(cancelled,{taskId:"dependent",cursor:selected.resultCursor,authority:authority(selected.resultCursor)});assert.equal(joined.schedulability,"ineligible");assert.deepEqual(joined.reasonCodes,["CANCELLATION_PROPAGATED"]);
  const unresolved=graph({kind:"receipt-only"});assert.deepEqual(evaluateTaskJoin(unresolved,{taskId:"dependent",cursor:baseCursor,authority:authority(baseCursor)}).reasonCodes,["DEPENDENCY_UNKNOWN"])});

test("authenticated composite authority rejects invented readiness and substituted components",()=>{const state=activateTask(addTask(emptyTaskProjection(),{taskId:"dependent",contractDigest:"contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}}),"dependent");const blocked=authority(baseCursor,{policy:{kind:"policy",state:"denied"},"grant-revocation":{kind:"grant-revocation",grantState:"unknown",revocationState:"revoked"},quota:{kind:"quota",state:"exhausted"}});const first=evaluateTaskJoin(state,{taskId:"dependent",cursor:baseCursor,authority:blocked});const replay=evaluateTaskJoin(state,{taskId:"dependent",cursor:baseCursor,authority:blocked});assert.equal(first.schedulability,"blocked");assert.deepEqual(first.reasonCodes,["GRANT_REVOKED","GRANT_UNKNOWN","POLICY_DENIED","QUOTA_EXHAUSTED"]);assert.equal(first.authoritySnapshotIdentities.length,5);assert.equal(first.snapshot.digest,replay.snapshot.digest);assert.throws(()=>evaluateTaskJoin(state,{taskId:"dependent",cursor:{...baseCursor,runId:"other"},authority:blocked}),/AUTHORITY_CURSOR_SUBSTITUTED/);
  const forged={...blocked,components:blocked.components.map(component=>component.value.kind==="policy"?{...component,value:{kind:"policy" as const,state:"allowed" as const}}:component)} as TaskAuthorityProjectionV1;assert.throws(()=>evaluateTaskJoin(state,{taskId:"dependent",cursor:baseCursor,authority:forged}),/AUTHORITY_PROOF_INVALID/);
  const substituted={...blocked,components:blocked.components.map((component,index)=>index===0?{...component,observationCursor:{...baseCursor,runSequence:2}}:component)} as TaskAuthorityProjectionV1;assert.throws(()=>evaluateTaskJoin(state,{taskId:"dependent",cursor:baseCursor,authority:substituted}),/AUTHORITY_CURSOR_SUBSTITUTED/);
  const empty={...blocked,components:blocked.components.map((component,index)=>index===0?{...component,projectionProof:{...component.projectionProof,snapshotDigest:""}}:component)} as TaskAuthorityProjectionV1;assert.throws(()=>evaluateTaskJoin(state,{taskId:"dependent",cursor:baseCursor,authority:empty}),/AUTHORITY_PROOF_INVALID/);assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor:baseCursor,authority:authority(baseCursor)}).schedulability,"ready");assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor:baseCursor,authority:authority(baseCursor,{"attempt-outcome":{kind:"attempt-outcome",state:"unknown_outcome"}})}).schedulability,"unknown_outcome");assert.equal(evaluateTaskJoin(state,{taskId:"dependent",cursor:baseCursor,authority:authority(baseCursor,{"attempt-outcome":{kind:"attempt-outcome",state:"live"}})}).schedulability,"running")});
