import assert from "node:assert/strict";
import test from "node:test";
import { completionPredicateIdentity, sealAttemptReceipt, type CompositeCursorV1, type CompletionPredicateV1 } from "@horseness/domain";
import { activateTask, addDependency, addTask, emptyTaskProjection, evaluateTaskJoin, recordDurablePredicate, resolveProjectedTask } from "../../src/tasks/task-projection.js";
import { emptyReceiptProjection, projectReceipt } from "../../src/receipts/receipt-projection.js";

const cursor:CompositeCursorV1={schemaVersion:"1",kind:"composite",workspaceId:"w",workspaceSequence:1,workspaceEnvelopeHash:"wh",workspaceContextEpoch:0,runId:"r",runSequence:4,runEnvelopeHash:"rh",runContextEpoch:3};
const receipt=(generation:number,outcome:"succeeded"|"failed"|"cancelled",nonce:string)=>sealAttemptReceipt({schemaVersion:"1",workspaceId:"w",runId:"r",taskId:"a",attemptId:"attempt",generation,attemptContextBindingDigest:"b",contextManifestCoreDigest:"m",forkPinDigest:"f",providerId:"p",providerOperationId:`op${generation}`,providerIdempotencyKeyDigest:`key${generation}`,producerPrincipalId:"principal",producerGrantDigest:"grant",adapterId:"adapter",adapterVersion:"1",hostId:"host",hostVersion:"1",outcome,startedAt:"2026-01-01T00:00:00Z",finishedAt:"2026-01-01T00:00:01Z",outputDigest:outcome==="succeeded"?`output${generation}`:null,evidence:[],provenance:{},nonce});
test("rejects cycles, self edges, and mutation after activation",()=>{let state=emptyTaskProjection();state=addTask(state,{taskId:"a",contractDigest:"ca",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});state=addTask(state,{taskId:"b",contractDigest:"cb",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});state=addDependency(state,{edgeId:"ab",sourceTaskId:"a",dependentTaskId:"b",edgeType:"requires_success",releasePredicate:"task-resolution",propagateCancellation:false});assert.throws(()=>addDependency(state,{edgeId:"ba",sourceTaskId:"b",dependentTaskId:"a",edgeType:"requires_terminal",releasePredicate:"task-resolution",propagateCancellation:false}),/DEPENDENCY_CYCLE/);assert.throws(()=>addDependency(state,{edgeId:"aa",sourceTaskId:"a",dependentTaskId:"a",edgeType:"requires_success",releasePredicate:"task-resolution",propagateCancellation:false}),/INVALID_DEPENDENCY/);state=activateTask(state,"a");assert.throws(()=>addDependency(state,{edgeId:"late",sourceTaskId:"a",dependentTaskId:"b",edgeType:"requires_terminal",releasePredicate:"task-resolution",propagateCancellation:false}),/LATE_DEPENDENCY_MUTATION/);});
test("durable resolution releases joins while receipts alone cannot satisfy canonical change",()=>{const canonical:CompletionPredicateV1={kind:"canonical-change",proposalDigest:"p",acceptedEventDigest:"accepted",resultingRevision:1,resultingStateHash:"s"};let state=emptyTaskProjection();state=addTask(state,{taskId:"a",contractDigest:"ca",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:canonical}});state=addTask(state,{taskId:"b",contractDigest:"cb",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});state=addDependency(state,{edgeId:"ab",sourceTaskId:"a",dependentTaskId:"b",edgeType:"requires_success",releasePredicate:"task-resolution",propagateCancellation:false});state=activateTask(activateTask(state,"a"),"b");state=recordDurablePredicate(state,"a",{kind:"receipt-only"});assert.throws(()=>resolveProjectedTask(state,{taskId:"a",resolution:"succeeded",winningGeneration:1,eventSequence:5,eventDigest:"resolved"}),/TASK_COMPLETION_UNSATISFIED/);state=recordDurablePredicate(state,"a",canonical);assert.ok(state.tasks.get("a")?.durablePredicateIds.has(completionPredicateIdentity(canonical)));state=resolveProjectedTask(state,{taskId:"a",resolution:"succeeded",winningGeneration:2,eventSequence:6,eventDigest:"resolved"});const join=evaluateTaskJoin(state,{taskId:"b",cursor,authorizationAllowed:true,quotaAllowed:true,liveAttempt:false,unknownOutcome:false});assert.equal(join.schedulability,"ready");assert.equal(join.snapshot.core.dependencies[0]?.winningGeneration,2);});
test("receipt generations arbitrate earliest success and flag duplicates and late outcomes",()=>{let state=emptyReceiptProjection("attempt");state=projectReceipt(state,receipt(1,"failed","n1"),8);state=projectReceipt(state,receipt(2,"succeeded","n2"),10);state=projectReceipt(state,receipt(3,"succeeded","n3"),12);assert.equal(state.winningGeneration,2);assert.ok(state.findings.includes("LATE_GENERATION_RECEIPT"));state=projectReceipt(state,receipt(2,"succeeded","n2"),10);assert.ok(state.findings.includes("DUPLICATE_RECEIPT"));});
