import { DomainError, canonicalJson, createForkPin, deltaAuthorityScopeDigest, refreshForkPin, verifyForkPin, type CompositeCursorV1, type ContextVersionV1, type DeltaAuthorityScopeV1, type SealedForkPinV1 } from "@horseness/domain";

export interface ForkAuthorityContextV1 { workspaceId:string;runId:string;canonicalRevision:number;canonicalStateHash:string;cursor:CompositeCursorV1;contextVersion:ContextVersionV1;dependencyJoinSnapshotDigest:string;scope:DeltaAuthorityScopeV1;pinnedPolicyDigest:string;revocationDigest:string;quotaDigest:string;principalId:string;grantDigest:string }
export interface ForkProjectionV1 { pins:ReadonlyMap<string,SealedForkPinV1>; activeByForkId:ReadonlyMap<string,string>; authorityContextDigestByPin:ReadonlyMap<string,string> }
export function emptyForkProjection():ForkProjectionV1{return {pins:new Map(),activeByForkId:new Map(),authorityContextDigestByPin:new Map()};}
function authorityDigest(context:ForkAuthorityContextV1):string { return JSON.stringify([context.revocationDigest,context.pinnedPolicyDigest,context.quotaDigest,context.grantDigest]); }
function input(context:ForkAuthorityContextV1){if(context.scope.workspaceId!==context.workspaceId||context.scope.runId!==context.runId)throw new DomainError("CAPABILITY_SCOPE_MISMATCH");return {schemaVersion:"1" as const,canonicalRevision:context.canonicalRevision,canonicalStateHash:context.canonicalStateHash,canonicalizerVersion:"jcs-v1" as const,hashVersion:"sha256-v1" as const,sourceObservationCursor:context.cursor,sourceContextVersion:context.contextVersion,dependencyJoinSnapshotDigest:context.dependencyJoinSnapshotDigest,deltaAuthorityScopeDigest:deltaAuthorityScopeDigest(context.scope),pinnedPolicyDigest:context.pinnedPolicyDigest,createdByPrincipalId:context.principalId,createdByGrantDigest:context.grantDigest};}
export function createProjectedFork(state:ForkProjectionV1,forkId:string,context:ForkAuthorityContextV1):{state:ForkProjectionV1;pin:SealedForkPinV1}{if(state.activeByForkId.has(forkId))throw new DomainError("FORK_IDENTITY_CONTINUITY");const pin=createForkPin({...input(context),forkId,pinVersion:1,workspaceId:context.workspaceId,runId:context.runId,parentForkPinDigest:null,refreshesForkPinDigest:null},null);return store(state,pin,context);}
export function refreshProjectedFork(state:ForkProjectionV1,forkId:string,context:ForkAuthorityContextV1):{state:ForkProjectionV1;pin:SealedForkPinV1}{const digest=state.activeByForkId.get(forkId);const parent=digest?state.pins.get(digest):undefined;if(!parent)throw new DomainError("FORK_PARENT_MISMATCH");const pin=refreshForkPin(parent,input(context));return store(state,pin,context);}
export function reuseProjectedFork(state:ForkProjectionV1,forkId:string,context:ForkAuthorityContextV1):SealedForkPinV1{const digest=state.activeByForkId.get(forkId);const pin=digest?state.pins.get(digest):undefined;if(!pin)throw new DomainError("FORK_PARENT_MISMATCH");verifyForkPin(pin);if(pin.core.canonicalRevision!==context.canonicalRevision||pin.core.canonicalStateHash!==context.canonicalStateHash||pin.core.dependencyJoinSnapshotDigest!==context.dependencyJoinSnapshotDigest||pin.core.deltaAuthorityScopeDigest!==deltaAuthorityScopeDigest(context.scope)||pin.core.pinnedPolicyDigest!==context.pinnedPolicyDigest||canonicalJson(pin.core.sourceObservationCursor)!==canonicalJson(context.cursor)||state.authorityContextDigestByPin.get(pin.forkPinDigest)!==authorityDigest(context))throw new DomainError("FORK_REUSE_STALE");return pin;}
function store(state:ForkProjectionV1,pin:SealedForkPinV1,context:ForkAuthorityContextV1):{state:ForkProjectionV1;pin:SealedForkPinV1}{const pins=new Map(state.pins);pins.set(pin.forkPinDigest,pin);const active=new Map(state.activeByForkId);active.set(pin.core.forkId,pin.forkPinDigest);const authorities=new Map(state.authorityContextDigestByPin);authorities.set(pin.forkPinDigest,authorityDigest(context));return {state:{pins,activeByForkId:active,authorityContextDigestByPin:authorities},pin};}
