import {attemptContextBindingDigest,canonicalScope,contextManifestCoreDigest,parseDomainCommandResultV1,parseDomainCommandV1,parseDomainQueryV1,parseQueryResultV1,sealDependencyJoinSnapshot,validateDependencyEdge,verifyAttemptReceipt,verifyForkPin,verifyProposal,type AttemptContextBindingV1,type AttemptReceiptEnvelopeV1,type ContextManifestCoreV1,type DeltaAuthorityScopeV1,type DependencyEdgeV1,type DependencyJoinSnapshotCoreV1,type DomainCommandResultV1,type DomainCommandV1,type DomainQueryV1,type ProposalEnvelopeV1,type QueryResultV1,type SealedForkPinV1} from "@horseness/domain";
import {ProtocolError} from "./errors.js";
export type DomainMappingNameV1="domain-command"|"domain-command-result"|"domain-query"|"domain-query-result"|"attempt-receipt"|"proposal-envelope"|"fork-pin"|"context-manifest"|"attempt-context-binding"|"dependency-edge"|"dependency-join-snapshot"|"delta-authority-scope";
export type DomainWireMappingV1=|{mapping:"domain-command";value:DomainCommandV1}|{mapping:"domain-command-result";value:DomainCommandResultV1}|{mapping:"domain-query";value:DomainQueryV1}|{mapping:"domain-query-result";value:QueryResultV1}|{mapping:"attempt-receipt";value:AttemptReceiptEnvelopeV1}|{mapping:"proposal-envelope";value:ProposalEnvelopeV1}|{mapping:"fork-pin";value:SealedForkPinV1}|{mapping:"context-manifest";value:ContextManifestCoreV1}|{mapping:"attempt-context-binding";value:AttemptContextBindingV1}|{mapping:"dependency-edge";value:DependencyEdgeV1}|{mapping:"dependency-join-snapshot";value:DependencyJoinSnapshotCoreV1}|{mapping:"delta-authority-scope";value:DeltaAuthorityScopeV1};
function exactDomainRecord(value:unknown,keys:readonly string[]):void{if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new Error("invalid domain mapping");const actual=Object.keys(value).sort(),expected=[...keys].sort();if(actual.length!==expected.length||actual.some((key,index)=>key!==expected[index]))throw new Error("invalid domain mapping keys")}
export function parseDomainWireMappingV1(mapping:DomainMappingNameV1,value:unknown):DomainWireMappingV1{try{switch(mapping){
case"domain-command":return{mapping,value:parseDomainCommandV1(value)};case"domain-command-result":return{mapping,value:parseDomainCommandResultV1(value)};case"domain-query":return{mapping,value:parseDomainQueryV1(value)};case"domain-query-result":return{mapping,value:parseQueryResultV1(value)};
case"attempt-receipt":verifyAttemptReceipt(value as AttemptReceiptEnvelopeV1);return{mapping,value:value as AttemptReceiptEnvelopeV1};case"proposal-envelope":verifyProposal(value as ProposalEnvelopeV1);return{mapping,value:value as ProposalEnvelopeV1};
case"fork-pin":{const pin=value as SealedForkPinV1;exactDomainRecord(pin,["core","forkPinDigest","forkPinId"]);exactDomainRecord(pin.core,["schemaVersion","forkId","pinVersion","workspaceId","runId","parentForkPinDigest","refreshesForkPinDigest","canonicalRevision","canonicalStateHash","canonicalizerVersion","hashVersion","sourceObservationCursor","sourceContextVersion","dependencyJoinSnapshotDigest","deltaAuthorityScopeDigest","pinnedPolicyDigest","ancestry","createdByPrincipalId","createdByGrantDigest"]);verifyForkPin(pin);return{mapping,value:pin}}
case"context-manifest":{const manifest=value as ContextManifestCoreV1;exactDomainRecord(manifest,["schemaVersion","workspaceId","runId","attemptId","generation","forkPinDigest","sourceObservationCursor","sourceContextVersion","authorizationObservationCursor","authorizationContextVersion","authorizationOverlayV1","canonicalRevision","canonicalStateHash","canonicalizerVersion","hashVersion","sources","rendererVersion","omissions","selectedBytes","byteBudget","tokenizerMetadata","renderedOutputDigest"]);exactDomainRecord(manifest.authorizationOverlayV1,["policyDigest","grantDigest","quotaDigest","result"]);for(const source of manifest.sources)exactDomainRecord(source,["kind","digest","byteStart","byteEnd","priority"]);contextManifestCoreDigest(manifest);return{mapping,value:manifest}}
case"attempt-context-binding":{const binding=value as AttemptContextBindingV1;exactDomainRecord(binding,["schemaVersion","attemptId","generation","forkPinDigest","contextManifestCoreDigest","sourceObservationCursor","sourceContextVersion","authorizationObservationCursor","authorizationContextVersion","providerIdempotencyKey","expectedReceiptSchemaVersion","allowedProducerPrincipalId","allowedProducerGrantDigest"]);attemptContextBindingDigest(binding);return{mapping,value:binding}}
case"dependency-edge":{const edge=value as DependencyEdgeV1;exactDomainRecord(edge,edge.edgeType==="requires_outcome"?["edgeId","sourceTaskId","dependentTaskId","edgeType","allowedOutcomes","releasePredicate","propagateCancellation"]:["edgeId","sourceTaskId","dependentTaskId","edgeType","releasePredicate","propagateCancellation"]);validateDependencyEdge(edge);return{mapping,value:edge}}
case"dependency-join-snapshot":{const snapshot=value as DependencyJoinSnapshotCoreV1;exactDomainRecord(snapshot,["schemaVersion","runId","taskId","taskContractDigest","joinEvaluationId","joinObservationCursor","dependencies","schedulability","reasonCodes"]);for(const dependency of snapshot.dependencies)exactDomainRecord(dependency,["edgeId","edgeType","sourceTaskId","taskResolutionEventSequence","taskResolutionDigest","winningGeneration"]);sealDependencyJoinSnapshot(snapshot);return{mapping,value:snapshot}}
case"delta-authority-scope":exactDomainRecord(value,["schemaVersion","workspaceId","runId","taskId","roots"]);return{mapping,value:canonicalScope(value as DeltaAuthorityScopeV1)};
}}catch(error){if(error instanceof ProtocolError)throw error;throw new ProtocolError("INVALID_PARAMS",-32602,false,{mapping} as never)}}
export const DOMAIN_MAPPING_NAMES_V1=["domain-command","domain-command-result","domain-query","domain-query-result","attempt-receipt","proposal-envelope","fork-pin","context-manifest","attempt-context-binding","dependency-edge","dependency-join-snapshot","delta-authority-scope"] as const satisfies readonly DomainMappingNameV1[];
