import {assertJsonValue,canonicalJson,parseObservationCursorV1,type JsonValue,type ObservationCursorV1} from "@horseness/domain";
import {isAuthorizedMethod,methodDefinition,PROTOCOL_VERSION,type MethodDefinitionV1,type PrincipalRole,type ProtocolMethodV1} from "./registry.js";
import {parseCoordinatorBodyV1} from "./dto.js";
import {ProtocolError} from "./errors.js";
export type JsonRpcId=string|number|null;
export interface JsonRpcRequestV1{jsonrpc:"2.0";id:JsonRpcId;method:ProtocolMethodV1;params:RpcParamsV1}
export interface RpcParamsV1{protocolVersion:"1";observationCursor:ObservationCursorV1;idempotencyKey?:string;body:JsonValue;page?:PageRequestV1;resume?:SubscriptionResumeV1}
export interface JsonRpcSuccessV1{jsonrpc:"2.0";id:JsonRpcId;result:{schemaVersion:"1";method:ProtocolMethodV1;resultCursor:JsonValue|null;data:JsonValue;page?:PageResultV1;subscription?:SubscriptionResultV1}}
export interface JsonRpcFailureV1{jsonrpc:"2.0";id:JsonRpcId;error:RpcErrorV1}
export type JsonRpcResponseV1=JsonRpcSuccessV1|JsonRpcFailureV1;
export interface RpcErrorV1{code:number;message:string;data:{schemaVersion:"1";reasonCode:ProtocolReasonCode;retryable:boolean;details:JsonValue|null}}
export type ProtocolReasonCode="PARSE_ERROR"|"INVALID_REQUEST"|"METHOD_NOT_FOUND"|"METHOD_NOT_AUTHORIZED"|"INVALID_PARAMS"|"UNSUPPORTED_PROTOCOL_VERSION"|"CURSOR_SCOPE_INSUFFICIENT"|"IDEMPOTENCY_REQUIRED"|"IDEMPOTENCY_FORBIDDEN"|"STALE_OBSERVATION"|"RESUME_TOKEN_INVALID"|"RESUME_TOKEN_EXPIRED"|"INTERNAL_ERROR";
export interface PageRequestV1{schemaVersion:"1";limit:number;afterObservationCursor:ObservationCursorV1|null;continuationToken:string|null}
export interface PageResultV1{schemaVersion:"1";items:JsonValue[];emittedResultCursors:JsonValue[];nextAfterObservationCursor:ObservationCursorV1|null;continuationToken:string|null}
export interface SubscriptionResumeV1{schemaVersion:"1";subscriptionId:string;afterObservationCursor:ObservationCursorV1;resumeToken:string}
export interface SubscriptionResultV1{schemaVersion:"1";subscriptionId:string;resumeToken:string;afterObservationCursor:ObservationCursorV1;emittedResultCursor:JsonValue|null}
export interface TransportSecurityMetadataV1{schemaVersion:"1";transport:"stdio"|"unix-socket"|"windows-named-pipe";localOnly:true;tcpEnabled:false;authenticatedPrincipalId:string;principalRole:PrincipalRole;workspaceId:string;grantDigest:string;osIdentity:string;endpointPermissions:"process-inherited"|"owner-only-0600"|"non-inheriting-owner-dacl"}
const RPC_CODES:Record<ProtocolReasonCode,number>={PARSE_ERROR:-32700,INVALID_REQUEST:-32600,METHOD_NOT_FOUND:-32601,METHOD_NOT_AUTHORIZED:-32001,INVALID_PARAMS:-32602,UNSUPPORTED_PROTOCOL_VERSION:-32002,CURSOR_SCOPE_INSUFFICIENT:-32003,IDEMPOTENCY_REQUIRED:-32004,IDEMPOTENCY_FORBIDDEN:-32005,STALE_OBSERVATION:-32006,RESUME_TOKEN_INVALID:-32007,RESUME_TOKEN_EXPIRED:-32008,INTERNAL_ERROR:-32603};
function exactRecord(value:unknown,keys:readonly string[],reason:ProtocolReasonCode):Record<string,unknown>{if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new ProtocolError(reason,RPC_CODES[reason]);const r=value as Record<string,unknown>,actual=Object.keys(r).sort(),expected=[...keys].sort();if(actual.length!==expected.length||actual.some((key,index)=>key!==expected[index]))throw new ProtocolError(reason,RPC_CODES[reason]);return r}
function text(value:unknown):string{if(typeof value!=="string"||value.length===0)throw new ProtocolError("INVALID_PARAMS",-32602);return value}
function validateCursor(definition:MethodDefinitionV1,cursor:ObservationCursorV1):void{const valid=definition.cursor==="absent-workspace"?cursor.kind==="absent-workspace-genesis":definition.cursor==="workspace"?cursor.kind==="workspace-only":definition.cursor==="absent-run"?cursor.kind==="absent-run-genesis":definition.cursor==="run"?cursor.kind==="run-only"||cursor.kind==="composite":cursor.kind==="composite";if(!valid)throw new ProtocolError("CURSOR_SCOPE_INSUFFICIENT",-32003)}
export function parseJsonRpcRequestV1(value:unknown,role:PrincipalRole):JsonRpcRequestV1{
 const request=exactRecord(value,["jsonrpc","id","method","params"],"INVALID_REQUEST");if(request.jsonrpc!=="2.0"||(typeof request.id!=="string"&&typeof request.id!=="number"&&request.id!==null)||typeof request.method!=="string")throw new ProtocolError("INVALID_REQUEST",-32600);
 const definition=methodDefinition(request.method);if(!definition)throw new ProtocolError("METHOD_NOT_FOUND",-32601);if(!isAuthorizedMethod(role,request.method))throw new ProtocolError("METHOD_NOT_AUTHORIZED",-32001);
 const paramsRecord=request.params as Record<string,unknown>;if(typeof paramsRecord!=="object"||paramsRecord===null||Array.isArray(paramsRecord))throw new ProtocolError("INVALID_PARAMS",-32602);
 const allowed=["protocolVersion","observationCursor","idempotencyKey","body","page","resume"],actual=Object.keys(paramsRecord);if(actual.some((key)=>!allowed.includes(key))||!actual.includes("protocolVersion")||!actual.includes("observationCursor")||!actual.includes("body"))throw new ProtocolError("INVALID_PARAMS",-32602);
 if(paramsRecord.protocolVersion!==PROTOCOL_VERSION)throw new ProtocolError("UNSUPPORTED_PROTOCOL_VERSION",-32002);let cursor:ObservationCursorV1;try{cursor=parseObservationCursorV1(paramsRecord.observationCursor)}catch{throw new ProtocolError("INVALID_PARAMS",-32602)}validateCursor(definition,cursor);
 if(definition.idempotency==="required"){if(typeof paramsRecord.idempotencyKey!=="string"||paramsRecord.idempotencyKey.length===0)throw new ProtocolError("IDEMPOTENCY_REQUIRED",RPC_CODES.IDEMPOTENCY_REQUIRED)}else if(paramsRecord.idempotencyKey!==undefined)throw new ProtocolError("IDEMPOTENCY_FORBIDDEN",RPC_CODES.IDEMPOTENCY_FORBIDDEN);
 const body=parseCoordinatorBodyV1(request.method as ProtocolMethodV1,definition,paramsRecord.body);
 if(paramsRecord.page!==undefined)parsePageRequestV1(paramsRecord.page);if(paramsRecord.resume!==undefined)parseSubscriptionResumeV1(paramsRecord.resume);
 if(definition.kind==="subscription"&&paramsRecord.resume===undefined)throw new ProtocolError("RESUME_TOKEN_INVALID",-32007);if(definition.kind!=="subscription"&&paramsRecord.resume!==undefined)throw new ProtocolError("INVALID_PARAMS",-32602);
 return {jsonrpc:"2.0",id:request.id as JsonRpcId,method:request.method as ProtocolMethodV1,params:{protocolVersion:"1",observationCursor:cursor,...(paramsRecord.idempotencyKey===undefined?{}:{idempotencyKey:paramsRecord.idempotencyKey as string}),body:body as unknown as JsonValue,...(paramsRecord.page===undefined?{}:{page:parsePageRequestV1(paramsRecord.page)}),...(paramsRecord.resume===undefined?{}:{resume:parseSubscriptionResumeV1(paramsRecord.resume)})}};
}
export function parsePageRequestV1(value:unknown):PageRequestV1{const r=exactRecord(value,["schemaVersion","limit","afterObservationCursor","continuationToken"],"INVALID_PARAMS");if(r.schemaVersion!=="1"||!Number.isSafeInteger(r.limit)||(r.limit as number)<1||(r.limit as number)>1000||(r.continuationToken!==null&&typeof r.continuationToken!=="string"))throw new ProtocolError("INVALID_PARAMS",-32602);return{schemaVersion:"1",limit:r.limit as number,afterObservationCursor:r.afterObservationCursor===null?null:parseObservationCursorV1(r.afterObservationCursor),continuationToken:r.continuationToken as string|null}}
export function parseSubscriptionResumeV1(value:unknown):SubscriptionResumeV1{const r=exactRecord(value,["schemaVersion","subscriptionId","afterObservationCursor","resumeToken"],"RESUME_TOKEN_INVALID");if(r.schemaVersion!=="1")throw new ProtocolError("UNSUPPORTED_PROTOCOL_VERSION",-32002);return{schemaVersion:"1",subscriptionId:text(r.subscriptionId),afterObservationCursor:parseObservationCursorV1(r.afterObservationCursor),resumeToken:text(r.resumeToken)}}
export function successResponse(id:JsonRpcId,method:ProtocolMethodV1,data:JsonValue,resultCursor:JsonValue|null=null,extra:{page?:PageResultV1;subscription?:SubscriptionResultV1}={}):JsonRpcSuccessV1{assertJsonValue(data);if(resultCursor!==null)assertJsonValue(resultCursor);return{jsonrpc:"2.0",id,result:{schemaVersion:"1",method,resultCursor,data,...extra}}}
export function failureResponse(id:JsonRpcId,error:unknown):JsonRpcFailureV1{const e=error instanceof ProtocolError?error:new ProtocolError("INTERNAL_ERROR",-32603);return{jsonrpc:"2.0",id,error:{code:e.rpcCode,message:e.reasonCode,data:{schemaVersion:"1",reasonCode:e.reasonCode,retryable:e.retryable,details:e.details}}}}
export function canonicalProtocolMessage(value:JsonRpcRequestV1|JsonRpcResponseV1):string{return canonicalJson(value as unknown as JsonValue)}
export function validateTransportSecurity(value:unknown):TransportSecurityMetadataV1{const r=exactRecord(value,["schemaVersion","transport","localOnly","tcpEnabled","authenticatedPrincipalId","principalRole","workspaceId","grantDigest","osIdentity","endpointPermissions"],"INVALID_PARAMS");if(r.schemaVersion!=="1"||!(["stdio","unix-socket","windows-named-pipe"] as unknown[]).includes(r.transport)||r.localOnly!==true||r.tcpEnabled!==false||!(["authority","approver","operator","worker","adapter"] as unknown[]).includes(r.principalRole))throw new ProtocolError("INVALID_PARAMS",-32602);const expected=r.transport==="stdio"?"process-inherited":r.transport==="unix-socket"?"owner-only-0600":"non-inheriting-owner-dacl";if(r.endpointPermissions!==expected)throw new ProtocolError("INVALID_PARAMS",-32602);for(const key of ["authenticatedPrincipalId","workspaceId","grantDigest","osIdentity"] as const)text(r[key]);return r as unknown as TransportSecurityMetadataV1}
