import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { SQLiteAuthority } from "../../src/sqlite-authority.js";
import { createBackup, verifyBackup } from "../../src/backup/index.js";
import { MIGRATION_0001 } from "../../src/migrations.js";
import { requireLosslessDowngrade, upgradeAuthority } from "../../src/migrations/index.js";

const setup=()=>{const root=mkdtempSync(join(tmpdir(),"horseness-c06-"));const database=join(root,"authority.sqlite"),artifacts=join(root,"artifacts");new SQLiteAuthority(database,artifacts).close();const db=new DatabaseSync(database);return{root,database,artifacts,db};};
const setupV1=()=>{const root=mkdtempSync(join(tmpdir(),"horseness-c06-v1-"));const database=join(root,"authority.sqlite"),artifacts=join(root,"artifacts"),db=new DatabaseSync(database);db.exec(MIGRATION_0001);db.prepare("INSERT INTO schema_migrations(version,name,applied_at) VALUES(1,'0001_initial_authority',?)").run(new Date().toISOString());return{root,database,artifacts,db};};
const journalMode=(db:DatabaseSync):unknown=>{const row=db.prepare("PRAGMA journal_mode").get();return row&&typeof row==="object"&&"journal_mode" in row?row.journal_mode:undefined;};

test("v1 upgrade is idempotent and the upgraded authority reopens through the normal path",()=>{const x=setupV1();try{assert.deepEqual(upgradeAuthority(x.db,x.artifacts),[1,2]);assert.deepEqual(upgradeAuthority(x.db,x.artifacts),[1,2]);x.db.close();const reopened=new SQLiteAuthority(x.database,x.artifacts);assert.deepEqual(reopened.migrationVersions(),[1,2]);assert.doesNotThrow(()=>reopened.db.prepare("SELECT count(*) FROM retention_intents").get());reopened.close();}finally{if(x.db.isOpen)x.db.close();rmSync(x.root,{recursive:true,force:true});}});
test("every v2 to v1 downgrade is major-gated",()=>{const x=setup();try{assert.throws(()=>requireLosslessDowngrade(x.db,1),/storage schema v2 cannot be downgraded to v1 in place/);x.db.prepare("INSERT INTO retention_intents(intent_id,workspace_id,digest,state,created_at) VALUES('i','w',?,'pending',?)").run("a".repeat(64),new Date().toISOString());assert.throws(()=>requireLosslessDowngrade(x.db,1),/major-version gate/);assert.doesNotThrow(()=>requireLosslessDowngrade(x.db,2));assert.throws(()=>requireLosslessDowngrade(x.db,0),/unsupported downgrade/);}finally{x.db.close();rmSync(x.root,{recursive:true,force:true});}});
test("raw chain corruption rejects before schema upcast",()=>{const x=setupV1();try{x.db.prepare("INSERT INTO streams VALUES('workspace','w','w',0,NULL,0)").run();assert.throws(()=>upgradeAuthority(x.db,x.artifacts),/raw event-chain verification failed/);assert.equal(x.db.prepare("SELECT 1 FROM schema_migrations WHERE version=2").get(),undefined);}finally{x.db.close();rmSync(x.root,{recursive:true,force:true});}});
test("conflicting and future migration ledgers reject before mutation",()=>{for(const entry of [[1,"wrong-identity"],[3,"future"]] as const){const root=mkdtempSync(join(tmpdir(),"horseness-c06-conflict-")),database=join(root,"authority.sqlite"),artifacts=join(root,"artifacts"),db=new DatabaseSync(database);try{db.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL)");db.prepare("INSERT INTO schema_migrations VALUES(?,?,?)").run(entry[0],entry[1],new Date().toISOString());assert.equal(journalMode(db),"delete");db.close();assert.throws(()=>new SQLiteAuthority(database,artifacts),entry[0]===3?/unsupported newer schema version 3/:/migration 0001 identity\/order mismatch/);const inspection=new DatabaseSync(database);assert.equal(journalMode(inspection),"delete");assert.equal(inspection.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='retention_intents'").get(),undefined);inspection.close();}finally{if(db.isOpen)db.close();rmSync(root,{recursive:true,force:true});}}});
test("backup manifest binds database and artifacts",()=>{const x=setup();try{const backup=join(x.root,"backup");const manifest=createBackup(x.db,x.artifacts,backup);const verified=verifyBackup(backup);assert.equal(verified.database.digest,manifest.database.digest);const databasePath=join(backup,verified.database.file),bytes=readFileSync(databasePath);writeFileSync(databasePath,Buffer.concat([bytes,Buffer.from("x")]));assert.throws(()=>verifyBackup(backup),/digest mismatch/);}finally{x.db.close();rmSync(x.root,{recursive:true,force:true});}});
