import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { createWorkspaceGenesis, NO_POLICY_DIGEST, sealEventEnvelope } from "@horseness/domain";
import { SQLiteAuthority } from "../../src/sqlite-authority.js";
import { createBackup, verifyBackup } from "../../src/backup/index.js";
import { MIGRATION_0001 } from "../../src/migrations.js";
import { requireLosslessDowngrade } from "../../src/migrations/index.js";

const setup=()=>{const root=mkdtempSync(join(tmpdir(),"horseness-c06-"));const database=join(root,"authority.sqlite"),artifacts=join(root,"artifacts");new SQLiteAuthority(database,artifacts).close();const db=new DatabaseSync(database);return{root,database,artifacts,db};};
const setupV1=()=>{const root=mkdtempSync(join(tmpdir(),"horseness-c06-v1-"));const database=join(root,"authority.sqlite"),artifacts=join(root,"artifacts"),db=new DatabaseSync(database);db.exec(MIGRATION_0001);db.prepare("INSERT INTO schema_migrations(version,name,applied_at) VALUES(1,'0001_initial_authority',?)").run(new Date().toISOString());return{root,database,artifacts,db};};
const journalMode=(db:DatabaseSync):unknown=>{const row=db.prepare("PRAGMA journal_mode").get();return row&&typeof row==="object"&&"journal_mode" in row?row.journal_mode:undefined;};

test("v1 upgrade is verified, idempotent, and reopens through the public factory",()=>{const x=setupV1();try{assert.throws(()=>new SQLiteAuthority(x.database,x.artifacts),/verified authority open required/);x.db.close();const upgraded=SQLiteAuthority.open(x.database,x.artifacts);assert.deepEqual(upgraded.migrationVersions(),[1,2]);upgraded.close();const reopened=SQLiteAuthority.open(x.database,x.artifacts);assert.deepEqual(reopened.migrationVersions(),[1,2]);assert.doesNotThrow(()=>reopened.db.prepare("SELECT count(*) FROM retention_intents").get());reopened.close();}finally{if(x.db.isOpen)x.db.close();rmSync(x.root,{recursive:true,force:true});}});
test("every v2 to v1 downgrade is major-gated",()=>{const x=setup();try{assert.throws(()=>requireLosslessDowngrade(x.db,1),/storage schema v2 cannot be downgraded to v1 in place/);x.db.prepare("INSERT INTO retention_intents(intent_id,workspace_id,digest,state,created_at) VALUES('i','w',?,'pending',?)").run("a".repeat(64),new Date().toISOString());assert.throws(()=>requireLosslessDowngrade(x.db,1),/major-version gate/);assert.doesNotThrow(()=>requireLosslessDowngrade(x.db,2));assert.throws(()=>requireLosslessDowngrade(x.db,0),/unsupported downgrade/);}finally{x.db.close();rmSync(x.root,{recursive:true,force:true});}});
test("semantic chain corruption rejects verified open before schema upcast",()=>{const x=setupV1();try{const genesis=createWorkspaceGenesis({workspaceId:"w",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:NO_POLICY_DIGEST,commandId:"create"});const insert=x.db.prepare("INSERT INTO events(stream_kind,workspace_id,stream_id,sequence,envelope_hash,prior_envelope_hash,event_id,idempotency_key,command_id,envelope_json,created_at) VALUES('workspace','w','w',?,?,?,?,?,?,?,?)");x.db.prepare("INSERT INTO streams VALUES('workspace','w','w',1,?,0)").run(genesis.event.envelopeHash);insert.run(1,genesis.event.envelopeHash,null,genesis.event.envelope.eventId,genesis.event.envelope.idempotencyKey,genesis.event.envelope.causationId,JSON.stringify(genesis.event),new Date().toISOString());const duplicate=sealEventEnvelope({...genesis.event.envelope,sequence:2,eventId:"duplicate",causationId:"duplicate",idempotencyKey:"duplicate",priorEnvelopeHash:genesis.event.envelopeHash});insert.run(2,duplicate.envelopeHash,genesis.event.envelopeHash,duplicate.envelope.eventId,duplicate.envelope.idempotencyKey,duplicate.envelope.causationId,JSON.stringify(duplicate),new Date().toISOString());x.db.prepare("UPDATE streams SET head_sequence=2,head_hash=? WHERE workspace_id='w'").run(duplicate.envelopeHash);x.db.close();assert.throws(()=>SQLiteAuthority.open(x.database,x.artifacts),/semantic event replay failed/);const inspection=new DatabaseSync(x.database);assert.equal(inspection.prepare("SELECT 1 FROM schema_migrations WHERE version=2").get(),undefined);inspection.close();}finally{if(x.db.isOpen)x.db.close();rmSync(x.root,{recursive:true,force:true});}});
test("dangling referenced artifact rejects verified open before schema upcast",()=>{const x=setupV1();try{const digest="a".repeat(64);x.db.prepare("INSERT INTO artifacts VALUES(?,?,?,?,?)").run(digest,1,`objects/${digest.slice(0,2)}/${digest.slice(2)}`,"application/octet-stream",new Date().toISOString());x.db.prepare("INSERT INTO artifact_pins VALUES(?,?,?)").run("pin",digest,new Date().toISOString());x.db.close();assert.throws(()=>SQLiteAuthority.open(x.database,x.artifacts),/dangling artifact/);const inspection=new DatabaseSync(x.database);assert.equal(inspection.prepare("SELECT 1 FROM schema_migrations WHERE version=2").get(),undefined);inspection.close();}finally{if(x.db.isOpen)x.db.close();rmSync(x.root,{recursive:true,force:true});}});
test("conflicting and future migration ledgers reject before mutation",()=>{for(const entry of [[1,"wrong-identity"],[3,"future"]] as const){const root=mkdtempSync(join(tmpdir(),"horseness-c06-conflict-")),database=join(root,"authority.sqlite"),artifacts=join(root,"artifacts"),db=new DatabaseSync(database);try{db.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL)");db.prepare("INSERT INTO schema_migrations VALUES(?,?,?)").run(entry[0],entry[1],new Date().toISOString());assert.equal(journalMode(db),"delete");db.close();assert.throws(()=>new SQLiteAuthority(database,artifacts),entry[0]===3?/unsupported newer schema version 3/:/migration 0001 identity\/order mismatch/);const inspection=new DatabaseSync(database);assert.equal(journalMode(inspection),"delete");assert.equal(inspection.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='retention_intents'").get(),undefined);inspection.close();}finally{if(db.isOpen)db.close();rmSync(root,{recursive:true,force:true});}}});
test("backup manifest binds database and artifacts",()=>{const x=setup();try{const backup=join(x.root,"backup");const manifest=createBackup(x.db,x.artifacts,backup);const verified=verifyBackup(backup);assert.equal(verified.database.digest,manifest.database.digest);const databasePath=join(backup,verified.database.file),bytes=readFileSync(databasePath);writeFileSync(databasePath,Buffer.concat([bytes,Buffer.from("x")]));assert.throws(()=>verifyBackup(backup),/digest mismatch/);}finally{x.db.close();rmSync(x.root,{recursive:true,force:true});}});
