import assert from "node:assert/strict";
import test from "node:test";
import { domainDigest, type JsonValue } from "@horseness/domain";
import { acquireLease } from "../../src/leases/index.js";
import { createBoundAttempt, requestAttemptCancellation } from "../../src/attempts/index.js";
import { commitLaunchIntent, createDispatchRecord, dispatchCommittedIntent, handoffCancellation, lookupDispatch, recordAuthenticatedTerminalReceipt, recordProviderHandle, recordTerminalReceipt, rehydrateDispatchRecord, requestDispatchCancellation, type DispatchEventV1, type DispatchRecordV1, type ProviderAdapterV1, type ProviderLookupResultV1 } from "../../src/dispatch/index.js";
import { fixture } from "../attempts/attempts.test.js";
import { storedCapabilities } from "../receipts/receipt-projection.test.js";

function setup(){const f=fixture(),attempt=createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1}).attempt,lease=acquireLease({attempt,current:null,leaseId:"lease",ownerId:"owner",bootId:"boot",processId:"process",authorityCursor:attempt.binding.sourceObservationCursor,now:"2026-01-01T00:00:00.000Z",expiresAt:"2026-01-01T00:10:00.000Z"}).lease!;return{f,attempt,lease,base:{attempt,lease,ownerId:"owner",fenceToken:lease.fenceToken,now:"2026-01-01T00:01:00.000Z"}};}
function adapter(lookup:ProviderLookupResultV1={status:"found",operationId:"op",handle:"handle"}){const calls={dispatch:0,lookup:0,cancel:0};const value:ProviderAdapterV1={providerId:"provider",dispatch:request=>{calls.dispatch++;return{operationId:"op",handle:"handle"}},lookup:request=>{calls.lookup++;return lookup},cancel:request=>{calls.cancel++;return{accepted:true}}};return{value,calls};}

test("durable intent strictly precedes provider side effects and duplicate dispatch is idempotent",()=>{const s=setup(),provider=adapter();try{const planned=createDispatchRecord(s.attempt);assert.throws(()=>dispatchCommittedIntent({...s.base,record:planned,adapter:provider.value}),/PROVIDER_BINDING_MISMATCH|INTENT_NOT_COMMITTED/);assert.equal(provider.calls.dispatch,0);const intent=commitLaunchIntent({...s.base,record:planned,providerId:"provider"});assert.equal(intent.phase,"intent_committed");assert.equal(provider.calls.dispatch,0);const launched=dispatchCommittedIntent({...s.base,record:intent,adapter:provider.value});assert.equal(launched.phase,"handle_recorded");assert.equal(provider.calls.dispatch,1);assert.equal(dispatchCommittedIntent({...s.base,record:launched,adapter:provider.value}),launched);assert.equal(provider.calls.dispatch,1);assert.equal(commitLaunchIntent({...s.base,record:intent,providerId:"provider"}),intent);}finally{s.f.close();}});

test("lookup found, definite absence and unsupported are deterministic and fail closed",()=>{const s=setup();try{const intent=commitLaunchIntent({...s.base,record:createDispatchRecord(s.attempt),providerId:"provider"});const found=lookupDispatch(intent,adapter().value);assert.equal(found.providerHandle,"handle");assert.equal(found.operationId,"op");const absent=lookupDispatch(intent,adapter({status:"not_found"}).value);assert.equal(absent.phase,"intent_committed");const unsupported=lookupDispatch(intent,adapter({status:"unsupported"}).value);assert.equal(unsupported.phase,"unknown_outcome");const launched=dispatchCommittedIntent({...s.base,record:intent,adapter:adapter().value});assert.equal(lookupDispatch(launched,adapter({status:"not_found"}).value).phase,"unknown_outcome");assert.throws(()=>lookupDispatch(intent,{...adapter().value,providerId:"other"}),/PROVIDER_BINDING_MISMATCH/);}finally{s.f.close();}});

test("late handles are recorded but mismatches and forged bindings fail closed",()=>{const s=setup();try{const intent=commitLaunchIntent({...s.base,record:createDispatchRecord(s.attempt),providerId:"provider"});const late=recordProviderHandle(intent,{operationId:"late-op",handle:"late-handle"});assert.equal(late.providerHandle,"late-handle");assert.throws(()=>recordProviderHandle(late,{operationId:"other",handle:"late-handle"}),/PROVIDER_HANDLE_MISMATCH/);assert.throws(()=>recordTerminalReceipt(late,{attemptId:"a",generation:1,bindingDigest:"wrong",outcome:"succeeded"}),/DISPATCH_RECEIPT_MISMATCH/);const forged={...s.attempt,bindingDigest:"wrong"};assert.throws(()=>commitLaunchIntent({...s.base,attempt:forged,record:createDispatchRecord(s.attempt),providerId:"provider"}),/DISPATCH_BINDING_MISMATCH/);}finally{s.f.close();}});

test("cancellation wins before launch and hands off after launch without duplicate calls",()=>{const s=setup(),provider=adapter();try{const planned=requestDispatchCancellation(createDispatchRecord(s.attempt));assert.equal(planned.phase,"cancel_requested");assert.throws(()=>commitLaunchIntent({...s.base,record:planned,providerId:"provider"}),/LAUNCH_CANCELLED|DUPLICATE_INTENT_MISMATCH/);assert.equal(provider.calls.dispatch,0);const intent=commitLaunchIntent({...s.base,record:createDispatchRecord(s.attempt),providerId:"provider"});const cancelled=requestDispatchCancellation(intent);assert.throws(()=>dispatchCommittedIntent({...s.base,record:cancelled,adapter:provider.value}),/DISPATCH_CANCELLED/);const handed=handoffCancellation(cancelled,provider.value);assert.equal(handed.phase,"cancel_handed_off");assert.equal(provider.calls.cancel,1);assert.equal(handoffCancellation(handed,provider.value),handed);assert.equal(provider.calls.cancel,1);const attemptCancelled=requestAttemptCancellation(s.attempt).attempt;assert.throws(()=>commitLaunchIntent({...s.base,attempt:attemptCancelled,record:createDispatchRecord(attemptCancelled),providerId:"provider"}),/LAUNCH_CANCELLED/);}finally{s.f.close();}});

test("every terminal receipt transition is idempotent and conflicts fail closed",()=>{for(const outcome of ["succeeded","failed","cancelled"] as const){const s=setup();try{const intent=commitLaunchIntent({...s.base,record:createDispatchRecord(s.attempt),providerId:"provider"});const launched=dispatchCommittedIntent({...s.base,record:intent,adapter:adapter().value});const terminal=recordTerminalReceipt(launched,{attemptId:"a",generation:1,bindingDigest:s.attempt.bindingDigest,operationId:"op",handle:"handle",outcome});assert.equal(terminal.phase,outcome);assert.equal(recordTerminalReceipt(terminal,{attemptId:"a",generation:1,bindingDigest:s.attempt.bindingDigest,operationId:"op",handle:"handle",outcome}),terminal);const other=outcome==="failed"?"succeeded":"failed";assert.throws(()=>recordTerminalReceipt(terminal,{attemptId:"a",generation:1,bindingDigest:s.attempt.bindingDigest,operationId:"op",handle:"handle",outcome:other}),/DISPATCH_RECEIPT_CONFLICT/);}finally{s.f.close();}}});

test("restart after intent uses lookup before a repeated provider dispatch",()=>{const s=setup(),provider=adapter({status:"found",operationId:"op",handle:"handle"});try{const intent=commitLaunchIntent({...s.base,record:createDispatchRecord(s.attempt),providerId:"provider"});const durable=rehydrateDispatchRecord(structuredClone(intent));assert.equal(provider.calls.dispatch,0);const recovered=lookupDispatch(durable,provider.value);assert.equal(recovered.providerHandle,"handle");assert.equal(provider.calls.lookup,1);assert.equal(provider.calls.dispatch,0);assert.throws(()=>rehydrateDispatchRecord({...structuredClone(intent),bindingDigest:"substituted"}),/DISPATCH_RECORD_DIGEST_MISMATCH/);}finally{s.f.close();}});

test("authenticated accepted receipt wins the pre-bind crash window atomically and idempotently",()=>{const stored=storedCapabilities();try{const eventCore={schemaVersion:"1" as const,ordinal:1,eventType:"LaunchIntentCommittedV1" as const,attemptId:"attempt",generation:1,bindingDigest:"binding-1"};const launchEvent:DispatchEventV1={...eventCore,eventDigest:domainDigest("horseness.dispatch-event.v1",eventCore as unknown as JsonValue)};const core:Omit<DispatchRecordV1,"recordDigest">={schemaVersion:"1",attemptId:"attempt",generation:1,bindingDigest:"binding-1",attemptDigest:"attempt-digest",phase:"intent_committed",providerId:"provider",idempotencyKey:"key-1",intentDigest:"intent-digest",operationId:null,providerHandle:null,cancellationRequested:false,events:[launchEvent]};const durable=rehydrateDispatchRecord({...core,recordDigest:domainDigest("horseness.dispatch-record.v1",core as unknown as JsonValue)});const terminal=recordAuthenticatedTerminalReceipt(durable,stored.capabilities.event,stored.capabilities.authority);assert.equal(terminal.phase,"succeeded");assert.equal(terminal.operationId,"operation-1");assert.equal(terminal.providerHandle,"handle-1");const restarted=rehydrateDispatchRecord(structuredClone(terminal));assert.equal(recordAuthenticatedTerminalReceipt(restarted,stored.capabilities.event,stored.capabilities.authority),restarted);const conflicting=storedCapabilities(1,"failed");try{assert.throws(()=>recordAuthenticatedTerminalReceipt(restarted,conflicting.capabilities.event,conflicting.capabilities.authority),/DISPATCH_RECEIPT_CONFLICT/);}finally{conflicting.close();}}finally{stored.close();}});
