import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createRunGenesis, createWorkspaceGenesis, sealEventEnvelope, type CompositeCursorV1, type ContextVersionV1 } from "@horseness/domain";
import { SQLiteAuthority, trustedAuthorityReader } from "@horseness/store-sqlite";
import { createProjectedFork, emptyForkProjection, issueForkAuthorityCapability, refreshProjectedFork, reuseProjectedFork, type ForkAuthorityContextV1 } from "../../src/forks/fork-registry.js";
import * as rootExports from "../../src/index.js";

const version=(cursor:CompositeCursorV1):ContextVersionV1=>({schemaVersion:"1",kind:"composite",observationCursor:cursor,workspaceContextEpoch:cursor.workspaceContextEpoch,runContextEpoch:cursor.runContextEpoch});
function fixture(sourceRevision=1, expectedActiveForkPinDigest:string|null=null){
  const root=mkdtempSync(join(tmpdir(),"horseness-fork-authority-"));const authority=new SQLiteAuthority(join(root,"db.sqlite"),join(root,"artifacts"));
  const workspace=createWorkspaceGenesis({workspaceId:"w",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:"pinned",commandId:"workspace"});authority.appendAtomic({commandId:"workspace",workspace:{streamKind:"workspace",workspaceId:"w",streamId:"w",expectedSequence:0,expectedEnvelopeHash:null,events:[workspace.event]}});
  const absent={schemaVersion:"1" as const,kind:"absent-run-genesis" as const,workspaceId:"w",workspaceSequence:1,workspaceEnvelopeHash:workspace.event.envelopeHash,workspaceContextEpoch:0,runId:"r",expectedRunHead:"absent" as const};const run=createRunGenesis({observationCursor:absent,initialDocument:{value:1},principalId:"p",commandId:"run"});authority.appendAtomic({commandId:"run",runGenesis:{observationCursor:absent,event:run.event}});
  const cursor=run.resultCursor;const source={schemaVersion:"1" as const,workspaceId:"w",runId:"r",observationCursor:cursor,contextVersion:version(cursor),canonicalRevision:sourceRevision,canonicalStateHash:`state-${sourceRevision}`,dependencyJoinSnapshotDigest:"join",scope:{schemaVersion:"1" as const,workspaceId:"w",runId:"r",taskId:"t",roots:["/a"]},pinnedPolicyDigest:"pinned"};const authorization={schemaVersion:"1" as const,workspaceId:"w",runId:"r",observationCursor:cursor,contextVersion:version(cursor),principalId:"p",grantDigest:"grant",revoked:false,pinnedPolicyDigest:"pinned",currentPolicyDigest:"current",quotaId:"q",quotaDigest:"quota",quotaAvailable:true,expectedActiveForkPinDigest};
  const put=(name:string,state:typeof source|typeof authorization)=>authority.putSnapshot({workspaceId:"w",streamKind:"run",streamId:"r",sequence:cursor.runSequence,envelopeHash:cursor.runEnvelopeHash,projectionName:name,projectionVersion:"1",state});put("fork-source",source);put("fork-authorization",authorization);
  return {root,authority,cursor,source,authorization,capability:()=>issueForkAuthorityCapability(trustedAuthorityReader(authority),{workspaceId:"w",runId:"r"}),close(){authority.close();rmSync(root,{recursive:true,force:true});}};
}

test("caller-built fork context cannot mint authority",()=>{const f=fixture();try{const forged:ForkAuthorityContextV1={source:{...f.source,canonicalRevision:999},authorization:{...f.authorization}};assert.throws(()=>createProjectedFork(emptyForkProjection(),"fork",forged as never),/FORK_AUTHORITY_UNAUTHENTICATED/);assert.equal("authenticated" in forged.source,false);}finally{f.close();}});

test("trusted SQLite issuance creates and reuses a fork",()=>{const f=fixture();try{let state=emptyForkProjection();const created=createProjectedFork(state,"fork",f.capability());state=created.state;f.authority.putSnapshot({workspaceId:"w",streamKind:"run",streamId:"r",sequence:f.cursor.runSequence,envelopeHash:f.cursor.runEnvelopeHash,projectionName:"fork-authorization",projectionVersion:"1",state:{...f.authorization,expectedActiveForkPinDigest:created.pin.forkPinDigest}});assert.equal(reuseProjectedFork(state,"fork",f.capability()).forkPinDigest,created.pin.forkPinDigest);}finally{f.close();}});

test("trusted refresh enforces persisted CAS and immutable lineage",()=>{const first=fixture();try{let state=emptyForkProjection();const created=createProjectedFork(state,"fork",first.capability());state=created.state;first.authority.putSnapshot({workspaceId:"w",streamKind:"run",streamId:"r",sequence:first.cursor.runSequence,envelopeHash:first.cursor.runEnvelopeHash,projectionName:"fork-source",projectionVersion:"1",state:{...first.source,canonicalRevision:2,canonicalStateHash:"state-2"}});first.authority.putSnapshot({workspaceId:"w",streamKind:"run",streamId:"r",sequence:first.cursor.runSequence,envelopeHash:first.cursor.runEnvelopeHash,projectionName:"fork-authorization",projectionVersion:"1",state:{...first.authorization,expectedActiveForkPinDigest:created.pin.forkPinDigest}});const refreshed=refreshProjectedFork(state,"fork",first.capability());assert.equal(refreshed.pin.core.parentForkPinDigest,created.pin.forkPinDigest);assert.equal(refreshed.pin.core.pinVersion,2);}finally{first.close();}});

test("stale or substituted persisted authority fails closed",()=>{const f=fixture();try{f.authority.putSnapshot({workspaceId:"w",streamKind:"run",streamId:"r",sequence:f.cursor.runSequence,envelopeHash:f.cursor.runEnvelopeHash,projectionName:"fork-authorization",projectionVersion:"1",state:{...f.authorization,workspaceId:"other"}});assert.throws(f.capability,/CAPABILITY_SCOPE_MISMATCH/);const next=sealEventEnvelope({schemaVersion:"1",streamKind:"run",workspaceId:"w",streamId:"r",sequence:2,eventId:"advance",eventType:"ForkCreatedV1",principalId:"p",causationId:"advance",correlationId:"advance",idempotencyKey:"advance",priorEnvelopeHash:f.cursor.runEnvelopeHash,payload:{eventType:"ForkCreatedV1",workspaceId:"w",runId:"r",forkPinDigest:"fork"}});f.authority.appendAtomic({commandId:"advance",run:{streamKind:"run",workspaceId:"w",streamId:"r",expectedSequence:1,expectedEnvelopeHash:f.cursor.runEnvelopeHash,events:[next]}});assert.throws(f.capability,/trusted projection is stale/);}finally{f.close();}});

test("root package exports trusted fork issuer and consumers",()=>{assert.equal(typeof rootExports.issueForkAuthorityCapability,"function");assert.equal(typeof rootExports.createProjectedFork,"function");assert.equal(typeof rootExports.emptyForkProjection,"function");});
