import assert from "node:assert/strict";
import test from "node:test";
import type { CompositeCursorV1, ContextVersionV1 } from "@horseness/domain";
import { createProjectedFork, emptyForkProjection, refreshProjectedFork, reuseProjectedFork, type ForkAuthorityContextV1 } from "../../src/forks/fork-registry.js";
import * as rootExports from "../../src/index.js";

const cursor = (workspaceEnvelopeHash="wh", runEnvelopeHash="rh"): CompositeCursorV1 => ({schemaVersion:"1",kind:"composite",workspaceId:"w",workspaceSequence:2,workspaceEnvelopeHash,workspaceContextEpoch:1,runId:"r",runSequence:3,runEnvelopeHash,runContextEpoch:2});
const version = (observationCursor:CompositeCursorV1):ContextVersionV1 => ({schemaVersion:"1",kind:"composite",observationCursor,workspaceContextEpoch:observationCursor.workspaceContextEpoch,runContextEpoch:observationCursor.runContextEpoch});
function context(overrides:{source?:Partial<ForkAuthorityContextV1["source"]>;authorization?:Partial<ForkAuthorityContextV1["authorization"]>}={}):ForkAuthorityContextV1 {
  const sourceCursor=cursor(); const authorizationCursor=cursor("wh-current","rh-current");
  return {source:{schemaVersion:"1",authenticated:true,workspaceId:"w",runId:"r",observationCursor:sourceCursor,contextVersion:version(sourceCursor),canonicalRevision:1,canonicalStateHash:"state",dependencyJoinSnapshotDigest:"join",scope:{schemaVersion:"1",workspaceId:"w",runId:"r",taskId:"t",roots:["/a"]},pinnedPolicyDigest:"pinned",...overrides.source},authorization:{schemaVersion:"1",authenticated:true,workspaceId:"w",runId:"r",observationCursor:authorizationCursor,contextVersion:version(authorizationCursor),principalId:"p",grantDigest:"grant",revoked:false,pinnedPolicyDigest:"pinned",currentPolicyDigest:"current",quotaId:"q",quotaDigest:"quota",quotaAvailable:true,expectedActiveForkPinDigest:null,...overrides.authorization}};
}

test("source and current authorization observations remain distinct and authenticated",()=>{let state=emptyForkProjection();const created=createProjectedFork(state,"fork",context());state=created.state;assert.notDeepEqual(created.pin.core.sourceObservationCursor,context().authorization.observationCursor);assert.ok(state.authoritySnapshotsByPin.get(created.pin.forkPinDigest));for(const mutation of [{source:{authenticated:false}},{source:{observationCursor:{...cursor(),runId:"other"}}},{authorization:{authenticated:false}},{authorization:{workspaceId:"other"}},{authorization:{revoked:true}},{authorization:{pinnedPolicyDigest:"substituted"}},{authorization:{currentPolicyDigest:""}},{authorization:{quotaAvailable:false}}] as const)assert.throws(()=>createProjectedFork(emptyForkProjection(),"bad",context(mutation)),/FORK_|CAPABILITY|CONTEXT_VERSION/);});

test("reuse requires the identical authenticated snapshots",()=>{let state=emptyForkProjection();const created=createProjectedFork(state,"fork",context());state=created.state;const reusable=context({authorization:{expectedActiveForkPinDigest:created.pin.forkPinDigest}});assert.equal(reuseProjectedFork(state,"fork",reusable).forkPinDigest,created.pin.forkPinDigest);assert.throws(()=>reuseProjectedFork(state,"fork",context({authorization:{expectedActiveForkPinDigest:created.pin.forkPinDigest,quotaDigest:"changed"}})),/FORK_REUSE_STALE/);assert.throws(()=>reuseProjectedFork(state,"fork",context({source:{canonicalRevision:2},authorization:{expectedActiveForkPinDigest:created.pin.forkPinDigest}})),/FORK_REUSE_STALE/);});

test("authorized refresh enforces CAS and immutable lineage",()=>{let state=emptyForkProjection();const created=createProjectedFork(state,"fork",context());state=created.state;assert.throws(()=>refreshProjectedFork(state,"fork",context()),/FORK_REFRESH_CAS_MISMATCH/);assert.throws(()=>refreshProjectedFork(state,"fork",context({authorization:{expectedActiveForkPinDigest:"fabricated"}})),/FORK_REFRESH_CAS_MISMATCH/);const refreshed=refreshProjectedFork(state,"fork",context({source:{canonicalRevision:2,canonicalStateHash:"state2"},authorization:{expectedActiveForkPinDigest:created.pin.forkPinDigest}}));assert.equal(refreshed.pin.core.parentForkPinDigest,created.pin.forkPinDigest);assert.equal(refreshed.pin.core.refreshesForkPinDigest,created.pin.forkPinDigest);assert.deepEqual(refreshed.pin.core.ancestry,[created.pin.forkPinDigest]);assert.equal(refreshed.state.pins.get(created.pin.forkPinDigest)?.core.canonicalRevision,1);});

test("root package exports fork authority surfaces",()=>{assert.equal(typeof rootExports.createProjectedFork,"function");assert.equal(typeof rootExports.emptyForkProjection,"function");});
