import { createHash, createPublicKey, verify } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const argument = process.argv.indexOf("--version");
const version = argument >= 0 ? process.argv[argument + 1] : undefined;
if (version !== "0.0.0-compat.1") throw new Error("COMPAT_TRAIN_VERSION_UNSUPPORTED");
const fixtureRoot = resolve(root, "tests/fixtures/compat-train");
const canonical = (value) => {
  if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number") return String(value);
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;
};
const sha = (bytes) => createHash("sha256").update(bytes).digest("hex");
const signed = JSON.parse(await readFile(resolve(fixtureRoot, "release-manifest.v1.json"), "utf8"));
const trust = JSON.parse(await readFile(resolve(fixtureRoot, "trust-root.v1.json"), "utf8"));
const provenance = JSON.parse(await readFile(resolve(fixtureRoot, "provenance.v1.json"), "utf8"));
const artifact = await readFile(resolve(fixtureRoot, `compat-train-${version}.tgz`));
const built = await readFile(resolve(fixtureRoot, `build/compat-train-${version}.tgz`));
const graph = await readFile(resolve(fixtureRoot, "dependency-graph.v1.json"));
if (!artifact.equals(built)) throw new Error("COMPAT_TRAIN_NOT_REPRODUCIBLE");
if (signed.manifest.version !== version || signed.manifest.artifacts.length !== 1 || signed.manifest.artifacts[0].sha256 !== sha(artifact) || signed.manifest.artifacts[0].bytes !== artifact.length) throw new Error("COMPAT_TRAIN_ARTIFACT_MISMATCH");
if (signed.manifest.dependencyGraphDigest !== sha(graph)) throw new Error("COMPAT_TRAIN_GRAPH_MISMATCH");
if (signed.manifestDigest !== sha(`horseness.release-manifest.v1\0${canonical(signed.manifest)}`)) throw new Error("COMPAT_TRAIN_MANIFEST_DIGEST_MISMATCH");
const delegation = trust.delegations.find((value) => value.keyId === signed.keyId);
if (!delegation) throw new Error("COMPAT_TRAIN_DELEGATION_MISSING");
const delegationCore = { keyId: delegation.keyId, publicKeyPem: delegation.publicKeyPem, validFromSequence: delegation.validFromSequence, validThroughSequence: delegation.validThroughSequence };
if (!verify(null, Buffer.from(canonical(delegationCore)), createPublicKey(trust.rootPublicKeyPem), Buffer.from(delegation.rootSignature, "base64"))) throw new Error("COMPAT_TRAIN_DELEGATION_INVALID");
if (!verify(null, Buffer.from(canonical(signed.manifest)), createPublicKey(delegation.publicKeyPem), Buffer.from(signed.signature, "base64"))) throw new Error("COMPAT_TRAIN_SIGNATURE_INVALID");
const packed = JSON.parse(artifact.toString("utf8"));
for (const required of ["database.json", "journal.json", "daemon.json", "cli.json"]) if (typeof packed.files[required] !== "string") throw new Error("COMPAT_TRAIN_BEHAVIOR_MISSING");
const sourceDigest = sha(Buffer.from(canonical(packed.files)));
if (provenance.schema !== "horseness.compat-train-provenance.v1" || provenance.version !== version || provenance.sourceDigest !== sourceDigest || provenance.artifactDigest !== sha(artifact) || provenance.releaseManifestDigest !== signed.manifestDigest || provenance.signingProvenance !== "fixture-ed25519-project-delegation") throw new Error("COMPAT_TRAIN_PROVENANCE_MISMATCH");
process.stdout.write(`${JSON.stringify({ artifactDigest: sha(artifact), manifestDigest: signed.manifestDigest, provenance: provenance.signingProvenance, schema: "horseness.compat-train-verify-result.v1", sourceDigest, version })}\n`);
