import { domainDigest, DomainError, type CompositeCursorV1, type JsonValue } from "@horseness/domain";
import { isBoundAttempt, type BoundAttemptV1 } from "../attempts/attempts.js";
export type LeaseTransitionCodeV1="LEASE_ACQUIRED"|"LEASE_RENEWED"|"LEASE_EXPIRED"|"LEASE_RELEASED"|"LEASE_STALE"|"LEASE_BUSY";
export interface LeaseFenceV1 {readonly schemaVersion:"1";readonly attemptId:string;readonly generation:number;readonly leaseId:string;readonly ownerId:string;readonly bootId:string;readonly processId:string;readonly fenceToken:number;readonly acquiredAt:string;readonly expiresAt:string;readonly durationMs:number;readonly authorityCursor:CompositeCursorV1;readonly bindingDigest:string;readonly leaseDigest:string}
export interface LeaseTransitionResultV1 {readonly code:LeaseTransitionCodeV1;readonly lease:LeaseFenceV1|null}
const leases=new WeakSet<object>();
function timestamp(value:string):number{const parsed=Date.parse(value);if(!Number.isFinite(parsed)||new Date(parsed).toISOString()!==value)throw new DomainError("LEASE_TIME_INVALID");return parsed;}
function seal(core:Omit<LeaseFenceV1,"leaseDigest">):LeaseFenceV1{const lease=Object.freeze({...core,leaseDigest:domainDigest("horseness.lease-fence.v1",core as unknown as JsonValue)});leases.add(lease);return lease;}
export function isLeaseFence(value:LeaseFenceV1):boolean{const{leaseDigest,...core}=value;return leases.has(value)&&leaseDigest===domainDigest("horseness.lease-fence.v1",core as unknown as JsonValue);}
function validateCore(core:Omit<LeaseFenceV1,"leaseDigest">):void{const acquired=timestamp(core.acquiredAt),expires=timestamp(core.expiresAt);if(core.schemaVersion!=="1"||!core.attemptId||core.generation<1||!core.leaseId||!core.ownerId||!core.bootId||!core.processId||!Number.isSafeInteger(core.fenceToken)||core.fenceToken<1||!Number.isSafeInteger(core.durationMs)||core.durationMs<1||expires-acquired!==core.durationMs||core.authorityCursor.kind!=="composite"||!core.bindingDigest)throw new DomainError("LEASE_SCHEMA_INVALID");}
export function rehydrateLeaseFence(value:LeaseFenceV1):LeaseFenceV1{if(value===null||typeof value!=="object"||Array.isArray(value))throw new DomainError("LEASE_SCHEMA_INVALID");const{leaseDigest,...core}=value;validateCore(core);if(leaseDigest!==domainDigest("horseness.lease-fence.v1",core as unknown as JsonValue))throw new DomainError("LEASE_DIGEST_MISMATCH");return seal(structuredClone(core));}
export function acquireLease(input:{attempt:BoundAttemptV1;current:LeaseFenceV1|null;leaseId:string;ownerId:string;bootId:string;processId:string;authorityCursor:CompositeCursorV1;now:string;expiresAt:string}):LeaseTransitionResultV1{if(!isBoundAttempt(input.attempt)||input.attempt.outcome!=="live")throw new DomainError("LEASE_ATTEMPT_INVALID");const now=timestamp(input.now),expires=timestamp(input.expiresAt);if(expires<=now||!input.leaseId||!input.ownerId||!input.bootId||!input.processId)throw new DomainError("LEASE_TIME_INVALID");if(input.current&&!isLeaseFence(input.current))throw new DomainError("LEASE_UNTRUSTED");if(input.current&&timestamp(input.current.expiresAt)>now)return{code:"LEASE_BUSY",lease:input.current};const token=input.current?.fenceToken??0;return{code:"LEASE_ACQUIRED",lease:seal({schemaVersion:"1",attemptId:input.attempt.attemptId,generation:input.attempt.generation,leaseId:input.leaseId,ownerId:input.ownerId,bootId:input.bootId,processId:input.processId,fenceToken:token+1,acquiredAt:input.now,expiresAt:input.expiresAt,durationMs:expires-now,authorityCursor:structuredClone(input.authorityCursor),bindingDigest:input.attempt.bindingDigest})};}
export function renewLease(input:{lease:LeaseFenceV1;ownerId:string;fenceToken:number;now:string;expiresAt:string}):LeaseTransitionResultV1{if(!isLeaseFence(input.lease)||input.ownerId!==input.lease.ownerId||input.fenceToken!==input.lease.fenceToken)return{code:"LEASE_STALE",lease:input.lease};const now=timestamp(input.now),expires=timestamp(input.expiresAt);if(now>=timestamp(input.lease.expiresAt))return{code:"LEASE_EXPIRED",lease:null};if(expires<=now)throw new DomainError("LEASE_TIME_INVALID");const{leaseDigest:_,...core}=input.lease;return{code:"LEASE_RENEWED",lease:seal({...core,acquiredAt:input.now,expiresAt:input.expiresAt,durationMs:expires-now})};}
export function expireLease(lease:LeaseFenceV1,now:string):LeaseTransitionResultV1{if(!isLeaseFence(lease))throw new DomainError("LEASE_UNTRUSTED");return timestamp(now)>=timestamp(lease.expiresAt)?{code:"LEASE_EXPIRED",lease:null}:{code:"LEASE_BUSY",lease};}
export function assertLeaseFence(attempt:BoundAttemptV1,lease:LeaseFenceV1,ownerId:string,fenceToken:number,now:string):void{if(!isBoundAttempt(attempt)||!isLeaseFence(lease)||lease.attemptId!==attempt.attemptId||lease.generation!==attempt.generation||lease.bindingDigest!==attempt.bindingDigest||lease.ownerId!==ownerId||lease.fenceToken!==fenceToken||timestamp(now)>=timestamp(lease.expiresAt))throw new DomainError("LEASE_FENCE_STALE");}
