import assert from "node:assert/strict";
import test from "node:test";
import { createBoundAttempt, recordAttemptOutcome } from "../../src/attempts/index.js";
import { commitLaunchIntent, createDispatchRecord, dispatchCommittedIntent, recordTerminalReceipt, type ProviderAdapterV1, type ProviderLookupResultV1 } from "../../src/dispatch/index.js";
import { acquireLease } from "../../src/leases/index.js";
import { assertRecoveryGenerationRefresh, auditLateHandle, recoverCancellation, recoverDispatch } from "../../src/recovery/index.js";
import { fixture } from "../attempts/attempts.test.js";

const now="2026-01-01T00:00:00.000Z",expiresAt="2026-01-01T00:10:00.000Z";
interface RecoveryFixture {source:ReturnType<typeof fixture>;attempt:ReturnType<typeof createBoundAttempt>["attempt"];lease:NonNullable<ReturnType<typeof acquireLease>["lease"]>;record:ReturnType<typeof createDispatchRecord>;state:{lookup:ProviderLookupResultV1;cancelAccepted:boolean;dispatches:number};adapter:ProviderAdapterV1}
function setup(dispatch=false):RecoveryFixture{const source=fixture(),attempt=createBoundAttempt({...source,taskId:"t",attemptId:"a",generation:1}).attempt,lease=acquireLease({attempt,current:null,leaseId:"lease-1",ownerId:"worker-1",now,expiresAt}).lease!;let record=commitLaunchIntent({record:createDispatchRecord(attempt),attempt,lease,ownerId:"worker-1",fenceToken:lease.fenceToken,now,providerId:"provider"});const state:{lookup:ProviderLookupResultV1;cancelAccepted:boolean;dispatches:number}={lookup:{status:"not_found"},cancelAccepted:true,dispatches:0};const adapter:ProviderAdapterV1={providerId:"provider",dispatch:()=>{state.dispatches++;return{operationId:"op-1"}},lookup:()=>state.lookup,cancel:()=>({accepted:state.cancelAccepted})};if(dispatch)record=dispatchCommittedIntent({record,attempt,lease,ownerId:"worker-1",fenceToken:lease.fenceToken,now,adapter});return{source,attempt,lease,record,state,adapter};}
const recover=(f:RecoveryFixture)=>recoverDispatch({record:f.record,attempt:f.attempt,lease:f.lease,ownerId:"worker-1",fenceToken:f.lease.fenceToken,now,adapter:f.adapter});

test("restart lookup found adopts once and repeated replay deterministically reattaches",()=>{const f=setup(true);try{f.state.lookup={status:"found",operationId:"op-1",handle:"handle-1"};const first=recover(f);assert.equal(first.action.classification,"ADOPT");assert.equal(first.record.bindingDigest,f.attempt.bindingDigest);const second=recoverDispatch({record:first.record,attempt:f.attempt,lease:f.lease,ownerId:"worker-1",fenceToken:f.lease.fenceToken,now,adapter:f.adapter});assert.equal(second.action.classification,"REATTACH");assert.equal(second.record.events.length,first.record.events.length);assert.equal(f.state.dispatches,1);}finally{f.source.close();}});

test("not-found is relaunchable only before a provider operation is known",()=>{const absent=setup();try{assert.equal(recover(absent).action.classification,"RELAUNCH_IDEMPOTENT");}finally{absent.source.close();}const handed=setup(true);try{const result=recover(handed);assert.equal(result.action.classification,"DUPLICATE_RISK_REQUIRED");assert.equal(result.action.duplicateRisk,true);assert.equal(result.record.phase,"unknown_outcome");}finally{handed.source.close();}});

test("unsupported and thrown lookup are unknown duplicate-risk outcomes",()=>{const unsupported=setup();try{unsupported.state.lookup={status:"unsupported"};const result=recover(unsupported);assert.equal(result.action.lookupOutcome,"unsupported");assert.equal(result.action.classification,"DUPLICATE_RISK_REQUIRED");const replay=recoverDispatch({record:result.record,attempt:unsupported.attempt,lease:unsupported.lease,ownerId:"worker-1",fenceToken:unsupported.lease.fenceToken,now,adapter:unsupported.adapter});assert.equal(replay.action.classification,"DUPLICATE_RISK_REQUIRED");assert.equal(replay.record,result.record);}finally{unsupported.source.close();}const unknown=setup();try{unknown.adapter.lookup=()=>{throw new Error("provider unavailable")};const result=recover(unknown);assert.equal(result.action.lookupOutcome,"unknown");assert.equal(result.action.classification,"UNKNOWN_OUTCOME");assert.equal(result.record,unknown.record);}finally{unknown.source.close();}});

test("cancellation propagates once and cancellation/provider race remains reconcilable",()=>{const accepted=setup(true);try{const first=recoverCancellation({record:accepted.record,attempt:accepted.attempt,lease:accepted.lease,ownerId:"worker-1",fenceToken:accepted.lease.fenceToken,now,adapter:accepted.adapter});assert.equal(first.action.classification,"CANCEL_HANDED_OFF");const second=recoverDispatch({record:first.record,attempt:accepted.attempt,lease:accepted.lease,ownerId:"worker-1",fenceToken:accepted.lease.fenceToken,now,adapter:accepted.adapter});assert.equal(second.action.classification,"CANCEL_HANDED_OFF");}finally{accepted.source.close();}const rejected=setup(true);try{rejected.state.cancelAccepted=false;assert.equal(recoverCancellation({record:rejected.record,attempt:rejected.attempt,lease:rejected.lease,ownerId:"worker-1",fenceToken:rejected.lease.fenceToken,now,adapter:rejected.adapter}).action.classification,"CANCEL_RECONCILE");}finally{rejected.source.close();}});

test("terminal selection makes late handles audit-only and immutable",()=>{const f=setup(true);try{const terminal=recordTerminalReceipt(f.record,{attemptId:"a",generation:1,bindingDigest:f.attempt.bindingDigest,operationId:"op-1",outcome:"succeeded"});const late=auditLateHandle({record:terminal,attempt:f.attempt,operationId:"op-late",handle:"late"});assert.equal(late.action.classification,"TERMINAL_AUDIT_ONLY");assert.equal(late.action.duplicateRisk,true);assert.equal(late.record,terminal);assert.equal(recoverDispatch({record:terminal,attempt:f.attempt,lease:f.lease,ownerId:"worker-1",fenceToken:f.lease.fenceToken,now,adapter:f.adapter}).action.classification,"TERMINAL_AUDIT_ONLY");}finally{f.source.close();}});

test("recovery rejects stale fences and substituted immutable binding",()=>{const f=setup();try{assert.throws(()=>recoverDispatch({record:f.record,attempt:f.attempt,lease:f.lease,ownerId:"worker-1",fenceToken:f.lease.fenceToken+1,now,adapter:f.adapter}),/LEASE_FENCE_STALE/);const forged={...f.attempt,bindingDigest:"other"};assert.throws(()=>recoverDispatch({record:f.record,attempt:forged,lease:f.lease,ownerId:"worker-1",fenceToken:f.lease.fenceToken,now,adapter:f.adapter}),/DISPATCH_BINDING_MISMATCH|RECOVERY_STATE_UNTRUSTED/);}finally{f.source.close();}});

test("retry recovery rejects reuse of the prior generation binding and ForkPin",()=>{const first=setup();const secondSource=fixture();try{const prior=recordAttemptOutcome(first.attempt,"failed").attempt;const candidate=createBoundAttempt({...secondSource,taskId:"t",attemptId:"a",generation:1}).attempt;assert.throws(()=>assertRecoveryGenerationRefresh(prior,candidate),/RECOVERY_GENERATION_NOT_REFRESHED/);}finally{first.source.close();secondSource.close();}});
