import assert from "node:assert/strict";
import test from "node:test";
import {attemptContextBindingDigest,contextManifestCoreDigest,sealAttemptReceipt,sealForkPin,sealProposal,type CompositeCursorV1,type ContextManifestCoreV1} from "@horseness/domain";
import {METHOD_REGISTRY_V1,methodDefinition,successResponse,type JsonRpcRequestV1,type JsonRpcResponseV1,type SubscriptionResultV1} from "@horseness/protocol";
import {CoordinatorClientV1,SdkError,WorkerClientV1,coordinatorCursorMatchesV1,type AuthorizedProtocolTransportV1,type OpaqueCredentialReferenceV1,type WorkerBindingV1} from "../src/index.js";

const cursor:CompositeCursorV1={schemaVersion:"1",kind:"composite",workspaceId:"w",workspaceSequence:2,workspaceEnvelopeHash:"wh",workspaceContextEpoch:1,runId:"r",runSequence:3,runEnvelopeHash:"rh",runContextEpoch:1};
const contextVersion={schemaVersion:"1",kind:"composite",workspaceContextEpoch:1,runContextEpoch:1,observationCursor:cursor} as const;
const fork=sealForkPin({schemaVersion:"1",forkId:"fork",pinVersion:1,workspaceId:"w",runId:"r",parentForkPinDigest:null,refreshesForkPinDigest:null,canonicalRevision:0,canonicalStateHash:"state",canonicalizerVersion:"jcs-v1",hashVersion:"sha256-v1",sourceObservationCursor:cursor,sourceContextVersion:contextVersion,dependencyJoinSnapshotDigest:"join",deltaAuthorityScopeDigest:"scope",pinnedPolicyDigest:"policy",ancestry:[],createdByPrincipalId:"worker",createdByGrantDigest:"grant"});
const manifest:ContextManifestCoreV1={schemaVersion:"1",workspaceId:"w",runId:"r",attemptId:"a",generation:1,forkPinDigest:fork.forkPinDigest,sourceObservationCursor:cursor,sourceContextVersion:contextVersion,authorizationObservationCursor:cursor,authorizationContextVersion:contextVersion,authorizationOverlayV1:{policyDigest:"policy",grantDigest:"grant",quotaDigest:"quota",result:"allowed"},canonicalRevision:0,canonicalStateHash:"state",canonicalizerVersion:"jcs-v1",hashVersion:"sha256-v1",sources:[],rendererVersion:"1",omissions:[],selectedBytes:0,byteBudget:100,tokenizerMetadata:{schemaVersion:"1",tokenizerId:"bytes",tokenizerVersion:"1",estimatedTokens:0},renderedOutputDigest:"rendered"};
const contextBinding={schemaVersion:"1",attemptId:"a",generation:1,forkPinDigest:fork.forkPinDigest,contextManifestCoreDigest:contextManifestCoreDigest(manifest),sourceObservationCursor:cursor,sourceContextVersion:contextVersion,authorizationObservationCursor:cursor,authorizationContextVersion:contextVersion,providerIdempotencyKey:"provider-key",expectedReceiptSchemaVersion:"1",allowedProducerPrincipalId:"worker",allowedProducerGrantDigest:"grant"} as const;
const binding:WorkerBindingV1={schemaVersion:"1",workspaceId:"w",runId:"r",taskId:"t",attemptId:"a",generation:1,forkPin:fork,manifest,contextBinding,providerId:"provider",providerIdempotencyKeyDigest:"provider-key-digest",observationCursor:cursor,dispatchId:"dispatch"};
const credential:OpaqueCredentialReferenceV1={schemaVersion:"1",kind:"keychain",reference:"horseness.worker.grant",scope:{workspaceId:"w",adapterId:"adapter",purpose:"worker-grant"}};

class FakeTransport implements AuthorizedProtocolTransportV1 {
  readonly calls:JsonRpcRequestV1[]=[];
  responder:(request:JsonRpcRequestV1)=>JsonRpcResponseV1=()=>{throw new Error("missing responder")};
  async request(request:JsonRpcRequestV1,received:OpaqueCredentialReferenceV1):Promise<JsonRpcResponseV1>{assert.deepEqual(received,credential);this.calls.push(request);return this.responder(request);}
}
function localResult(request:JsonRpcRequestV1,value:Readonly<Record<string,unknown>>,subscription?:SubscriptionResultV1):JsonRpcResponseV1 {
  const result={schemaVersion:"1",resultType:request.method,value} as const;
  return successResponse(request.id,request.method,result as unknown as never,null,subscription===undefined?{}:{subscription});
}
function worker(transport:FakeTransport):WorkerClientV1{return new WorkerClientV1(new CoordinatorClientV1(transport,credential),binding);}

test("retains immutable binding and maps bound context through protocol registry",async()=>{const transport=new FakeTransport();transport.responder=request=>successResponse(request.id,request.method,{schemaVersion:"1",resultType:request.method,value:manifest} as unknown as never);const client=worker(transport);assert.throws(()=>{(client.binding as {attemptId:string}).attemptId="other";},TypeError);assert.deepEqual(await client.readBoundContext(),manifest);const call=transport.calls[0]!;assert.equal(call.method,"context.get.v1");assert.equal(methodDefinition(call.method)?.scope,"attempt");assert.deepEqual((call.params.body as {workspaceId:string;runId:string;taskId:string;attemptId:string;generation:number}),{schemaVersion:"1",workspaceId:"w",runId:"r",taskId:"t",attemptId:"a",generation:1,input:(call.params.body as {input:unknown}).input});});

test("deep-clones and freezes every nested worker binding identity",()=>{const mutable=structuredClone(binding);const client=new WorkerClientV1(new CoordinatorClientV1(new FakeTransport(),credential),mutable);mutable.forkPin.core.ancestry.push("substituted");mutable.manifest.authorizationOverlayV1.policyDigest="substituted";mutable.contextBinding.sourceObservationCursor.runEnvelopeHash="substituted";assert.deepEqual(client.binding,binding);assert.throws(()=>{client.binding.forkPin.core.ancestry.push("mutation");},TypeError);assert.throws(()=>{client.binding.manifest.authorizationOverlayV1.policyDigest="mutation";},TypeError);});

test("covers every registry cursor requirement and all five cursor variants",()=>{const variants={"absent-workspace-genesis":{schemaVersion:"1",kind:"absent-workspace-genesis",workspaceId:"w",expectedWorkspaceHead:"absent"},"workspace-only":{schemaVersion:"1",kind:"workspace-only",workspaceId:"w",workspaceSequence:1,workspaceEnvelopeHash:"wh",workspaceContextEpoch:0},"absent-run-genesis":{schemaVersion:"1",kind:"absent-run-genesis",workspaceId:"w",workspaceSequence:1,workspaceEnvelopeHash:"wh",workspaceContextEpoch:0,runId:"r",expectedRunHead:"absent"},"run-only":{schemaVersion:"1",kind:"run-only",workspaceId:"w",runId:"r",runSequence:1,runEnvelopeHash:"rh",runContextEpoch:0},composite:cursor} as const;const allowed={"absent-workspace":["absent-workspace-genesis"],workspace:["workspace-only"],"absent-run":["absent-run-genesis"],run:["run-only","composite"],composite:["composite"]} as const;for(const definition of METHOD_REGISTRY_V1)for(const [kind,value] of Object.entries(variants))assert.equal(coordinatorCursorMatchesV1(definition.cursor,value),allowed[definition.cursor].includes(kind as never),`${definition.method}:${kind}`);for(const requirement of Object.keys(allowed) as (keyof typeof allowed)[])for(const [kind,value] of Object.entries(variants))assert.equal(coordinatorCursorMatchesV1(requirement,value),allowed[requirement].includes(kind as never),`${requirement}:${kind}`);});

test("maps artifact, receipt, proposal, and own cancellation methods",async()=>{const transport=new FakeTransport();transport.responder=request=>{if(request.method==="artifact.publish.v1")return localResult(request,{outcomeId:"o",status:"accepted",artifactId:"art",publishedDigest:"digest",immutableReference:"ref"});if(request.method==="dispatch.cancel.v1")return localResult(request,{outcomeId:"o",status:"accepted",dispatchId:"dispatch",cancelState:"requested",adapterAcknowledged:false});return successResponse(request.id,request.method,{schemaVersion:"1",resultType:request.method,value:{schemaVersion:"1",resultType:"RunCommandResultV1",commandId:"command",resultCursor:cursor,resultContextVersion:contextVersion}} as unknown as never);};const client=worker(transport);await client.publishArtifact({operationId:"publish",artifactId:"art",mediaType:"text/plain",contentDigest:"digest",byteLength:1,storageReference:"ref"});const receipt=sealAttemptReceipt({schemaVersion:"1",workspaceId:"w",runId:"r",taskId:"t",attemptId:"a",generation:1,attemptContextBindingDigest:attemptContextBindingDigest(contextBinding),contextManifestCoreDigest:contextManifestCoreDigest(manifest),forkPinDigest:fork.forkPinDigest,providerId:"provider",providerOperationId:"op",providerIdempotencyKeyDigest:"provider-key-digest",producerPrincipalId:"worker",producerGrantDigest:"grant",adapterId:"adapter",adapterVersion:"1",hostId:"host",hostVersion:"1",outcome:"failed",startedAt:"2026-01-01T00:00:00Z",finishedAt:"2026-01-01T00:00:01Z",outputDigest:null,evidence:[],provenance:{kind:"test"},nonce:"nonce"});await client.submitReceipt(receipt,"receipt-key");const proposal=sealProposal({schemaVersion:"1",workspaceId:"w",runId:"r",authorPrincipalId:"worker",authorGrantDigest:"grant",attemptId:"a",receiptDigests:[receipt.receiptDigest],forkPinDigest:fork.forkPinDigest,deltaAuthorityScopeDigest:"scope",baseRevision:0,baseStateHash:"state",canonicalizerVersion:"jcs-v1",hashVersion:"sha256-v1",proposalSealingObservationCursor:cursor,proposalSealingContextVersion:contextVersion,operations:[],evidenceClaims:[],pinnedPolicyDigest:"policy",currentPolicyDigest:"policy",nonce:"proposal",predecessorProposalDigest:null,predecessorReason:null});await client.submitProposal(proposal,"proposal-key");await client.cancelOwnAttempt("stop");assert.deepEqual(transport.calls.map(call=>call.method),["artifact.publish.v1","receipt.submit.v1","proposal.submit.v1","dispatch.cancel.v1"]);});

test("resumes decision subscriptions and surfaces every admission outcome",async()=>{const transport=new FakeTransport();const proposal=sealProposal({schemaVersion:"1",workspaceId:"w",runId:"r",authorPrincipalId:"worker",authorGrantDigest:"grant",attemptId:"a",receiptDigests:[],forkPinDigest:fork.forkPinDigest,deltaAuthorityScopeDigest:"scope",baseRevision:0,baseStateHash:"state",canonicalizerVersion:"jcs-v1",hashVersion:"sha256-v1",proposalSealingObservationCursor:cursor,proposalSealingContextVersion:contextVersion,operations:[],evidenceClaims:[],pinnedPolicyDigest:"policy",currentPolicyDigest:"policy",nonce:"proposal-2",predecessorProposalDigest:null,predecessorReason:null});const states=["accepted","rejected","conflicted","quarantined","approval_required"] as const;transport.responder=request=>localResult(request,{outcomeId:"o",status:"accepted",subscriptionId:"sub",events:states.map(state=>({state,proposalId:proposal.proposalId,proposalDigest:proposal.proposalDigest})),resumeToken:"next"},{schemaVersion:"1",subscriptionId:"sub",resumeToken:"next",afterObservationCursor:cursor,emittedResultCursor:null});const client=worker(transport);const first=await client.subscribeDecisions(proposal,"subscribe");const second=await client.subscribeDecisions(proposal,"subscribe",first.resume);assert.deepEqual(second.events.map(event=>event.state),states);assert.deepEqual(transport.calls[1]!.params.resume,first.resume);});

test("rejects unverified, cross-scope, and regressed subscription resumes",async()=>{const transport=new FakeTransport();const proposal=sealProposal({schemaVersion:"1",workspaceId:"w",runId:"r",authorPrincipalId:"worker",authorGrantDigest:"grant",attemptId:"a",receiptDigests:[],forkPinDigest:fork.forkPinDigest,deltaAuthorityScopeDigest:"scope",baseRevision:0,baseStateHash:"state",canonicalizerVersion:"jcs-v1",hashVersion:"sha256-v1",proposalSealingObservationCursor:cursor,proposalSealingContextVersion:contextVersion,operations:[],evidenceClaims:[],pinnedPolicyDigest:"policy",currentPolicyDigest:"policy",nonce:"resume-negative",predecessorProposalDigest:null,predecessorReason:null});transport.responder=request=>localResult(request,{outcomeId:"o",status:"accepted",subscriptionId:"sub",events:[{state:"accepted",proposalId:proposal.proposalId,proposalDigest:proposal.proposalDigest}],resumeToken:"next"},{schemaVersion:"1",subscriptionId:"sub",resumeToken:"next",afterObservationCursor:cursor,emittedResultCursor:null});const client=worker(transport);await assert.rejects(client.subscribeDecisions(proposal,"subscribe",{schemaVersion:"1",subscriptionId:"sub",resumeToken:"forged",afterObservationCursor:cursor}),error=>error instanceof SdkError&&error.code==="SCOPE_SUBSTITUTION");const first=await client.subscribeDecisions(proposal,"subscribe");await assert.rejects(client.subscribeDecisions(proposal,"subscribe",{...first.resume,afterObservationCursor:{...cursor,runId:"other"}}),error=>error instanceof SdkError&&error.code==="SCOPE_SUBSTITUTION");await assert.rejects(client.subscribeDecisions(proposal,"subscribe",{...first.resume,afterObservationCursor:{...cursor,runSequence:2}}),error=>error instanceof SdkError&&error.code==="SCOPE_SUBSTITUTION");});

test("rejects scope substitution and secret-shaped credentials before transport",async()=>{assert.throws(()=>new CoordinatorClientV1(new FakeTransport(),{schemaVersion:"1",kind:"keychain",reference:"Bearer actual-secret",scope:{workspaceId:"w",adapterId:"adapter",purpose:"worker-grant"}}),error=>error instanceof SdkError&&error.code==="CREDENTIAL_NOT_OPAQUE");assert.throws(()=>new WorkerClientV1(new CoordinatorClientV1(new FakeTransport(),credential),{...binding,runId:"other"}),error=>error instanceof SdkError&&error.code==="INVALID_BINDING");const transport=new FakeTransport();const client=worker(transport);const receipt=sealAttemptReceipt({schemaVersion:"1",workspaceId:"w",runId:"r",taskId:"other",attemptId:"a",generation:1,attemptContextBindingDigest:attemptContextBindingDigest(contextBinding),contextManifestCoreDigest:contextManifestCoreDigest(manifest),forkPinDigest:fork.forkPinDigest,providerId:"provider",providerOperationId:"op",providerIdempotencyKeyDigest:"provider-key-digest",producerPrincipalId:"worker",producerGrantDigest:"grant",adapterId:"adapter",adapterVersion:"1",hostId:"host",hostVersion:"1",outcome:"failed",startedAt:"2026-01-01T00:00:00Z",finishedAt:"2026-01-01T00:00:01Z",outputDigest:null,evidence:[],provenance:{kind:"test"},nonce:"nonce-other"});await assert.rejects(client.submitReceipt(receipt,"key"),error=>error instanceof SdkError&&error.code==="SCOPE_SUBSTITUTION");assert.equal(transport.calls.length,0);});
