import assert from "node:assert/strict";
import test from "node:test";
import { sealAttemptReceipt, type AttemptGenerationStateV1 } from "@horseness/domain";
import * as orchestrator from "../../src/index.js";
import { emptyReceiptProjection, projectAuthenticatedReceipt, recordExplicitTaskCancellation, registerReceiptGeneration, setRetryPermitted, type AuthenticatedReceiptInputV1 } from "../../src/index.js";

const generation=(number:number,state:AttemptGenerationStateV1["state"]="acknowledged"):AttemptGenerationStateV1=>({attemptId:"attempt",generation:number,state,bindingDigest:`binding-${number}`,idempotencyKeyDigest:`key-${number}`,providerHandle:`handle-${number}`,terminalEventSequence:null,findingCodes:[]});
const event=(generation:number,outcome:"succeeded"|"failed"|"cancelled",sequence:number,overrides:Partial<AuthenticatedReceiptInputV1>={}):AuthenticatedReceiptInputV1=>{
 const receipt=sealAttemptReceipt({schemaVersion:"1",workspaceId:"w",runId:"r",taskId:"task",attemptId:"attempt",generation,attemptContextBindingDigest:`binding-${generation}`,contextManifestCoreDigest:`manifest-${generation}`,forkPinDigest:`fork-${generation}`,providerId:"provider",providerOperationId:`operation-${generation}`,providerIdempotencyKeyDigest:`key-${generation}`,producerPrincipalId:"adapter",producerGrantDigest:"grant",adapterId:"adapter",adapterVersion:"1",hostId:"host",hostVersion:"1",outcome,startedAt:"2026-08-12T00:00:00Z",finishedAt:"2026-08-12T00:00:01Z",outputDigest:outcome==="succeeded"?"output":null,evidence:[],provenance:{},nonce:`nonce-${generation}-${outcome}`});
 return {eventSequence:sequence,eventDigest:`event-${sequence}`,authenticated:true,authenticatedPrincipalId:"adapter",authorizedGrantDigest:"grant",providerHandle:`handle-${generation}`,binding:{attemptId:"attempt",generation,digest:`binding-${generation}`,contextManifestCoreDigest:`manifest-${generation}`,forkPinDigest:`fork-${generation}`,providerId:"provider",providerOperationId:`operation-${generation}`,providerIdempotencyKeyDigest:`key-${generation}`,allowedProducerPrincipalId:"adapter",allowedProducerGrantDigest:"grant"},receipt,...overrides};
};
const state=(...generations:number[])=>generations.reduce((value,item)=>registerReceiptGeneration(value,generation(item)),emptyReceiptProjection("attempt"));

test("earliest success event wins across generations and later outcomes are audit-only",()=>{let value=state(1,2);value=projectAuthenticatedReceipt(value,event(2,"succeeded",20));assert.equal(value.resolution?.winningGeneration,2);value=projectAuthenticatedReceipt(value,event(1,"succeeded",30));assert.equal(value.resolution?.winningGeneration,2);assert.ok(value.findings.includes("LATE_GENERATION_RECEIPT"));});
test("success wins over failure without waiting for exhausted generations",()=>{let value=state(1,2);value=projectAuthenticatedReceipt(value,event(1,"failed",10));assert.equal(value.resolution,null);value=projectAuthenticatedReceipt(value,event(2,"succeeded",11));assert.equal(value.resolution?.resolution,"succeeded");});
test("failure waits while retry is permitted and resolves when exhausted",()=>{let value=setRetryPermitted(state(1),1,true);value=projectAuthenticatedReceipt(value,event(1,"failed",10));assert.equal(value.resolution,null);value=setRetryPermitted(value,1,false);value=projectAuthenticatedReceipt(value,event(1,"failed",10));assert.equal(value.resolution,null);value=recordExplicitTaskCancellation(value,12);assert.equal(value.resolution?.resolution,"cancelled");});
test("all exhausted failures resolve only after every live generation terminates",()=>{let value=state(1,2);value=projectAuthenticatedReceipt(value,event(1,"failed",10));assert.equal(value.resolution,null);value=projectAuthenticatedReceipt(value,event(2,"failed",12));assert.equal(value.resolution?.resolution,"failed");});
test("unknown and duplicate-risk generations prevent premature resolution",()=>{let value=registerReceiptGeneration(state(1),generation(2,"unknown_outcome"));value=projectAuthenticatedReceipt(value,event(1,"failed",10));assert.equal(value.resolution,null);assert.equal(value.generations.get(2)?.state,"unknown_outcome");});
test("explicit cancellation wins before exhausted failure and remains immutable",()=>{let value=state(1);value=recordExplicitTaskCancellation(value,5,"task");assert.equal(value.resolution?.resolution,"cancelled");value=projectAuthenticatedReceipt(value,event(1,"succeeded",8));assert.equal(value.resolution?.resolution,"cancelled");assert.ok(value.findings.includes("LATE_GENERATION_RECEIPT"));});
test("binding grant operation idempotency and handle substitutions fail closed",()=>{for(const changed of [event(1,"succeeded",4,{authenticatedPrincipalId:"other"}),event(1,"succeeded",4,{binding:{...event(1,"succeeded",4).binding,providerOperationId:"other"}})])assert.throws(()=>projectAuthenticatedReceipt(state(1),changed),/RECEIPT_GRANT_MISMATCH|RECEIPT_OPERATION_MISMATCH/);let value=registerReceiptGeneration(emptyReceiptProjection("attempt"),{...generation(1),providerHandle:"expected"});value=projectAuthenticatedReceipt(value,event(1,"succeeded",4,{providerHandle:"other"}));assert.equal(value.resolution,null);assert.ok(value.findings.includes("CONFLICTING_PROVIDER_HANDLE"));});
test("same receipt is idempotent and conflicting terminal receipt is audit-only",()=>{let value=state(1);const first=event(1,"failed",7);value=projectAuthenticatedReceipt(value,first);value=projectAuthenticatedReceipt(value,first);assert.ok(value.findings.includes("DUPLICATE_RECEIPT"));const conflict=event(1,"succeeded",8);value=projectAuthenticatedReceipt(value,conflict);assert.ok(value.findings.includes("RECEIPT_TERMINAL_CONFLICT"));assert.equal(value.outcomes.get(1)?.outcome,"failed");});
test("package root exposes only authenticated receipt projection",()=>{assert.equal("projectReceipt" in orchestrator,false);assert.equal(orchestrator.projectAuthenticatedReceipt,projectAuthenticatedReceipt);});
test("package-root receipt projection rejects inputs missing authentication evidence",()=>{const input=event(1,"succeeded",4);const {binding: _binding,...withoutBinding}=input;assert.throws(()=>orchestrator.projectAuthenticatedReceipt(state(1),withoutBinding as AuthenticatedReceiptInputV1));const {authorizedGrantDigest: _grant,...withoutGrant}=input;assert.throws(()=>orchestrator.projectAuthenticatedReceipt(state(1),withoutGrant as AuthenticatedReceiptInputV1));const {authenticatedPrincipalId: _principal,...withoutPrincipal}=input;assert.throws(()=>orchestrator.projectAuthenticatedReceipt(state(1),withoutPrincipal as AuthenticatedReceiptInputV1));});
