import { domainDigest, DomainError, type JsonValue } from "@horseness/domain";
import { assertImmutableBinding, isBoundAttempt, type BoundAttemptV1 } from "../attempts/attempts.js";
import { assertLeaseFence, type LeaseFenceV1 } from "../leases/leases.js";

export type ProviderLookupResultV1 =
  | { readonly status: "found"; readonly operationId: string; readonly handle: string }
  | { readonly status: "not_found" }
  | { readonly status: "unsupported" };
export interface ProviderDispatchRequestV1 { readonly providerId:string;readonly workspaceId:string;readonly runId:string;readonly taskId:string;readonly attemptId:string;readonly generation:number;readonly bindingDigest:string;readonly idempotencyKey:string;readonly intentDigest:string }
export interface ProviderLookupRequestV1 { readonly providerId:string;readonly attemptId:string;readonly generation:number;readonly bindingDigest:string;readonly idempotencyKey:string;readonly operationId:string|null }
export interface ProviderCancelRequestV1 extends ProviderLookupRequestV1 { readonly handle:string|null }
export interface ProviderAdapterV1 {
 readonly providerId:string;
 dispatch(request:ProviderDispatchRequestV1):{readonly operationId:string;readonly handle?:string};
 lookup(request:ProviderLookupRequestV1):ProviderLookupResultV1;
 cancel(request:ProviderCancelRequestV1):{readonly accepted:boolean};
}
export type DispatchPhaseV1="planned"|"intent_committed"|"dispatched"|"handle_recorded"|"cancel_requested"|"cancel_handed_off"|"reconciliation_required"|"unknown_outcome"|"succeeded"|"failed"|"cancelled";
export type DispatchEventTypeV1="LaunchIntentCommittedV1"|"ProviderDispatchBoundV1"|"ProviderHandleRecordedV1"|"CancellationRequestedV1"|"CancellationHandedOffV1"|"DispatchLookupNotFoundV1"|"DispatchLookupUnsupportedV1"|"DispatchReconciliationRequiredV1"|"DispatchTerminalReceiptRecordedV1";
export interface DispatchEventV1 {readonly schemaVersion:"1";readonly ordinal:number;readonly eventType:DispatchEventTypeV1;readonly attemptId:string;readonly generation:number;readonly bindingDigest:string;readonly eventDigest:string}
export interface DispatchRecordV1 {readonly schemaVersion:"1";readonly attemptId:string;readonly generation:number;readonly bindingDigest:string;readonly attemptDigest:string;readonly phase:DispatchPhaseV1;readonly providerId:string|null;readonly idempotencyKey:string|null;readonly intentDigest:string|null;readonly operationId:string|null;readonly providerHandle:string|null;readonly cancellationRequested:boolean;readonly events:readonly DispatchEventV1[];readonly recordDigest:string}
const records=new WeakSet<object>();
const terminal=(phase:DispatchPhaseV1)=>phase==="succeeded"||phase==="failed"||phase==="cancelled";
function seal(core:Omit<DispatchRecordV1,"recordDigest">):DispatchRecordV1{const record=Object.freeze({...core,events:Object.freeze([...core.events]),recordDigest:domainDigest("horseness.dispatch-record.v1",core as unknown as JsonValue)});records.add(record);return record;}
export function isDispatchRecord(value:DispatchRecordV1):boolean{if(!records.has(value))return false;const{recordDigest,...core}=value;return recordDigest===domainDigest("horseness.dispatch-record.v1",core as unknown as JsonValue);}
export function rehydrateDispatchRecord(value:DispatchRecordV1):DispatchRecordV1{const{recordDigest,...core}=value;if(recordDigest!==domainDigest("horseness.dispatch-record.v1",core as unknown as JsonValue))throw new DomainError("DISPATCH_RECORD_DIGEST_MISMATCH");if(core.schemaVersion!=="1"||core.generation<1||!core.attemptId||!core.bindingDigest||!core.attemptDigest||core.events.some((item,index)=>item.ordinal!==index+1||item.attemptId!==core.attemptId||item.generation!==core.generation||item.bindingDigest!==core.bindingDigest||item.eventDigest!==domainDigest("horseness.dispatch-event.v1",{schemaVersion:item.schemaVersion,ordinal:item.ordinal,eventType:item.eventType,attemptId:item.attemptId,generation:item.generation,bindingDigest:item.bindingDigest} as JsonValue)))throw new DomainError("DISPATCH_RECORD_INVALID");return seal(core);}
function event(record:DispatchRecordV1,eventType:DispatchEventTypeV1):DispatchEventV1{const core={schemaVersion:"1" as const,ordinal:record.events.length+1,eventType,attemptId:record.attemptId,generation:record.generation,bindingDigest:record.bindingDigest};return Object.freeze({...core,eventDigest:domainDigest("horseness.dispatch-event.v1",core as unknown as JsonValue)});}
function evolve(record:DispatchRecordV1,changes:Partial<Omit<DispatchRecordV1,"schemaVersion"|"attemptId"|"generation"|"bindingDigest"|"attemptDigest"|"events"|"recordDigest">>,eventType?:DispatchEventTypeV1):DispatchRecordV1{assertRecord(record);const{recordDigest:_,...core}=record;return seal({...core,...changes,events:eventType?[...record.events,event(record,eventType)]:record.events});}
function assertRecord(record:DispatchRecordV1):void{if(!isDispatchRecord(record))throw new DomainError("DISPATCH_RECORD_UNTRUSTED");}
export function createDispatchRecord(attempt:BoundAttemptV1):DispatchRecordV1{if(!isBoundAttempt(attempt)||attempt.outcome!=="live")throw new DomainError("DISPATCH_ATTEMPT_INVALID");return seal({schemaVersion:"1",attemptId:attempt.attemptId,generation:attempt.generation,bindingDigest:attempt.bindingDigest,attemptDigest:attempt.attemptDigest,phase:"planned",providerId:null,idempotencyKey:null,intentDigest:null,operationId:null,providerHandle:null,cancellationRequested:false,events:[]});}
export function assertDispatchBinding(record:DispatchRecordV1,attempt:BoundAttemptV1):void{assertRecord(record);if(!isBoundAttempt(attempt)||record.attemptId!==attempt.attemptId||record.generation!==attempt.generation||record.bindingDigest!==attempt.bindingDigest||record.attemptDigest!==attempt.attemptDigest)throw new DomainError("DISPATCH_BINDING_MISMATCH");assertImmutableBinding(attempt,attempt);}
function fence(input:{record:DispatchRecordV1;attempt:BoundAttemptV1;lease:LeaseFenceV1;ownerId:string;fenceToken:number;now:string}):void{assertDispatchBinding(input.record,input.attempt);assertLeaseFence(input.attempt,input.lease,input.ownerId,input.fenceToken,input.now);}
export function commitLaunchIntent(input:{record:DispatchRecordV1;attempt:BoundAttemptV1;lease:LeaseFenceV1;ownerId:string;fenceToken:number;now:string;providerId:string}):DispatchRecordV1{fence(input);if(!input.providerId)throw new DomainError("PROVIDER_ID_INVALID");if(input.record.phase!=="planned"){if(input.record.providerId===input.providerId)return input.record;throw new DomainError("DUPLICATE_INTENT_MISMATCH");}if(input.attempt.cancellation!=="none"||input.record.cancellationRequested)throw new DomainError("LAUNCH_CANCELLED");const idempotencyKey=domainDigest("horseness.provider-idempotency.v1",{attemptId:input.attempt.attemptId,generation:input.attempt.generation,bindingDigest:input.attempt.bindingDigest} as JsonValue);const intentDigest=domainDigest("horseness.launch-intent.v1",{providerId:input.providerId,idempotencyKey,attemptDigest:input.attempt.attemptDigest,leaseDigest:input.lease.leaseDigest} as JsonValue);return evolve(input.record,{phase:"intent_committed",providerId:input.providerId,idempotencyKey,intentDigest},"LaunchIntentCommittedV1");}
function adapterFor(record:DispatchRecordV1,adapter:ProviderAdapterV1):void{if(record.providerId!==adapter.providerId||!record.idempotencyKey||!record.intentDigest)throw new DomainError("PROVIDER_BINDING_MISMATCH");}
export function dispatchCommittedIntent(input:{record:DispatchRecordV1;attempt:BoundAttemptV1;lease:LeaseFenceV1;ownerId:string;fenceToken:number;now:string;adapter:ProviderAdapterV1}):DispatchRecordV1{fence(input);adapterFor(input.record,input.adapter);if(input.record.cancellationRequested)throw new DomainError("DISPATCH_CANCELLED");if(input.record.operationId)return input.record;if(input.record.phase!=="intent_committed")throw new DomainError("INTENT_NOT_COMMITTED");const result=input.adapter.dispatch({providerId:input.adapter.providerId,workspaceId:input.attempt.workspaceId,runId:input.attempt.runId,taskId:input.attempt.taskId,attemptId:input.attempt.attemptId,generation:input.attempt.generation,bindingDigest:input.attempt.bindingDigest,idempotencyKey:input.record.idempotencyKey!,intentDigest:input.record.intentDigest!});if(!result.operationId||result.handle!==undefined&&!result.handle)throw new DomainError("PROVIDER_DISPATCH_INVALID");let next=evolve(input.record,{phase:"dispatched",operationId:result.operationId},"ProviderDispatchBoundV1");if(result.handle!==undefined)next=evolve(next,{phase:"handle_recorded",providerHandle:result.handle},"ProviderHandleRecordedV1");return next;}
export function recordProviderHandle(record:DispatchRecordV1,input:{operationId:string;handle:string}):DispatchRecordV1{assertRecord(record);if(!input.operationId||!input.handle)throw new DomainError("PROVIDER_HANDLE_INVALID");if(record.operationId&&record.operationId!==input.operationId||record.providerHandle&&record.providerHandle!==input.handle)throw new DomainError("PROVIDER_HANDLE_MISMATCH");if(record.providerHandle===input.handle)return record;if(record.phase==="planned")throw new DomainError("HANDLE_PRE_INTENT");return evolve(record,{operationId:record.operationId??input.operationId,providerHandle:input.handle,phase:terminal(record.phase)?record.phase:"handle_recorded"},"ProviderHandleRecordedV1");}
export function lookupDispatch(record:DispatchRecordV1,adapter:ProviderAdapterV1):DispatchRecordV1{assertRecord(record);adapterFor(record,adapter);if(record.phase==="planned")throw new DomainError("LOOKUP_PRE_INTENT");const result=adapter.lookup({providerId:adapter.providerId,attemptId:record.attemptId,generation:record.generation,bindingDigest:record.bindingDigest,idempotencyKey:record.idempotencyKey!,operationId:record.operationId});if(result.status==="found")return recordProviderHandle(record,result);if(result.status==="not_found"){if(record.operationId||record.providerHandle)return evolve(record,{phase:"unknown_outcome"},"DispatchReconciliationRequiredV1");return evolve(record,{phase:"intent_committed"},"DispatchLookupNotFoundV1");}return evolve(record,{phase:"unknown_outcome"},"DispatchLookupUnsupportedV1");}
export function requestDispatchCancellation(record:DispatchRecordV1):DispatchRecordV1{assertRecord(record);if(terminal(record.phase)||record.cancellationRequested)return record;if(record.phase==="planned")return evolve(record,{phase:"cancel_requested",cancellationRequested:true},"CancellationRequestedV1");return evolve(record,{phase:"cancel_requested",cancellationRequested:true},"CancellationRequestedV1");}
export function handoffCancellation(record:DispatchRecordV1,adapter:ProviderAdapterV1):DispatchRecordV1{assertRecord(record);adapterFor(record,adapter);if(!record.cancellationRequested)throw new DomainError("CANCELLATION_NOT_REQUESTED");if(record.phase==="cancel_handed_off")return record;const result=adapter.cancel({providerId:adapter.providerId,attemptId:record.attemptId,generation:record.generation,bindingDigest:record.bindingDigest,idempotencyKey:record.idempotencyKey!,operationId:record.operationId,handle:record.providerHandle});return result.accepted?evolve(record,{phase:"cancel_handed_off"},"CancellationHandedOffV1"):evolve(record,{phase:"reconciliation_required"},"DispatchReconciliationRequiredV1");}
export function recordTerminalReceipt(record:DispatchRecordV1,input:{attemptId:string;generation:number;bindingDigest:string;operationId?:string;handle?:string;outcome:"succeeded"|"failed"|"cancelled"}):DispatchRecordV1{assertRecord(record);if(input.attemptId!==record.attemptId||input.generation!==record.generation||input.bindingDigest!==record.bindingDigest||input.operationId!==undefined&&record.operationId!==input.operationId||input.handle!==undefined&&record.providerHandle!==null&&record.providerHandle!==input.handle)throw new DomainError("DISPATCH_RECEIPT_MISMATCH");if(record.phase==="planned")throw new DomainError("RECEIPT_PRE_INTENT");if(terminal(record.phase)){if(record.phase===input.outcome)return record;throw new DomainError("DISPATCH_RECEIPT_CONFLICT");}let next=record;if(input.handle!==undefined)next=recordProviderHandle(next,{operationId:input.operationId??record.operationId??"receipt",handle:input.handle});return evolve(next,{phase:input.outcome},"DispatchTerminalReceiptRecordedV1");}
