import {spawn} from "node:child_process";
import {realpath} from "node:fs/promises";
import {isAbsolute,relative,resolve} from "node:path";
import type {AttemptReceiptEnvelopeV1} from "@horseness/domain";
import type {AdapterCapabilitiesV1,AdapterCancelRequestV1,AdapterLaunchRequestV1,AdapterOperationResultV1,AdapterReconcileRequestV1,AdapterResumeRequestV1,BoundAdapterOperationV1,DoctorProbeResultV1,WorkerAdapterV1,WorkerReturnV1} from "@horseness/protocol";

export const ADAPTER_KIT_PACKAGE="@horseness/adapter-kit" as const;
export class AdapterKitError extends Error{constructor(readonly code:string,message:string){super(message);this.name="AdapterKitError"}}
const fail=(code:string,message:string):never=>{throw new AdapterKitError(code,message)};
const plain=(value:unknown):value is Record<string,unknown>=>typeof value==="object"&&value!==null&&!Array.isArray(value)&&Object.getPrototypeOf(value)===Object.prototype;
const exact=(value:unknown,keys:readonly string[],code:string):Record<string,unknown>=>{if(!plain(value))return fail(code,"expected plain object");const actual=Object.keys(value).sort(),wanted=[...keys].sort();if(actual.length!==wanted.length||actual.some((key,index)=>key!==wanted[index]))return fail(code,"unexpected object fields");return value};
const text=(value:unknown,code:string):string=>typeof value==="string"&&value.length>0?value:fail(code,"expected non-empty string");
const digest=(value:unknown,code:string):string=>{const result=text(value,code);return /^[A-Za-z0-9][A-Za-z0-9:._-]{2,255}$/.test(result)?result:fail(code,"invalid digest/reference")};

export interface CredentialReferenceV1{readonly schemaVersion:"1";readonly kind:"keychain"|"environment-reference"|"host-reference";readonly reference:string;readonly scope:{readonly workspaceId:string;readonly adapterId:string;readonly purpose:string}}
export function parseCredentialReferenceV1(value:unknown):CredentialReferenceV1{const record=exact(value,["schemaVersion","kind","reference","scope"],"CREDENTIAL_REFERENCE_INVALID");if(record.schemaVersion!=="1"||!(["keychain","environment-reference","host-reference"] as unknown[]).includes(record.kind))return fail("CREDENTIAL_REFERENCE_INVALID","unsupported credential reference");const scope=exact(record.scope,["workspaceId","adapterId","purpose"],"CREDENTIAL_REFERENCE_INVALID");const reference=digest(record.reference,"CREDENTIAL_REFERENCE_INVALID");if(/(?:[\s=]|bearer|token|secret|password|passwd|api[-_]?key|private[-_]?key|credential|sk[-_]|gh[pousr]_|xox[baprs]-|-----BEGIN)/iu.test(reference))return fail("CREDENTIAL_REFERENCE_INVALID","reference resembles secret material");return Object.freeze({schemaVersion:"1",kind:record.kind as CredentialReferenceV1["kind"],reference,scope:Object.freeze({workspaceId:text(scope.workspaceId,"CREDENTIAL_REFERENCE_INVALID"),adapterId:text(scope.adapterId,"CREDENTIAL_REFERENCE_INVALID"),purpose:text(scope.purpose,"CREDENTIAL_REFERENCE_INVALID")})})}

export interface AdapterBindingGuardV1{assert(operation:BoundAdapterOperationV1):void;readonly binding:BoundAdapterOperationV1}
const BINDING_KEYS=["schemaVersion","workspaceId","runId","taskId","attemptId","generation","forkPinDigest","contextManifestCoreDigest","attemptContextBindingDigest","providerIdempotencyKeyDigest","attemptCapability"] as const;
export function parseBoundAdapterOperationV1(value:unknown):BoundAdapterOperationV1{const r=exact(value,BINDING_KEYS,"BINDING_INVALID");if(r.schemaVersion!=="1"||!Number.isSafeInteger(r.generation)||(r.generation as number)<1)return fail("BINDING_INVALID","invalid binding version/generation");return Object.freeze({schemaVersion:"1",workspaceId:text(r.workspaceId,"BINDING_INVALID"),runId:text(r.runId,"BINDING_INVALID"),taskId:text(r.taskId,"BINDING_INVALID"),attemptId:text(r.attemptId,"BINDING_INVALID"),generation:r.generation as number,forkPinDigest:digest(r.forkPinDigest,"BINDING_INVALID"),contextManifestCoreDigest:digest(r.contextManifestCoreDigest,"BINDING_INVALID"),attemptContextBindingDigest:digest(r.attemptContextBindingDigest,"BINDING_INVALID"),providerIdempotencyKeyDigest:digest(r.providerIdempotencyKeyDigest,"BINDING_INVALID"),attemptCapability:digest(r.attemptCapability,"BINDING_INVALID")})}
export function createBindingGuard(binding:BoundAdapterOperationV1):AdapterBindingGuardV1{const retained=parseBoundAdapterOperationV1(binding);return Object.freeze({binding:retained,assert(operation:BoundAdapterOperationV1){const candidate=Object.fromEntries(BINDING_KEYS.map(key=>[key,operation[key]]));const parsed=parseBoundAdapterOperationV1(candidate);for(const key of BINDING_KEYS)if(parsed[key]!==retained[key])fail("BINDING_SUBSTITUTED",`immutable binding field changed: ${key}`)}})}

export type InstallContributionV1={readonly schemaVersion:"1";readonly kind:"file"|"directory"|"command"|"skill"|"plugin"|"mcp";readonly contributionId:string;readonly relativePath:string;readonly contentDigest:string;readonly sourceArtifactDigest:string;readonly mode:"read-only"|"executable";readonly hostScope:string};
export function parseInstallContributionV1(value:unknown):InstallContributionV1{const r=exact(value,["schemaVersion","kind","contributionId","relativePath","contentDigest","sourceArtifactDigest","mode","hostScope"],"INSTALL_CONTRIBUTION_INVALID");if(r.schemaVersion!=="1"||!(["file","directory","command","skill","plugin","mcp"] as unknown[]).includes(r.kind)||!(["read-only","executable"] as unknown[]).includes(r.mode))return fail("INSTALL_CONTRIBUTION_INVALID","unsupported contribution");const path=text(r.relativePath,"INSTALL_CONTRIBUTION_INVALID");if(isAbsolute(path)||path.split(/[\\/]/u).some(part=>part===""||part==="."||part===".."))return fail("INSTALL_CONTRIBUTION_INVALID","path must be normalized and relative");return Object.freeze({schemaVersion:"1",kind:r.kind as InstallContributionV1["kind"],contributionId:text(r.contributionId,"INSTALL_CONTRIBUTION_INVALID"),relativePath:path,contentDigest:digest(r.contentDigest,"INSTALL_CONTRIBUTION_INVALID"),sourceArtifactDigest:digest(r.sourceArtifactDigest,"INSTALL_CONTRIBUTION_INVALID"),mode:r.mode as InstallContributionV1["mode"],hostScope:text(r.hostScope,"INSTALL_CONTRIBUTION_INVALID")})}

export function parseDoctorProbeResultV1(value:unknown):DoctorProbeResultV1{const r=exact(value,["schemaVersion","checks","restartRequired"],"DOCTOR_RESULT_INVALID");if(r.schemaVersion!=="1"||typeof r.restartRequired!=="boolean"||!Array.isArray(r.checks))return fail("DOCTOR_RESULT_INVALID","invalid doctor result");const seen=new Set<string>();const checks=r.checks.map(item=>{const c=exact(item,["code","status","evidenceDigest"],"DOCTOR_RESULT_INVALID"),code=text(c.code,"DOCTOR_RESULT_INVALID");if(seen.has(code)||!(["ok","warning","error"] as unknown[]).includes(c.status)||!(c.evidenceDigest===null||typeof c.evidenceDigest==="string"))return fail("DOCTOR_RESULT_INVALID","invalid or duplicate doctor check");seen.add(code);return Object.freeze({code,status:c.status as "ok"|"warning"|"error",evidenceDigest:c.evidenceDigest as string|null})});return Object.freeze({schemaVersion:"1",checks:Object.freeze(checks),restartRequired:r.restartRequired})}

export interface SecureProcessSpecV1{readonly executable:string;readonly argv:readonly string[];readonly cwd:string;readonly executableRoots:readonly string[];readonly cwdRoots:readonly string[];readonly env:Readonly<Record<string,string>>;readonly envAllowlist:readonly string[];readonly outputLimitBytes:number;readonly redactions:readonly string[];readonly timeoutMs:number}
export interface SecureProcessResultV1{readonly exitCode:number|null;readonly signal:string|null;readonly stdout:string;readonly stderr:string;readonly stdoutTruncated:boolean;readonly stderrTruncated:boolean}
const SECRET_KEY=/(?:^|_)(?:TOKEN|SECRET|PASSWORD|PASS|API_KEY|PRIVATE_KEY|CREDENTIAL)(?:_|$)/iu;
async function confined(path:string,roots:readonly string[],code:string):Promise<string>{const actual=await realpath(resolve(path));for(const root of roots){const base=await realpath(resolve(root)),rel=relative(base,actual);if(rel===""||(!rel.startsWith("..")&&!isAbsolute(rel)))return actual}return fail(code,`${path} escapes configured roots`)}
const redact=(input:string,patterns:readonly string[]):string=>patterns.reduce((value,pattern)=>pattern.length===0?value:value.split(pattern).join("[REDACTED]"),input);
export async function runSecureProcess(spec:SecureProcessSpecV1):Promise<SecureProcessResultV1>{if(!Array.isArray(spec.argv)||spec.argv.some(value=>typeof value!=="string")||!Number.isSafeInteger(spec.outputLimitBytes)||spec.outputLimitBytes<0||!Number.isSafeInteger(spec.timeoutMs)||spec.timeoutMs<1)fail("PROCESS_SPEC_INVALID","invalid process spec");const executable=await confined(spec.executable,spec.executableRoots,"EXECUTABLE_OUTSIDE_ROOT"),cwd=await confined(spec.cwd,spec.cwdRoots,"CWD_OUTSIDE_ROOT");const allowed=new Set(spec.envAllowlist),env:Record<string,string>={};for(const [key,value] of Object.entries(spec.env)){if(allowed.has(key)&&!SECRET_KEY.test(key))env[key]=value}const {promise,resolve:resolveResult,reject}=Promise.withResolvers<SecureProcessResultV1>();const child=spawn(executable,[...spec.argv],{cwd,env,stdio:["ignore","pipe","pipe"],shell:false,windowsHide:true});const out:Buffer[]=[],err:Buffer[]=[];child.stdout.on("data",(chunk:Buffer)=>out.push(chunk));child.stderr.on("data",(chunk:Buffer)=>err.push(chunk));child.once("error",reject);const timer=setTimeout(()=>child.kill("SIGKILL"),spec.timeoutMs);child.once("close",(exitCode,signal)=>{clearTimeout(timer);const bound=(chunks:Buffer[]):readonly [string,boolean]=>{const redacted=Buffer.from(redact(Buffer.concat(chunks).toString("utf8"),spec.redactions),"utf8"),truncated=redacted.length>spec.outputLimitBytes;return [redacted.subarray(0,spec.outputLimitBytes).toString("utf8"),truncated]};const [stdout,stdoutTruncated]=bound(out),[stderr,stderrTruncated]=bound(err);resolveResult(Object.freeze({exitCode,signal,stdout,stderr,stdoutTruncated,stderrTruncated}))});return await promise}

export class SecureWorkerAdapterV1 implements WorkerAdapterV1{
 readonly #guard:AdapterBindingGuardV1;readonly #delegate:WorkerAdapterV1;readonly #seen=new Map<string,Promise<AdapterOperationResultV1>>();
 constructor(binding:BoundAdapterOperationV1,delegate:WorkerAdapterV1){this.#guard=createBindingGuard(binding);this.#delegate=delegate}
 detectCapabilities():Promise<AdapterCapabilitiesV1>{return this.#delegate.detectCapabilities()}
 #once(key:string,operation:BoundAdapterOperationV1,callback:()=>Promise<AdapterOperationResultV1>):Promise<AdapterOperationResultV1>{this.#guard.assert(operation);const prior=this.#seen.get(key);if(prior!==undefined)return prior;const current=callback();this.#seen.set(key,current);return current}
 launch(request:AdapterLaunchRequestV1):Promise<AdapterOperationResultV1>{return this.#once("launch",request,()=>this.#delegate.launch(request))}
 cancel(request:AdapterCancelRequestV1):Promise<AdapterOperationResultV1>{return this.#once(`cancel:${request.cancelIdempotencyKey}`,request,()=>this.#delegate.cancel(request))}
 reconcile(request:AdapterReconcileRequestV1):Promise<AdapterOperationResultV1>{return this.#once(`reconcile:${request.providerOperationId??"none"}`,request,()=>this.#delegate.reconcile(request))}
 resume(request:AdapterResumeRequestV1):Promise<AdapterOperationResultV1>{return this.#once(`${request.operation}:${request.providerOperationId}:${request.nativeSessionId??"none"}`,request,()=>this.#delegate.resume(request))}
 collectReceipt(binding:BoundAdapterOperationV1):Promise<AttemptReceiptEnvelopeV1>{this.#guard.assert(binding);return this.#delegate.collectReceipt(binding)}
}

export interface WorkerReturnClientV1{publishObject(digest:string,kind:"artifact"|"evidence"):Promise<void>;submitReceipt(receipt:WorkerReturnV1["receipt"],binding:BoundAdapterOperationV1):Promise<string>;submitProposal(proposal:WorkerReturnV1["proposal"],binding:BoundAdapterOperationV1):Promise<{proposalId:string;proposalDigest:string}>;subscribeDecision(input:{proposalId:string;proposalDigest:string;subscriptionId:string;resumeToken:string|null}):Promise<{resumeToken:string|null;decision:"accepted"|"rejected"|"conflicted"|"quarantined"|"approval_required"}>}
export type WorkerReturnDeliveryStepV1=`publication:${number}`|"receipt"|"proposal"|"decision";
export interface WorkerReturnDeliveryAuthorityV1{perform<T>(step:WorkerReturnDeliveryStepV1,operation:()=>Promise<T>):Promise<T>}
export async function deliverWorkerReturn(workerReturn:WorkerReturnV1,client:WorkerReturnClientV1,authority?:WorkerReturnDeliveryAuthorityV1):Promise<{receiptDigest:string;decision:string;resumeToken:string|null}>{
 const guard=createBindingGuard(workerReturn.binding);guard.assert(workerReturn.binding);
 const perform=<T>(step:WorkerReturnDeliveryStepV1,operation:()=>Promise<T>)=>authority===undefined?operation():authority.perform(step,operation);
 for(const [index,publication] of workerReturn.publications.entries())await perform(`publication:${index}` as WorkerReturnDeliveryStepV1,()=>client.publishObject(digest(publication.digest,"WORKER_RETURN_INVALID"),publication.kind));
 const receiptDigest=await perform("receipt",()=>client.submitReceipt(workerReturn.receipt,guard.binding));
 const proposal=await perform("proposal",()=>client.submitProposal(workerReturn.proposal,guard.binding));
 if(proposal.proposalId!==workerReturn.decisionResume.proposalId||proposal.proposalDigest!==workerReturn.decisionResume.proposalDigest)fail("DECISION_SCOPE_MISMATCH","proposal decision subscription substituted");
 const decision=await perform("decision",()=>client.subscribeDecision(workerReturn.decisionResume));
 return Object.freeze({receiptDigest,decision:decision.decision,resumeToken:decision.resumeToken});
}
