import assert from "node:assert/strict";
import { createWorkspaceGenesis, NO_POLICY_DIGEST } from "@horseness/domain";
import { existsSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { createBackup, verifyBackup } from "../../src/backup/index.js";
import { importBackup, promoteImportedBackup } from "../../src/import/index.js";
import { upgradeAuthority } from "../../src/migrations/index.js";
import { SQLiteAuthority } from "../../src/sqlite-authority.js";

function authority(root:string,name:string):{database:string;artifacts:string;db:DatabaseSync} {const database=join(root,`${name}.sqlite`),artifacts=join(root,`${name}-artifacts`);new SQLiteAuthority(database,artifacts).close();const db=new DatabaseSync(database);upgradeAuthority(db,artifacts);return{database,artifacts,db};}
function manifest(root:string):Record<string,unknown> {return JSON.parse(readFileSync(join(root,"manifest.json"),"utf8")) as Record<string,unknown>;}
function saveManifest(root:string,value:unknown):void {writeFileSync(join(root,"manifest.json"),`${JSON.stringify(value,null,2)}\n`);}

test("backup manifest rejects traversal, absolute paths, duplicate paths, and unknown versions",()=>{const root=mkdtempSync(join(tmpdir(),"horseness-import-paths-"));try{const source=authority(root,"source"),backup=join(root,"backup");createBackup(source.db,source.artifacts,backup);source.db.close();for(const file of ["../escape.sqlite","/tmp/escape.sqlite","db/../authority.sqlite"]){const value=manifest(backup);const database=value.database as Record<string,unknown>;database.file=file;saveManifest(backup,value);assert.throws(()=>verifyBackup(backup),/path|root/);}const value=manifest(backup);value.schemaVersion=2;saveManifest(backup,value);assert.throws(()=>verifyBackup(backup),/version/);}finally{rmSync(root,{recursive:true,force:true});}});

test("backup enumeration rejects extra files, symlinks, and catalog mismatch",()=>{const root=mkdtempSync(join(tmpdir(),"horseness-import-enum-"));try{const source=authority(root,"source"),backup=join(root,"backup");createBackup(source.db,source.artifacts,backup);source.db.close();writeFileSync(join(backup,"artifacts","unlisted"),"foreign");assert.throws(()=>verifyBackup(backup),/enumeration mismatch/);rmSync(join(backup,"artifacts","unlisted"));symlinkSync(join(backup,"db","authority.sqlite"),join(backup,"artifacts","link"));assert.throws(()=>verifyBackup(backup),/symlink/);rmSync(join(backup,"artifacts","link"));const value=manifest(backup);value.artifacts=[{path:"artifacts/objects/aa/missing",digest:"0".repeat(64),bytes:0}];saveManifest(backup,value);assert.throws(()=>verifyBackup(backup),/enumeration mismatch|catalog mismatch/);}finally{rmSync(root,{recursive:true,force:true});}});

test("foreign authority is remapped into quarantine and cannot mutate live authority",()=>{const root=mkdtempSync(join(tmpdir(),"horseness-import-quarantine-"));try{const sourceDatabase=join(root,"source.sqlite"),sourceArtifacts=join(root,"source-artifacts"),sourceStore=new SQLiteAuthority(sourceDatabase,sourceArtifacts);const genesis=createWorkspaceGenesis({workspaceId:"foreign-workspace",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:NO_POLICY_DIGEST,commandId:"foreign-genesis"});sourceStore.appendAtomic({commandId:"foreign-genesis",workspace:{streamKind:"workspace",workspaceId:"foreign-workspace",streamId:"foreign-workspace",expectedSequence:0,expectedEnvelopeHash:null,events:[genesis.event]}});sourceStore.close();const sourceDb=new DatabaseSync(sourceDatabase);upgradeAuthority(sourceDb,sourceArtifacts);const backup=join(root,"backup");createBackup(sourceDb,sourceArtifacts,backup);sourceDb.close();const target=authority(root,"target");const before=(target.db.prepare("SELECT count(*) AS count FROM streams").get() as {count:number}).count;const imported=importBackup(target.db,target.artifacts,backup);assert.equal(imported.state,"quarantined");assert.equal(imported.workspaces.length,1);assert.equal(imported.workspaces[0]?.sourceWorkspaceId,"foreign-workspace");assert.notEqual(imported.workspaces[0]?.localWorkspaceId,"foreign-workspace");assert.equal((target.db.prepare("SELECT count(*) AS count FROM streams").get() as {count:number}).count,before);assert.equal(existsSync(join(imported.quarantinePath,"db","authority.sqlite")),true);const provenance=JSON.parse(readFileSync(join(imported.quarantinePath,"provenance.json"),"utf8")) as {state:string};assert.equal(provenance.state,"quarantined");target.db.close();}finally{rmSync(root,{recursive:true,force:true});}});

test("promotion requires explicit review and atomically records it",()=>{const root=mkdtempSync(join(tmpdir(),"horseness-import-promotion-"));try{const source=authority(root,"source"),backup=join(root,"backup");createBackup(source.db,source.artifacts,backup);source.db.close();const target=authority(root,"target"),imported=importBackup(target.db,target.artifacts,backup);assert.throws(()=>promoteImportedBackup(imported.quarantinePath,{reviewedBy:"",reviewEvidence:"ticket-1"}),/explicit review/);const promoted=promoteImportedBackup(imported.quarantinePath,{reviewedBy:"reviewer@example.test",reviewEvidence:"ticket-1 approved digest"});assert.equal(promoted.state,"promoted");assert.equal(promoted.promotion?.reviewEvidence,"ticket-1 approved digest");assert.throws(()=>promoteImportedBackup(imported.quarantinePath,{reviewedBy:"reviewer",reviewEvidence:"again"}),/not quarantined/);target.db.close();}finally{rmSync(root,{recursive:true,force:true});}});
