import assert from "node:assert/strict";
import test from "node:test";
import { domainDigest, sealDependencyJoinSnapshot, type CompositeCursorV1, type JsonValue } from "@horseness/domain";
import { issueStoredAuthorityEvent, type DurableAuthorityEventV1 } from "../../src/tasks/task-projection.js";
import { selectReadyTasks } from "../../src/scheduler/index.js";

const cursor:CompositeCursorV1={schemaVersion:"1",kind:"composite",workspaceId:"w",workspaceSequence:1,workspaceEnvelopeHash:"wh",workspaceContextEpoch:0,runId:"r",runSequence:2,runEnvelopeHash:"rh",runContextEpoch:1};
function accepted(){const payload={eventType:"DeltaAcceptedV1" as const,workspaceId:"w",runId:"r",taskId:"t",proposalDigest:"p",resultingRevision:1,resultingStateHash:"state"};const envelope={schemaVersion:"1" as const,eventId:"evt",streamKind:"run" as const,workspaceId:"w",streamId:"r",sequence:2,priorEnvelopeHash:"prior",eventType:"DeltaAcceptedV1",payloadHash:domainDigest("horseness.event-payload.v1",payload as unknown as JsonValue),payload,createdAt:"2026-01-01T00:00:00.000Z"};const record:DurableAuthorityEventV1={envelope,envelopeHash:domainDigest("horseness.event-envelope.v1",envelope as unknown as JsonValue),resultCursor:cursor};return issueStoredAuthorityEvent({authenticatedView:()=>({cursor}),exactRunHeadSnapshot:()=>({state:record})} as never,{workspaceId:"w",runId:"r",sequence:2,eventType:"DeltaAcceptedV1"});}
function candidate(taskId:string,priority:number,sequence:number){const snapshot=sealDependencyJoinSnapshot({schemaVersion:"1",runId:"r",taskId,taskContractDigest:`contract-${taskId}`,joinEvaluationId:`join-${taskId}`,joinObservationCursor:cursor,dependencies:[],schedulability:"ready",reasonCodes:[]});return{taskId,priority,createdSequence:sequence,join:{taskId,schedulability:"ready" as const,cancellationPropagated:false,reasonCodes:[],authoritySnapshotIdentities:[],snapshot},deltaAccepted:accepted()};}
test("ready set ordering and decisions replay deterministically",()=>{const inputs=[candidate("z",1,2),candidate("b",2,3),candidate("a",2,3)];const first=selectReadyTasks(inputs),second=selectReadyTasks([...inputs].reverse());assert.deepEqual(first,second);assert.deepEqual(first.map(item=>item.taskId),["a","b","z"]);assert.ok(first.every(item=>item.decisionCode==="READY"&&item.authorizationKey));const duplicate=selectReadyTasks(inputs,new Set([first[0]!.authorizationKey!]));assert.equal(duplicate[0]!.decisionCode,"ALREADY_AUTHORIZED");});
test("no authorization is produced before durable accepted authority",()=>{const input={...candidate("t",1,1),deltaAccepted:null};const [decision]=selectReadyTasks([input]);assert.equal(decision!.decisionCode,"DELTA_NOT_ACCEPTED");assert.equal(decision!.authorizationKey,null);});
