import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { NO_POLICY_DIGEST, NO_POLICY_V1, createRunGenesis, createWorkspaceGenesis, deltaAuthorityScopeDigest, deterministicReplay, deterministicWorkspaceReplay, jsonValueDigest, sealEventEnvelope, sealForkPin, sealProposal, type CapabilityV1, type CompositeCursorV1, type ProposalEnvelopeCoreV1 } from "@horseness/domain";
import { sealPolicyDocument, type PolicyEffectV1 } from "@horseness/policy";
import { SQLiteAuthority } from "@horseness/store-sqlite";
import { AdmissionService, loadRevision, type AdmissionCurrentAuthorityV1, type AdmissionRequestV1 } from "../../src/index.js";

function setup(effect:PolicyEffectV1, quotaAvailable=true){
  const root=mkdtempSync(join(tmpdir(),"horseness-admission-transition-")); const database=join(root,"authority.sqlite"); const artifacts=join(root,"artifacts"); let authority=new SQLiteAuthority(database,artifacts);
  const workspace=createWorkspaceGenesis({workspaceId:"w",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:NO_POLICY_DIGEST,commandId:"workspace"}); authority.appendAtomic({commandId:"workspace",workspace:{streamKind:"workspace",workspaceId:"w",streamId:"w",expectedSequence:0,expectedEnvelopeHash:null,events:[workspace.event]}});
  const absent={schemaVersion:"1" as const,kind:"absent-run-genesis" as const,workspaceId:"w",workspaceSequence:1,workspaceEnvelopeHash:workspace.event.envelopeHash,workspaceContextEpoch:0,runId:"r",expectedRunHead:"absent" as const}; const run=createRunGenesis({observationCursor:absent,initialDocument:{value:1},principalId:"worker",commandId:"run"}); authority.appendAtomic({commandId:"run",runGenesis:{observationCursor:absent,event:run.event}});
  const cursor:CompositeCursorV1=run.resultCursor; const revision=loadRevision(authority,"w","r"); const scope={schemaVersion:"1" as const,workspaceId:"w",runId:"r",taskId:"t",roots:["/value"]};
  const policy=effect==="accepted"?NO_POLICY_V1:sealPolicyDocument({schemaVersion:"1",kind:"policy",policyId:"p",revision:0,predecessorDigest:null,rules:[{ruleId:"rule",subject:{action:null,pathPrefix:null,version:null},effect,constraints:[],evidence:[]}]});
  const fork=sealForkPin({schemaVersion:"1",forkId:"f",pinVersion:1,workspaceId:"w",runId:"r",parentForkPinDigest:null,refreshesForkPinDigest:null,canonicalRevision:revision.revision,canonicalStateHash:revision.stateHash,canonicalizerVersion:"jcs-v1",hashVersion:"sha256-v1",sourceObservationCursor:cursor,sourceContextVersion:{schemaVersion:"1",kind:"composite",workspaceContextEpoch:0,runContextEpoch:0,observationCursor:cursor},dependencyJoinSnapshotDigest:"join",deltaAuthorityScopeDigest:deltaAuthorityScopeDigest(scope),pinnedPolicyDigest:policy.kind==="no-policy"?NO_POLICY_DIGEST:policy.policyDigest,ancestry:[],createdByPrincipalId:"worker",createdByGrantDigest:"grant"});
  const capability:CapabilityV1={schemaVersion:"1",workspaceId:"w",runId:"r",commands:["submit-proposal"],issuer:"authority",delegatee:"worker",issuedObservationSequence:1,expiresObservationSequence:100,nonce:"cap",revocationSequence:null}; const current:AdmissionCurrentAuthorityV1={schemaVersion:"1",evaluationObservationCursor:cursor,currentPolicy:policy,authorization:{role:"worker",capabilityId:"capability",capability,grantDigest:"grant",revoked:false},quota:{id:"quota",digest:"quota-digest",available:quotaAvailable},authenticatedApproverPrincipalId:"approver",authorityTime:"2026-08-12T00:00:00Z"};
  authority.putSnapshot({workspaceId:"w",streamKind:"run",streamId:"r",sequence:1,envelopeHash:cursor.runEnvelopeHash,projectionName:"admission-sealing",projectionVersion:"1",state:{schemaVersion:"1",observationCursor:cursor,fork,scope,receipts:[],pinnedPolicy:policy,evidence:[]}}); authority.putSnapshot({workspaceId:"w",streamKind:"run",streamId:"r",sequence:1,envelopeHash:cursor.runEnvelopeHash,projectionName:"admission-current",projectionVersion:"1",state:current});
  const proposalCore:ProposalEnvelopeCoreV1={schemaVersion:"1",workspaceId:"w",runId:"r",authorPrincipalId:"worker",authorGrantDigest:"grant",attemptId:"attempt",receiptDigests:[],forkPinDigest:fork.forkPinDigest,deltaAuthorityScopeDigest:deltaAuthorityScopeDigest(scope),baseRevision:0,baseStateHash:revision.stateHash,canonicalizerVersion:"jcs-v1",hashVersion:"sha256-v1",proposalSealingObservationCursor:cursor,proposalSealingContextVersion:{schemaVersion:"1",kind:"composite",workspaceContextEpoch:0,runContextEpoch:0,observationCursor:cursor},operations:[{op:"replace",path:"/value",expectedValueDigest:jsonValueDigest(1),value:2}],evidenceClaims:[],pinnedPolicyDigest:policy.kind==="no-policy"?NO_POLICY_DIGEST:policy.policyDigest,currentPolicyDigest:policy.kind==="no-policy"?NO_POLICY_DIGEST:policy.policyDigest,nonce:"proposal",predecessorProposalDigest:null,predecessorReason:null}; const proposal=sealProposal(proposalCore);
  const request=(commandId:string,action:string,approval:AdmissionRequestV1["approval"]=null,policyDigest=proposalCore.currentPolicyDigest):AdmissionRequestV1=>({schemaVersion:"1",commandId,proposal,scopeDigest:proposalCore.deltaAuthorityScopeDigest,forkPinDigest:proposalCore.forkPinDigest,receiptDigests:[],evidenceIds:[],policyDigest,quotaId:"quota",evaluationClock:{schemaVersion:"1",authorityTime:current.authorityTime,observationCursor:cursor},approval,authorization:{capabilityId:"capability"},action,version:"1"});
  const updateCurrent=(nextEffect:PolicyEffectV1,available=true)=>{const workspaceHead=authority.replay("w","workspace","w").at(-1)!;const runHead=authority.replay("w","run","r").at(-1)!;const observationCursor:CompositeCursorV1={schemaVersion:"1",kind:"composite",workspaceId:"w",workspaceSequence:workspaceHead.envelope.sequence,workspaceEnvelopeHash:workspaceHead.envelopeHash,workspaceContextEpoch:workspaceHead.envelope.sequence-1,runId:"r",runSequence:runHead.envelope.sequence,runEnvelopeHash:runHead.envelopeHash,runContextEpoch:runHead.envelope.sequence-1};const nextPolicy=nextEffect==="accepted"?NO_POLICY_V1:sealPolicyDocument({schemaVersion:"1",kind:"policy",policyId:`current-${nextEffect}`,revision:0,predecessorDigest:null,rules:[{ruleId:"rule",subject:{action:null,pathPrefix:null,version:null},effect:nextEffect,constraints:[],evidence:[]}]});authority.putSnapshot({workspaceId:"w",streamKind:"run",streamId:"r",sequence:runHead.envelope.sequence,envelopeHash:runHead.envelopeHash,projectionName:"admission-current",projectionVersion:"1",state:{...current,evaluationObservationCursor:observationCursor,currentPolicy:nextPolicy,quota:{...current.quota,available}}});return nextPolicy.kind==="no-policy"?NO_POLICY_DIGEST:nextPolicy.policyDigest;};
  return {get authority(){return authority;},reopen(){authority.close();authority=new SQLiteAuthority(database,artifacts);},request,updateCurrent,policy,cursor,proposal,cleanup(){authority.close();rmSync(root,{recursive:true,force:true});}};
}

test("approval-required decisions persist an exact current snapshot and continue after reopen",()=>{for(const transition of ["approve","reject"]){const f=setup("approval_required");try{assert.equal(new AdmissionService(f.authority).evaluateAndApply(f.request("initial","write")).state,"approval_required");f.reopen();const now=f.authority.latestSnapshot("w","run","r","admission-current","1");assert.equal(now?.sequence,3);const cursor={schemaVersion:"1" as const,kind:"composite" as const,workspaceId:"w",workspaceSequence:2,workspaceEnvelopeHash:f.authority.replay("w","workspace","w").at(-1)!.envelopeHash,workspaceContextEpoch:1,runId:"r",runSequence:3,runEnvelopeHash:f.authority.replay("w","run","r").at(-1)!.envelopeHash,runContextEpoch:2};assert.deepEqual((now?.state as unknown as AdmissionCurrentAuthorityV1).evaluationObservationCursor,cursor);const approval=transition==="approve"?{schemaVersion:"1" as const,approvalId:"approval",proposalDigest:f.proposal.proposalDigest,baseRevision:0,baseStateHash:f.proposal.core.baseStateHash,pinnedPolicyDigest:f.proposal.core.pinnedPolicyDigest,currentPolicyDigest:f.proposal.core.currentPolicyDigest,approverPrincipalId:"approver",approverGrantDigest:"grant",allowedAction:"approve",issueObservationCursor:f.cursor,evaluationObservationCursor:cursor,issuedAt:"2026-08-11T00:00:00Z",expiresAt:"2026-08-13T00:00:00Z"}:null;assert.equal(new AdmissionService(f.authority).evaluateAndApply(f.request(transition,transition,approval)).state,transition==="approve"?"accepted":"rejected");}finally{f.cleanup();}}});

test("release re-evaluates exact current authority and cannot override precedence",()=>{for(const current of ["rejected","quarantined","approval_required","accepted"] as const){const f=setup("accepted",false);try{assert.equal(new AdmissionService(f.authority).evaluateAndApply(f.request("initial","write")).state,"quarantined");f.reopen();const snapshot=f.authority.latestSnapshot("w","run","r","admission-current","1")!;f.authority.db.prepare("UPDATE snapshots SET envelope_hash='substituted' WHERE workspace_id='w' AND stream_kind='run' AND stream_id='r' AND sequence=? AND projection_name='admission-current'").run(snapshot.sequence);assert.throws(()=>new AdmissionService(f.authority).evaluateAndApply(f.request("substituted","release")),/AUTHORITY_STATE_SUBSTITUTED/);f.authority.db.prepare("UPDATE snapshots SET envelope_hash=? WHERE workspace_id='w' AND stream_kind='run' AND stream_id='r' AND sequence=? AND projection_name='admission-current'").run(snapshot.envelopeHash,snapshot.sequence);const policyDigest=f.updateCurrent(current,current!=="quarantined");assert.equal(new AdmissionService(f.authority).evaluateAndApply(f.request(`release-${current}`,"release",null,policyDigest)).state,current);}finally{f.cleanup();}}});

test("workspace authority change after an older run snapshot fails closed after restart",()=>{const f=setup("accepted",false);try{assert.equal(new AdmissionService(f.authority).evaluateAndApply(f.request("initial","write")).state,"quarantined");const workspaceHead=f.authority.replay("w","workspace","w").at(-1)!;const payload={eventType:"PolicyReferenceChangedV1" as const,workspaceId:"w",activePolicyDigest:"changed-policy"};const changed=sealEventEnvelope({schemaVersion:"1",streamKind:"workspace",workspaceId:"w",streamId:"w",sequence:workspaceHead.envelope.sequence+1,priorEnvelopeHash:workspaceHead.envelopeHash,eventId:"authority-change:1",eventType:payload.eventType,payload,principalId:"authority",causationId:"authority-change",correlationId:"authority-change",idempotencyKey:"authority-change"});f.authority.appendAtomic({commandId:"authority-change",workspace:{streamKind:"workspace",workspaceId:"w",streamId:"w",expectedSequence:workspaceHead.envelope.sequence,expectedEnvelopeHash:workspaceHead.envelopeHash,events:[changed]}});f.reopen();assert.throws(()=>new AdmissionService(f.authority).evaluateAndApply(f.request("stale-release","release")),/AUTHORITY_STATE_SUBSTITUTED/);}finally{f.cleanup();}});

test("release can remain quarantined or require approval and both authority chains replay after reopen",()=>{for(const current of ["quarantined","approval_required"] as const){const f=setup("accepted",false);try{assert.equal(new AdmissionService(f.authority).evaluateAndApply(f.request("initial","write")).state,"quarantined");f.reopen();const policyDigest=f.updateCurrent(current,current!=="quarantined");assert.equal(new AdmissionService(f.authority).evaluateAndApply(f.request(`release-${current}`,"release",null,policyDigest)).state,current);f.reopen();const run=deterministicReplay(f.authority.replay("w","run","r"));const workspace=deterministicWorkspaceReplay(f.authority.replay("w","workspace","w"));assert.equal(run.operational.proposals[f.proposal.proposalId]?.status,current);assert.equal(workspace.admissions[f.proposal.proposalDigest]?.state,current);assert.equal(workspace.admissions[f.proposal.proposalDigest]?.history.length,2);}finally{f.cleanup();}}});
