import assert from "node:assert/strict";
import {mkdtemp,realpath,symlink,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import test from "node:test";
import type {AttemptReceiptEnvelopeV1,ProposalEnvelopeV1} from "@horseness/domain";
import type {AdapterLaunchRequestV1,AdapterOperationResultV1,BoundAdapterOperationV1,WorkerAdapterV1,WorkerReturnV1} from "@horseness/protocol";
import {AdapterKitError,SecureWorkerAdapterV1,createBindingGuard,deliverWorkerReturn,parseCredentialReferenceV1,parseDoctorProbeResultV1,parseInstallContributionV1,runSecureProcess} from "../src/index.js";

const binding={schemaVersion:"1",workspaceId:"ws",runId:"run",taskId:"task",attemptId:"attempt",generation:1,forkPinDigest:"sha256:fork",contextManifestCoreDigest:"sha256:manifest",attemptContextBindingDigest:"sha256:binding",providerIdempotencyKeyDigest:"sha256:key",attemptCapability:"capability-ref"} as const satisfies BoundAdapterOperationV1;
const launch={...binding,operation:"launch",renderedContextDigest:"sha256:rendered",providerOptions:{}} as const satisfies AdapterLaunchRequestV1;
const result:AdapterOperationResultV1={schemaVersion:"1",status:"accepted",providerOperationId:"operation",nativeSessionId:"session",details:{}};
const receipt={schemaVersion:"1"} as unknown as AttemptReceiptEnvelopeV1;
const fakeAdapter=()=>{const calls:string[]=[];const adapter:WorkerAdapterV1={async detectCapabilities(){calls.push("capabilities");return {schemaVersion:"1",adapterId:"adapter",providerId:"provider",launch:true,cancel:true,reconcile:"supported",reattach:"supported",nativeResume:"supported",contextInjection:"bytes",receiptCollection:true,maxContextBytes:4096,outputMediaTypes:["text/plain"],evidenceMediaTypes:["application/json"]}},async launch(){calls.push("launch");return result},async cancel(){calls.push("cancel");return result},async reconcile(){calls.push("reconcile");return result},async resume(request){calls.push(request.operation);return result},async collectReceipt(){calls.push("receipt");return receipt}};return {adapter,calls}};
const hasCode=(code:string)=>(error:unknown)=>error instanceof AdapterKitError&&error.code===code;

test("capabilities and lifecycle callbacks retain immutable binding and deduplicate",async()=>{const fake=fakeAdapter(),secure=new SecureWorkerAdapterV1(binding,fake.adapter);assert.equal((await secure.detectCapabilities()).nativeResume,"supported");assert.deepEqual(await secure.launch(launch),result);assert.deepEqual(await secure.launch(launch),result);await secure.cancel({...binding,operation:"cancel",providerOperationId:"operation",cancelIdempotencyKey:"cancel-1"});await secure.reconcile({...binding,operation:"reconcile",providerOperationId:"operation"});await secure.resume({...binding,operation:"reattach",providerOperationId:"operation",nativeSessionId:"session"});await secure.resume({...binding,operation:"resume",providerOperationId:"operation",nativeSessionId:"session"});assert.equal(await secure.collectReceipt(binding),receipt);assert.equal(fake.calls.filter(value=>value==="launch").length,1);assert.deepEqual(fake.calls,["capabilities","launch","cancel","reconcile","reattach","resume","receipt"])});

test("binding and scope substitution fail closed",()=>{const guard=createBindingGuard(binding);assert.throws(()=>guard.assert({...binding,workspaceId:"other"}),hasCode("BINDING_SUBSTITUTED"));const fake=fakeAdapter(),secure=new SecureWorkerAdapterV1(binding,fake.adapter);assert.throws(()=>secure.launch({...launch,generation:2}),hasCode("BINDING_SUBSTITUTED"));assert.deepEqual(fake.calls,[])});

test("credential references are opaque scoped identifiers, never values",()=>{assert.deepEqual(parseCredentialReferenceV1({schemaVersion:"1",kind:"keychain",reference:"keychain-ref-123",scope:{workspaceId:"ws",adapterId:"adapter",purpose:"provider-auth"}}).scope.workspaceId,"ws");assert.throws(()=>parseCredentialReferenceV1({schemaVersion:"1",kind:"keychain",reference:"TOKEN=secret",scope:{workspaceId:"ws",adapterId:"adapter",purpose:"auth"}}),hasCode("CREDENTIAL_REFERENCE_INVALID"));for(const reference of ["ghp_abcdefghijklmnopqrstuvwxyz","sk_live_abcdefghijklmnopqrstuvwxyz","xoxb-123456789-secretvalue","sk-abcdefghijklmnopqrstuvwxyz","-----BEGIN PRIVATE KEY-----"])assert.throws(()=>parseCredentialReferenceV1({schemaVersion:"1",kind:"keychain",reference,scope:{workspaceId:"ws",adapterId:"adapter",purpose:"auth"}}),hasCode("CREDENTIAL_REFERENCE_INVALID"),`raw secret ${reference} must be rejected`)});

test("secure runner confines executable/cwd, strips secret env, redacts and bounds output",async()=>{const root=await mkdtemp(join(tmpdir(),"adapter-kit-")),script=join(root,"probe.mjs");await writeFile(script,"process.stdout.write(`${process.env.SAFE ?? ''}:${process.env.API_TOKEN ?? 'stripped'}:credential-value:0123456789`);process.stderr.write('credential-value')");const node=await realpath(process.execPath),nodeRoot=join(node,"..");const run=await runSecureProcess({executable:node,argv:[script],cwd:root,executableRoots:[nodeRoot],cwdRoots:[root],env:{SAFE:"allowed",API_TOKEN:"credential-value"},envAllowlist:["SAFE","API_TOKEN"],outputLimitBytes:32,redactions:["credential-value"],timeoutMs:5000});assert.match(run.stdout,/allowed:stripped:\[REDACTED\]/);assert.equal(run.stdout.includes("credential-value"),false);assert.equal(run.stderr,"[REDACTED]");assert.equal(run.stdoutTruncated,true);assert.ok(Buffer.byteLength(run.stdout)<=32);await assert.rejects(()=>runSecureProcess({executable:node,argv:[],cwd:tmpdir(),executableRoots:[nodeRoot],cwdRoots:[root],env:{},envAllowlist:[],outputLimitBytes:1,redactions:[],timeoutMs:100}),hasCode("CWD_OUTSIDE_ROOT"));const link=join(root,"escape");await symlink(tmpdir(),link);await assert.rejects(()=>runSecureProcess({executable:node,argv:[],cwd:link,executableRoots:[nodeRoot],cwdRoots:[root],env:{},envAllowlist:[],outputLimitBytes:1,redactions:[],timeoutMs:100}),hasCode("CWD_OUTSIDE_ROOT"))});

test("declarative install and read-only doctor schemas reject hooks, target escape, mutation fields",()=>{const contribution=parseInstallContributionV1({schemaVersion:"1",kind:"plugin",contributionId:"plugin",relativePath:"plugins/horseness.json",contentDigest:"sha256:content",sourceArtifactDigest:"sha256:source",mode:"read-only",hostScope:"pi"});assert.equal(contribution.kind,"plugin");assert.throws(()=>parseInstallContributionV1({...contribution,relativePath:"../host.json"}),hasCode("INSTALL_CONTRIBUTION_INVALID"));assert.throws(()=>parseInstallContributionV1({...contribution,hook:"postinstall"}),hasCode("INSTALL_CONTRIBUTION_INVALID"));assert.equal(parseDoctorProbeResultV1({schemaVersion:"1",checks:[{code:"HOST_OK",status:"ok",evidenceDigest:null}],restartRequired:false}).checks[0]?.code,"HOST_OK");assert.throws(()=>parseDoctorProbeResultV1({schemaVersion:"1",checks:[],restartRequired:false,repair:true}),hasCode("DOCTOR_RESULT_INVALID"))});

test("WorkerReturn publishes, submits, and resumes a bound decision without authority escalation",async()=>{const proposal={schemaVersion:"1"} as unknown as ProposalEnvelopeV1;const returned={schemaVersion:"1",binding,receipt,proposal,publishedObjectDigests:["sha256:artifact","sha256:evidence"],decisionResume:{proposalId:"proposal",proposalDigest:"sha256:proposal",subscriptionId:"subscription",resumeToken:"resume-1"}} as const satisfies WorkerReturnV1;const calls:string[]=[];const outcome=await deliverWorkerReturn(returned,{async publishObject(value){calls.push(`publish:${value}`)},async submitReceipt(_receipt,retained){createBindingGuard(binding).assert(retained);calls.push("receipt");return "sha256:receipt"},async submitProposal(_proposal,retained){createBindingGuard(binding).assert(retained);calls.push("proposal");return {proposalId:"proposal",proposalDigest:"sha256:proposal"}},async subscribeDecision(input){calls.push(`subscribe:${input.resumeToken}`);return {resumeToken:"resume-2",decision:"accepted"}}});assert.deepEqual(outcome,{receiptDigest:"sha256:receipt",decision:"accepted",resumeToken:"resume-2"});assert.deepEqual(calls,["publish:sha256:artifact","publish:sha256:evidence","receipt","proposal","subscribe:resume-1"]);await assert.rejects(()=>deliverWorkerReturn(returned,{async publishObject(){},async submitReceipt(){return "receipt"},async submitProposal(){return {proposalId:"other",proposalDigest:"sha256:proposal"}},async subscribeDecision(){throw new Error("must not subscribe")}}),hasCode("DECISION_SCOPE_MISMATCH"))});
