import assert from "node:assert/strict";
import test from "node:test";
import { domainDigest, sealDependencyJoinSnapshot, type CompositeCursorV1 } from "@horseness/domain";
import { createBoundAttempt, requestAttemptCancellation, recordAttemptOutcome, assertImmutableBinding } from "../../src/attempts/index.js";
import { selectReadyTasks } from "../../src/scheduler/index.js";
import { issueStoredAuthorityEvent, type DurableAuthorityEventV1 } from "../../src/tasks/task-projection.js";
import { authenticContextFixture } from "../context/authentic-context.fixture.js";
const cursor:CompositeCursorV1={schemaVersion:"1",kind:"composite",workspaceId:"w",workspaceSequence:1,workspaceEnvelopeHash:"wh",workspaceContextEpoch:0,runId:"r",runSequence:2,runEnvelopeHash:"rh",runContextEpoch:1};
export function fixture(){const payload={eventType:"DeltaAcceptedV1" as const,workspaceId:"w",runId:"r",taskId:"t",proposalDigest:"p",resultingRevision:1,resultingStateHash:"state"},envelope={schemaVersion:"1" as const,eventId:"evt",streamKind:"run" as const,workspaceId:"w",streamId:"r",sequence:2,priorEnvelopeHash:"prior",eventType:"DeltaAcceptedV1",payloadHash:domainDigest("horseness.event-payload.v1",payload),payload,createdAt:"2026-01-01T00:00:00.000Z"},record:DurableAuthorityEventV1={envelope,envelopeHash:domainDigest("horseness.event-envelope.v1",envelope),resultCursor:cursor},accepted=issueStoredAuthorityEvent({authenticatedView:()=>({cursor}),exactRunHeadSnapshot:()=>({state:record})} as never,{workspaceId:"w",runId:"r",sequence:2,eventType:"DeltaAcceptedV1"});const snapshot=sealDependencyJoinSnapshot({schemaVersion:"1",runId:"r",taskId:"t",taskContractDigest:"contract",joinEvaluationId:"join",joinObservationCursor:cursor,dependencies:[],schedulability:"ready",reasonCodes:[]}),decision=selectReadyTasks([{taskId:"t",priority:1,createdSequence:1,join:{taskId:"t",schedulability:"ready",cancellationPropagated:false,reasonCodes:[],authoritySnapshotIdentities:[],snapshot},deltaAccepted:accepted}])[0]!,issued=authenticContextFixture();return{decision,pin:issued.pin,context:issued.context,close:issued.close};}
test("duplicate authorization is idempotent and binding remains immutable across cancellation/outcome",()=>{const f=fixture();try{const created=createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1});const duplicate=createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1,existing:created.attempt});assert.equal(duplicate.code,"DUPLICATE_AUTHORIZATION");assert.equal(duplicate.attempt,created.attempt);const cancelled=requestAttemptCancellation(created.attempt);assertImmutableBinding(created.attempt,cancelled.attempt);const late=recordAttemptOutcome(cancelled.attempt,"succeeded");assertImmutableBinding(created.attempt,late.attempt);assert.equal(late.attempt.outcome,"succeeded");assert.equal(requestAttemptCancellation(late.attempt).code,"CANCELLATION_IDEMPOTENT");}finally{f.close();}});

test("attempt creation rejects a structurally forged reconstructed context",()=>{const f=fixture();try{const forged={bytes:f.context.bytes,manifest:f.context.manifest,binding:f.context.binding};assert.throws(()=>createBoundAttempt({decision:f.decision,taskId:"t",attemptId:"a",generation:1,pin:f.pin,context:forged}),/CONTEXT_RECONSTRUCTION_UNAUTHENTICATED/);assert.equal(createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1}).code,"ATTEMPT_CREATED");}finally{f.close();}});
