import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createRunGenesis, createWorkspaceGenesis, domainDigest, sealEventEnvelope } from "@horseness/domain";
import { SQLiteAuthority, createOrLoadAuthorityCredential } from "@horseness/store-sqlite";
import { createBoundAttempt, requestAttemptCancellation, recordAttemptOutcome, assertImmutableBinding, rehydrateBoundAttempt } from "../../src/attempts/index.js";
import { selectReadyTasks } from "../../src/scheduler/index.js";
import { activateTask, addTask, emptyTaskProjection, evaluateTaskJoin, issueStoredAuthorityEvent, issueTaskAuthorityProjection, type DurableAuthorityEventV1 } from "../../src/tasks/task-projection.js";
import { authenticContextFixture } from "../context/authentic-context.fixture.js";
export function fixture(){
 const root=mkdtempSync(join(tmpdir(),"horseness-c10-attempt-")),database=join(root,"authority.sqlite"),artifacts=join(root,"artifacts"),bootstrap=new SQLiteAuthority(database,artifacts);
 const workspace=createWorkspaceGenesis({workspaceId:"w",authorityPrincipalId:"authority",initialGrantDigest:"grant",authorityConsumptionMarker:"marker",activePolicyDigest:"policy",commandId:"workspace"});bootstrap.appendAtomic({commandId:"workspace",workspace:{streamKind:"workspace",workspaceId:"w",streamId:"w",expectedSequence:0,expectedEnvelopeHash:null,events:[workspace.event]}});
 const absent={...workspace.resultCursor,kind:"absent-run-genesis" as const,runId:"r",expectedRunHead:"absent" as const},run=createRunGenesis({observationCursor:absent,initialDocument:{},principalId:"authority",commandId:"run"});bootstrap.appendAtomic({commandId:"run",runGenesis:{observationCursor:absent,event:run.event}});
 const head=sealEventEnvelope({schemaVersion:"1",eventId:"head",streamKind:"run",workspaceId:"w",streamId:"r",sequence:2,priorEnvelopeHash:run.event.envelopeHash,eventType:"ProposalSubmittedV1",payload:{eventType:"ProposalSubmittedV1",workspaceId:"w",runId:"r",proposalId:"head",proposalDigest:"head"},principalId:"authority",causationId:"head",correlationId:"run",idempotencyKey:"head"});bootstrap.appendAtomic({commandId:"head",run:{streamKind:"run",workspaceId:"w",streamId:"r",expectedSequence:1,expectedEnvelopeHash:run.event.envelopeHash,events:[head]}});bootstrap.close();
 const opened=SQLiteAuthority.openAuthenticatedWorkspace(database,artifacts,{workspaceId:"w",sessionId:`c10-${root}`,credential:createOrLoadAuthorityCredential(database,artifacts,"w")}),cursor=opened.reader.authenticatedView("w","r").cursor,payload={eventType:"DeltaAcceptedV1" as const,workspaceId:"w",runId:"r",taskId:"t",proposalDigest:"p",resultingRevision:1,resultingStateHash:"state"},sealed=sealEventEnvelope({schemaVersion:"1",eventId:"accepted",streamKind:"run",workspaceId:"w",streamId:"r",sequence:2,priorEnvelopeHash:run.event.envelopeHash,eventType:"DeltaAcceptedV1",payload,principalId:"authority",causationId:"accepted",correlationId:"run",idempotencyKey:"accepted"}),record:DurableAuthorityEventV1={envelope:sealed.envelope,envelopeHash:sealed.envelopeHash,resultCursor:cursor};
 const snapshot=(name:string,state:unknown):void=>{opened.authority.db.prepare("INSERT OR REPLACE INTO snapshots(workspace_id,stream_kind,stream_id,sequence,envelope_hash,projection_name,projection_version,state_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run("w","run","r",2,head.envelopeHash,name,"1",JSON.stringify(state),"2026-01-01T00:00:00.000Z")};
 snapshot("durable-authority-event/DeltaAcceptedV1/2",record);for(const state of [{kind:"contract",valid:true},{kind:"policy",state:"allowed"},{kind:"grant-revocation",grantState:"allowed",revocationState:"clear"},{kind:"quota",state:"available"},{kind:"attempt-outcome",state:"none"}])snapshot(`task-authority/${state.kind}`,{taskId:"t",...state});
 const accepted=issueStoredAuthorityEvent(opened.reader,{workspaceId:"w",runId:"r",sequence:2,eventType:"DeltaAcceptedV1"});let projection=emptyTaskProjection();projection=addTask(projection,{taskId:"t",contractDigest:"contract",completionPolicy:{schemaVersion:"1",kind:"predicate",predicate:{kind:"receipt-only"}}});projection=activateTask(projection,"t");const joinEvaluation=evaluateTaskJoin(projection,{taskId:"t",cursor,authority:issueTaskAuthorityProjection(opened.reader,{workspaceId:"w",runId:"r",taskId:"t"})});const decision=selectReadyTasks([{taskId:"t",priority:1,createdSequence:1,join:joinEvaluation,deltaAccepted:accepted,proposalDigest:"p"}])[0]!,issued=authenticContextFixture();return{decision,pin:issued.pin,context:issued.context,close(){issued.close();opened.authority.close();rmSync(root,{recursive:true,force:true});}};
}
test("duplicate authorization is idempotent and binding remains immutable across cancellation/outcome",()=>{const f=fixture();try{const created=createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1});const duplicate=createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1,existing:created.attempt});assert.equal(duplicate.code,"DUPLICATE_AUTHORIZATION");assert.equal(duplicate.attempt,created.attempt);const cancelled=requestAttemptCancellation(created.attempt);assertImmutableBinding(created.attempt,cancelled.attempt);const late=recordAttemptOutcome(cancelled.attempt,"succeeded");assertImmutableBinding(created.attempt,late.attempt);assert.equal(late.attempt.outcome,"succeeded");assert.equal(requestAttemptCancellation(late.attempt).code,"CANCELLATION_IDEMPOTENT");}finally{f.close();}});

test("attempt creation rejects a structurally forged reconstructed context",()=>{const f=fixture();try{const forged={bytes:f.context.bytes,manifest:f.context.manifest,binding:f.context.binding};assert.throws(()=>createBoundAttempt({decision:f.decision,taskId:"t",attemptId:"a",generation:1,pin:f.pin,context:forged}),/CONTEXT_RECONSTRUCTION_UNAUTHENTICATED/);assert.equal(createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1}).code,"ATTEMPT_CREATED");}finally{f.close();}});

test("serialized attempts rehydrate and forged same-key duplicates fail",()=>{const f=fixture();try{const created=createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1}).attempt;const restarted=rehydrateBoundAttempt(structuredClone(created));assert.equal(createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1,existing:restarted}).code,"DUPLICATE_AUTHORIZATION");const forged=structuredClone(created);forged.taskId="other";assert.throws(()=>rehydrateBoundAttempt(forged),/ATTEMPT_DIGEST_MISMATCH/);const sameKey=structuredClone(created);sameKey.taskId="other";const{attemptDigest:_,...core}=sameKey;sameKey.attemptDigest=domainDigest("horseness.bound-attempt.v1",core);assert.throws(()=>createBoundAttempt({...f,taskId:"t",attemptId:"a",generation:1,existing:rehydrateBoundAttempt(sameKey)}),/ATTEMPT_ALREADY_EXISTS/);}finally{f.close();}});
